### PR TITLE
Fix spurious symbols, take two (Fixes #475)

### LINKED ISSUE #475: Additional, unwanted symbols exported on Cosmic
From https://launchpadlibrarian.net/379506489/buildlog_ubuntu-cosmic-i386.mir_0.32.1+dev40-g6d4378fd96-0ubuntu18.10_BUILDING.txt.gz

```
dpkg-gensymbols: warning: some new symbols appeared in the symbols file: see diff output below
dpkg-gensymbols: warning: /<<BUILDDIR>>/mir-0.32.1+dev40-g6d4378fd96/build-i386/src/miral/libmiral3.symbols doesn't match completely debian/libmiral3.symbols
--- debian/libmiral3.symbols (libmiral3_2.3.0_i386)
+++ dpkg-gensymbolsx6hsAf	2018-07-21 11:10:34.589336977 +0000
@@ -3,6 +3,29 @@
  MIRAL_2.1@MIRAL_2.1 2.1.0
  MIRAL_2.2@MIRAL_2.2 2.2.0
  MIRAL_2.3@MIRAL_2.3 2.3.0
+ XcursorImagesDestroy@Base 2.3.0
+ _Z19join_client_threadsPN3mir6ServerE@Base 2.3.0
+ _ZN5miral13MRUWindowList4pushERKNS_6WindowE@Base 2.3.0
+ _ZN5miral13MRUWindowList5eraseERKNS_6WindowE@Base 2.3.0
+ _ZN5miral13XCursorLoaderC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE@Base 2.3.0
+ _ZN5miral18BasicWindowManagerC1EPN3mir5shell15FocusControllerERKSt10shared_ptrINS2_13DisplayLayoutEERKS5_INS2_22PersistentSurfaceStoreEERNS1_17ObserverRegistrarINS1_8graphics28DisplayConfigurationObserverEEERKSt8functionIFSt10unique_ptrINS_22WindowManagementPolicyESt14default_deleteISL_EERKNS_18WindowManagerToolsEEE@Base 2.3.0
+ _ZN5miral20CoordinateTranslator16enable_debug_apiEv@Base 2.3.0
+ _ZN5miral20CoordinateTranslator17disable_debug_apiEv@Base 2.3.0
+ _ZN5miral29DisplayConfigurationListeners12add_listenerEPNS_21ActiveOutputsListenerE@Base 2.3.0
+ _ZN5miral29DisplayConfigurationListeners15delete_listenerEPNS_21ActiveOutputsListenerE@Base 2.3.0
+ _ZN5miral29DisplayConfigurationListeners20configuration_failedERKSt10shared_ptrIKN3mir8graphics20DisplayConfigurationEERKSt9exception@Base 2.3.0
+ _ZN5miral29DisplayConfigurationListeners21configuration_appliedERKSt10shared_ptrIKN3mir8graphics20DisplayConfigurationEE@Base 2.3.0
+ _ZN5miral29DisplayConfigurationListeners21initial_configurationERKSt10shared_ptrIKN3mir8graphics20DisplayConfigurationEE@Base 2.3.0
+ _ZN5miral29DisplayConfigurationListeners26base_configuration_updatedERKSt10shared_ptrIKN3mir8graphics20DisplayConfigurationEE@Base 2.3.0
+ _ZN5miral29DisplayConfigurationListeners29session_configuration_appliedERKSt10shared_ptrIN3mir8frontend7SessionEERKS1_INS2_8graphics20DisplayConfigurationEE@Base 2.3.0
+ _ZN5miral29DisplayConfigurationListeners29session_configuration_removedERKSt10shared_ptrIN3mir8frontend7SessionEE@Base 2.3.0
+ _ZN5miral29DisplayConfigurationListeners32catastrophic_configuration_errorERKSt10shared_ptrIKN3mir8graphics20DisplayConfigurationEERKSt9exception@Base 2.3.0
+ _ZNK5miral29DisplayConfigurationListeners22process_active_outputsERKSt8functionIFvRKSt6vectorINS_6OutputESaIS3_EEEE@Base 2.3.0
+ _ZTIN5miral20CoordinateTranslatorE@Base 2.3.0
+ _ZTIN5miral21ActiveOutputsListenerE@Base 2.3.0
+ _ZTIN5miral29DisplayConfigurationListenersE@Base 2.3.0
+ _ZTVN5miral13XCursorLoaderE@Base 2.3.0
+ _ZTVN5miral21ActiveOutputsListenerE@Base 2.3.0
  (c++)"miral::AddInitCallback::AddInitCallback(std::function<void ()> const&)@MIRAL_2.0" 2.0.0
  (c++)"miral::AddInitCallback::operator()(mir::Server&) const@MIRAL_2.0" 2.0.0
  (c++)"miral::AddInitCallback::~AddInitCallback()@MIRAL_2.0" 2.0.0
@@ -306,3 +329,4 @@
  (c++)"typeinfo for miral::WindowManagementPolicy@MIRAL_2.0" 2.0.0
  (c++)"vtable for miral::CanonicalWindowManagerPolicy@MIRAL_2.0" 2.0.0
  (c++)"vtable for miral::WindowManagementPolicy@MIRAL_2.0" 2.0.0
+ xcursor_load_theme@Base 2.3.0
```

### PR DESCRIPTION
**Pull request by RAOF**
Fix (or, rather, work around) in a way that doesn't require source changes.

The `gold` linker doesn't add spurious debugging symbols, unlike Cosmic's `bfd` linker. As an added bonus, the `gold` linker is roughly twice as fast as the `bfd` linker, *and* produces better warnings.

### CODE REVIEW

**Comment by gerboland** [comment]
I'm a bit wary of debian packages using a different default linker to the default cmake config. If it works on all platforms, why not just use the gold linker by default?

**Comment by RAOF** [comment]
I'd be happy to change the default to gold. It's significantly faster and provides better warnings.

Presumably Fedora will also hit this at some point, so changing the default should also head that off.

**Comment by AlanGriffiths** [comment]
I guess the remaining question is: is this simply a bug in `ld` that will be fixed sooner or later or a feature that we'll need to deal with long term?

**Comment by AlanGriffiths** [comment]
After chatting we decided on another approach: "[take three](https://github.com/MirServer/mir/pull/484)"

**Pull request closed without merging**
