### PR TITLE
[debian] enable LTO on jammy again

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
bors merge

**Comment by Saviq** [comment]
bors retry

**Comment by AlanGriffiths** [comment]
Maybe now...

bors retry

**Comment by Saviq** [comment]
> Maybe now...

Need to wait for a rebuild of `libinput` in Debian:

https://tracker.debian.org/news/1301009/accepted-libinput-1193-2-source-into-unstable/

**Comment by AlanGriffiths** [comment]
This should now land successfully. :crossed_fingers: 

bors merge

**Comment by Saviq** [comment]
bors retry

**Comment by AlanGriffiths** [comment]
bors merge

**Pull request merged**
