### PR TITLE
Prevent deadlocks in ObserverMultiplexer

### PR DESCRIPTION
**Pull request by wmww**
This PR adds three multiplexer tests (all of which previously deadlocked) and fixes all of them.

The core issue was that spawning an observation required locking the same mutex that remained locked while observations were being processed. The use of `recursive_mutex` mitigated that if everything was on the same thread, but if the receiving-observation thread was blocked on some other thread, which was blocked on sending an observation there was trouble.

This PR uses separate mutexes for spawning and running observations. Both are locked when an observer is unregistered, but unregister does not lock them simultaneously.

This fixes some of the deadlocks I've encountered in #2371, and assuming it's correct is an overall improvement.

### CODE REVIEW

**Review by RAOF — APPROVED** [review]
I think the double-locking and duplicate `weak_ptr` was unnecessarily complicated, and I think my modifications perform the same function.

This does means that we'll need @AlanGriffiths or @graysonguarino to review ;)

**Comment by AlanGriffiths** [comment]
... but re-running the job passed. :confused:

**Review by AlanGriffiths — APPROVED** [review]
LGTM, but now I've added a commit

**Review by AlanGriffiths — APPROVED** [review]
Dropping my wrong-headed commit

bors r+

**Comment by wmww** [comment]
My version had one additional guarantee (that wasn't well documented): The executor wont be used after `unregister_interest()` returns (even if the observer is still alive), By dropping the 2nd lock you lose that guarantee.

**Comment by RAOF** [comment]
Is that a guarantee we need to provide? We've got a set of executors with essentially `'static` lifetime available, and for a custom executor it's not *terribly* difficult to ensure the executor outlives the observer.

**Comment by AlanGriffiths** [comment]
> it's not terribly difficult to ensure the executor outlives the observer.

Any teardown code _doesn't_ control the lifetime of the observer - because ownership is by `shared_ptr<>`.

**Pull request merged**
