### PR TITLE
Only call extension filter once per app per extension

### LINKED ISSUE #2209: MirAL extension filter invoked multiple times for the same app and same protocol
It is invoked for each protocol once every time the client creates a registry (can be multiple times) and once for every time the global is bound. I see no reason it should be called more than once for each app/protocol combination.

### PR DESCRIPTION
**Pull request by wmww**
Updated version of #2211. Fixes #2209.

### CODE REVIEW

**Comment by Saviq** [comment]
@wmww there are a couple conflicts here now, if you could fix.

**Comment by wmww** [comment]
I think they'll go away once #2642 lands

**Comment by wmww** [comment]
Ayy conflicts gone

**Review by RAOF — COMMENTED** [review]
I'm not sure if this is a good idea?

It seems like fair amount of extra complexity? Documenting that the filter function may be called multiple times for the same client/protocol pair seems simpler, and it's not clear to me how usage of the filter API is made more difficult by the requirement that it be callable multiple times.

**Comment by wmww** [comment]
If there's any performance penalty to calling the filter, *someone* should be caching the results. I don't think pushing that complexity to the shell is particularly more attractive.

**Comment by AlanGriffiths** [comment]
As I commented in #2211, I see no need for this and I also don't see why anyone would care about #2209, nor why adding a doc comment wouldn't fix any hypothetical confusion

**Pull request closed without merging**
