### PR TITLE
Set the logind session type

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes: #2833

### CODE REVIEW

**Comment by z3ntu** [comment]
I came up with practically the solution on the `release/1.8` branch
```diff
diff --git a/src/server/console/logind_console_services.cpp b/src/server/console/logind_console_services.cpp
index 9583f40031..43a0fb05a3 100644
--- a/src/server/console/logind_console_services.cpp
+++ b/src/server/console/logind_console_services.cpp
@@ -266,6 +266,15 @@ mir::LogindConsoleServices::LogindConsoleServices(std::shared_ptr<mir::GLibMainL
                 std::string{"Logind TakeControl call failed: "} + error_msg}));
     }
 
+    if (!logind_session_call_set_type_sync(session_proxy.get(), "wayland", nullptr, &error))
+    {
+        std::string const error_msg = error ? error->message : "unknown error";
+
+        BOOST_THROW_EXCEPTION((
+            std::runtime_error{
+                std::string{"Logind SetType call failed: "} + error_msg}));
+    }
+
     g_signal_connect(
         G_OBJECT(session_proxy.get()),
         "notify::active",

```
Seems to work fine now :)

```
$ loginctl show-session c3 | grep Type=
Type=wayland
```

**Comment by AlanGriffiths** [comment]
> ```diff
> +        BOOST_THROW_EXCEPTION((
> +            std::runtime_error{
> +                std::string{"Logind SetType call failed: "} + error_msg}));
> ```

I think refusing to start if the SetName call fails is OTT. Mir can be run on systems that predate this API.

**Comment by AlanGriffiths** [comment]
Oh, and a better incantation for testing is:

```plain
loginctl show-session --property=Type $XDG_SESSION_ID
```

**Comment by z3ntu** [comment]
Hm unfortunately now with repowerd I seem to hit a race condition where it detects the session before the type is changed so it still thinks it's "unspecified"... But honestly this is more a bug in repowerd I guess, not really possible to fix here...

**Review by wmww — APPROVED** [review]
LGTM
bors r+

**Comment by AlanGriffiths** [comment]
bors retry

**Pull request merged**
