### PR TITLE
Fix regenerate-miral-symbols-map.py (and symbols.map)

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Oh! I know what's happening. I have a stray file in `include/miral` Will update...

**Review by wmww — CHANGES_REQUESTED** [review]
I'm still getting this diff, perhaps it's non-deterministic?
```diff
diff --git a/src/miral/symbols.map b/src/miral/symbols.map
index d276700690..ec475464ae 100644
--- a/src/miral/symbols.map
+++ b/src/miral/symbols.map
@@ -297,9 +297,9 @@ global:
     miral::Zone::?Zone*;
     miral::Zone::Zone*;
     miral::Zone::extents*;
+    miral::Zone::id*;
     miral::Zone::is_same_zone*;
     miral::Zone::operator*;
-    miral::Zone::id*;
     miral::application_for*;
     miral::apply_lifecycle_state_to*;
     miral::display_configuration_options*;
```

If you don't think it matters go ahead and merge

bors delegate+

**Review by wmww — APPROVED** [review]
Ops, I guess I should approve
bors delegate+

**Comment by AlanGriffiths** [comment]
> I'm still getting this diff, perhaps it's non-deterministic?

That is weird. I thought these entries were lexically ordered to prevent this. But clearly this PR doesn't cause it. So landing then investigating...

bors r=wmww

**Pull request merged**
