### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Release 1.6.0

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
## Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

Target|Tested| Status| Comments
------------ | -------------|---|--
18.04LTS||
16.04LTS||
19.04||
19.10||
Nvidia||

## mir-test-tools

Target|Tested| Status| Comments
------------ | -------------|---|--
18.04LTS|||
16.04LTS|||
19.04|||
19.10|||
Core18 (AMD64)|||
Core18 (armhf)|||

## mir-kiosk
Target|Tested| Status| Comments
------------ | -------------|---|--
18.04LTS|||
16.04LTS|||
19.04|||
19.10|||
Core18 (AMD64)|||
Core18 (armhf)|||

**Comment by RAOF** [comment]
Tested on 20.04 with NVIDIA: qterminal, glmark2-es-wayland, and es2gears_wayland all work as expected.

**Comment by AlanGriffiths** [comment]
## Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

Target|Tested| Status| Comments
------------ | -------------|---|--
18.04LTS|1.6.0||
16.04LTS|1.6.0||
19.04|1.6.0|Completed| See note 1
19.10|1.6.0|Completed| See note 1
Nvidia|1.6.0||

### 1. Qt app menus appear in weird places.

This seems to be a Qt issue as it can be reproduced with `QT_QPA_PLATFORM=wayland <app>` on Gnome DE.

## mir-test-tools

Target|Tested| Status| Comments
------------ | -------------|---|--
18.04LTS|1.6.0||
16.04LTS|1.6.0||
19.04|1.6.0||
19.10|1.6.0||
Core18 (AMD64)|||
Core18 (armhf)|1.6.0|Completed|

## mir-kiosk
Target|Tested| Status| Comments
------------ | -------------|---|--
18.04LTS|1.6.0||
16.04LTS|1.6.0||
19.04|1.6.0||
19.10|1.6.0||
Core18 (AMD64)|||
Core18 (armhf)|1.6.0|

**Pull request merged**
