### PR TITLE
Mir release 1.1

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
18.04: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

**Comment by AlanGriffiths** [comment]
18.10: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

**Comment by AlanGriffiths** [comment]
16.04: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

**Comment by AlanGriffiths** [comment]
19.04: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

**Comment by AlanGriffiths** [comment]
We should fix #661 before release

**Comment by AlanGriffiths** [comment]
We also need to solve #662

**Comment by RAOF** [comment]
The new build should fix #662; the egl-wayland package is no longer broken, so #661 is also fixed.

**Comment by AlanGriffiths** [comment]
16.04: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

**Comment by AlanGriffiths** [comment]
18.10: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

**Comment by AlanGriffiths** [comment]
\o/ I now have a way to reproduce the message @gerboland saw last week:
```
[2018-12-17 10:14:46.872497] <CRITICAL> frontend:Wayland: Exception processing Surface::commit() request: /build/mir-fN5xrV/mir-1.1.0~rc12-gd4574168b8/src/miral/basic_window_manager.cpp(1949): Throw in function void miral::BasicWindowManager::validate_modification_request(const miral::WindowSpecification&, const miral::WindowInfo&) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: width must be positive
```
On 18.10 I ran:

    $ miral-desktop -kiosk

then ran some programs and exited. The above appeared in the log.

**Comment by AlanGriffiths** [comment]
19.04: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

**Comment by AlanGriffiths** [comment]
18.04: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

**Comment by RAOF** [comment]
Although we might want to cherry-pick #678

**Comment by AlanGriffiths** [comment]
> @RAOF Although we might want to cherry-pick #678

I'd prefer not to add any more changes, and we've done a lot of testing without: this can it wait?

**Comment by RAOF** [comment]
> > @RAOF Although we might want to cherry-pick #678
> 
> I'd prefer not to add any more changes, and we've done a lot of testing without: this can it wait?

Yes; it doesn't prevent Mir from working, it just fails to prevent Mir from trying to work on NVIDIA driver versions Gerry found not to work.

**Comment by AlanGriffiths** [comment]
18.10: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

Also, mir-smoke-test-runner passed on 19.04 mesa-kms and mesa-x11

**Comment by AlanGriffiths** [comment]
16.04: pass https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

**Pull request merged**
