### PR TITLE
Refresh distros

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
alpine-3.18 was just released, we can either keep it here (it won't block merges) until it starts working, or drop it.

**Review by AlanGriffiths — APPROVED** [review]
bors merge

**Comment by AlanGriffiths** [comment]
> Configuration problem:
> bors.toml: not found

Oh! we're already in the post-bors era. Do I need to do anything more?

**Comment by Saviq** [comment]
> Oh! we're already in the post-bors era. Do I need to do anything more?

Yeah, merge the prerequisite: #2922

That part of the story (chaining PRs) isn't great, yet.

**Comment by Saviq** [comment]
> That part of the story (chaining PRs) isn't great, yet.

But at least:
image

So the missing piece is being able to queue behind the prerequisite.

**Pull request merged**
