### PR TITLE
Mir 0.30 release

### PR DESCRIPTION
**Pull request by RAOF**
We've got a bunch of functional changes, so let's release them!

(This commit will need to be amended before actual release)

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Do we need to bump to 0.30?

I thought there were no ABI or API changes - which would make 0.29.1 consistent

**Comment by Saviq** [comment]
We do now... [ppa:mir-team/rc](https://launchpad.net/~mir-team/+archive/ubuntu/rc)

**Comment by RAOF** [comment]
We've got functional changes, so I thought a minor version bump was appropriate - 0.29.1 would be the version if this was a bugfix-only release, right?

I've added a 0.30 milestone that we can add things that should block the release to.

**Comment by Conan-Kudo** [comment]
@AlanGriffiths I think you mean g++8 (we don't have GCC 5.8 in Rawhide, we have GCC 8).

**Comment by AlanGriffiths** [comment]
Yes, g++8.

**Comment by Conan-Kudo** [comment]
@AlanGriffiths @RAOF Is this supposed to be happening? 

```
[ 18%] Building CXX object src/server/input/CMakeFiles/mirinput.dir/null_input_dispatcher.cpp.o
cd /builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/x86_64-redhat-linux-gnu/src/server/input && /usr/bin/c++  -DLOG_NDEBUG=1 -DMESA_EGL_NO_X11_HEADERS -DMIR_DRMMODEADDFB_HAS_CONST_SIGNATURE -DMIR_LOG_COMPONENT_FALLBACK=\"mirserver\" -DMIR_SERVER_EGL_OPENGL_API=EGL_OPENGL_ES_API -DMIR_SERVER_EGL_OPENGL_BIT=EGL_OPENGL_ES2_BIT -DMIR_SERVER_GLEXT_H="<GLES2/gl2ext.h>" -DMIR_SERVER_GL_H="<GLES2/gl2.h>" -DMIR_SERVER_GRAPHICS_PLATFORM_VERSION=\"MIR_GRAPHICS_PLATFORM_0.27\" -DMIR_SERVER_INPUT_PLATFORM_VERSION=\"MIR_INPUT_PLATFORM_0.27\" -DMIR_SERVER_PLATFORM_PATH=\"/usr/lib64/mir/server-platform\" -DMIR_VERSION=\"0.29.0\" -DMIR_VERSION_MAJOR=0 -DMIR_VERSION_MICRO=0 -DMIR_VERSION_MINOR=29 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/include/core -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/include/common -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/include/cookie -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/src/include/common -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/x86_64-redhat-linux-gnu/src/capnproto -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/x86_64-redhat-linux-gnu/src/protobuf -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/include/platform -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/include/client -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/include/server -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/include/renderer -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/include/renderers/gl -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/include/renderers/sw -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/src/include/platform -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/src/include/client -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/src/include/server -I/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/src/include/cookie -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -pthread -g -std=c++14 -Werror -Wall -fno-strict-aliasing -pedantic -Wnon-virtual-dtor -Wextra -fPIC -Wno-psabi -flto -ffat-lto-objects   -o CMakeFiles/mirinput.dir/null_input_dispatcher.cpp.o -c /builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/src/server/input/null_input_dispatcher.cpp
/builddir/build/BUILD/mir-0f97cb39541fa1856690e22a1e3d1260c89072ac/src/server/input/null_input_dispatcher.cpp:19:10: fatal error: boost/asio/detail/shared_ptr.hpp: No such file or directory
 #include <boost/asio/detail/shared_ptr.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
{standard input}: Assembler messages:
{standard input}: Error: .size expression for null_input_dispatcher.cpp does not evaluate to a constant
make[2]: *** [src/server/input/CMakeFiles/mirinput.dir/build.make:378: src/server/input/CMakeFiles/mirinput.dir/null_input_dispatcher.cpp.o] Error 1
```
From: https://copr-be.cloud.fedoraproject.org/results/ngompa/mir-prerel-fedora/fedora-rawhide-x86_64/00712868-mir/build.log.gz

The header doesn't exist in Boost 1.66: https://koji.fedoraproject.org/koji/rpminfo?fileStart=550&rpmID=12763755&fileOrder=name&buildrootOrder=-id&buildrootStart=0#filelist

**Comment by AlanGriffiths** [comment]
@Conan-Kudo that header isn't used. I suspect it was "#include"d by mistake.

**Comment by AlanGriffiths** [comment]
@RAOF I think this is about ready.

As far as I can see there's just a linker tweak pending: PR #162 (to fix the rawhide build)

**Comment by Saviq** [comment]
Hmm I just got emails from Launchpad that the most recent build (of `5ddaf04`) was rejected, because it already existed in the `rc` PPA, did someone restart the Travis job? In any case, next step would be to push a `v0.30.0` tag :)

**Comment by AlanGriffiths** [comment]
@Saviq that's an unintended side-effect of my pushing a commit accidentally and then removing it. Nothing to be concerned about.

**Comment by AlanGriffiths** [comment]
>  In any case, next step would be to push a v0.30.0 tag :)

AIUI We also need to update MIR_VERSION_MINOR in CMakeLists.txt (as we have not reached agreement over https://github.com/MirServer/mir/pull/118)

**Comment by RAOF** [comment]
Currently testing this.

**Comment by AlanGriffiths** [comment]
@RAOF re testing this: I've been using this on Fedora rawhide & 27 (from the COPR - which lacks 
the last couple of commits) and Ubuntu 17.10 (from the PPA) without problems. (Also `mir-smoke-test-runner` runs OK on these.)

**Comment by RAOF** [comment]
Tested in a 16.04 VM, KMS backend works fine.
Tested on bionic AMD/NVIDIA hybrid system and Intel - KMS backend works fine, X11 backend works fine.

Let's see if I correctly understand the release process!

**Comment by AlanGriffiths** [comment]
Hmm, changelog not been written. But we're tagged so...

bors r+

**Pull request merged**
