### PR TITLE
0.31 release

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@AlanGriffiths Did someone forget to merge the `debian/changelog` contents for 0.30.0 into this?

**Comment by AlanGriffiths** [comment]
@Conan-Kudo maybe I missed it, but I've not seen a 0.30 debian/changelog

**Comment by Conan-Kudo** [comment]
@AlanGriffiths I'm not sure if there is supposed to be one. The lack of an 0.30.0 entry caused #217.

**Comment by Conan-Kudo** [comment]
Mir pre-release build for Fedora: https://copr.fedorainfracloud.org/coprs/ngompa/mir-prerel-fedora/build/728255/

There seems to be an interesting failure for Fedora 28 x86_64: https://copr-be.cloud.fedoraproject.org/results/ngompa/mir-prerel-fedora/fedora-28-x86_64/00728255-mir/build.log.gz

I'm not sure if it's spurious or something else...

**Comment by AlanGriffiths** [comment]
@Conan-Kudo that error is just the one configuration? It looks like the compiler and linker are in disagreement about whether functions are used. I hope it is spurious.

**Comment by Conan-Kudo** [comment]
Re-running the build: https://copr.fedorainfracloud.org/coprs/ngompa/mir-prerel-fedora/build/728338/

**Comment by AlanGriffiths** [comment]
Doh! If we don't build the EGL examples we can't package them.

**Comment by Conan-Kudo** [comment]
@AlanGriffiths It looks like the problem in Fedora 28 is reproducible...

**Comment by AlanGriffiths** [comment]
@Conan-Kudo I'll try to reproduce in the morning

**Comment by AlanGriffiths** [comment]
@Conan-Kudo I've built Mir successfully on my rawhide VM today. (Both using a default git clone, cmake, make and using mock with your source rpm.) Could this have been transient "build tools are out of step"?

**Comment by Conan-Kudo** [comment]
Rawhide is fine, but Fedora 28 is not. Those are not necessarily the same anymore. But yes, it's possible.

**Comment by AlanGriffiths** [comment]
Oh, I'm not sure which my VM is on then. I've just run normal updates since switching it from 27.

Probably time for new one. ;)

**Comment by Conan-Kudo** [comment]
Fedora 28 branched from Rawhide at the end of February: https://fedoraproject.org/wiki/Releases/28/Schedule

Rawhide is now what will be Fedora 29.

**Comment by AlanGriffiths** [comment]
@Conan-Kudo doing things right I can reproduce the build error in mock. (But it still looks like something weird in the toolchain.)

**Comment by WebDrake** [comment]
> @AlanGriffiths I'm not sure if there is supposed to be one. The lack of an 0.30.0 entry caused #217.

Ah, so it is meant to be manually added before a release is tagged?  I wasn't sure if you folks had switched to some kind of package build-system that automatically generated the changelog from commits since last tag.

**Comment by AlanGriffiths** [comment]
Tested OK:
  o Ubuntu 16.04 , 17.10 and 18.04
  o Debian 26, 27 and rawhide

Issues:
  o FTBFS fedora-28-x86_64: https://copr-be.cloud.fedoraproject.org/results/ngompa/mir-prerel-fedora/fedora-28-x86_64/00728338-mir/

**Comment by Conan-Kudo** [comment]
> o Debian 26, 27 and rawhide

I don't think Debian has had 27 major releases. :)

It looks like Fedora 28's issue may be caused by this: https://bugzilla.redhat.com/show_bug.cgi?id=1557511

I'm investigating to see if it is fixed when annobin is updated or disabled.

**Comment by AlanGriffiths** [comment]
> @Conan-Kudo It looks like Fedora 28's issue may be caused by this: https://bugzilla.redhat.com/show_bug.cgi?id=1557511

That does indeed look like the same issue. I'll leave that to you. ;)

**Comment by AlanGriffiths** [comment]
@Conan-Kudo any news on the Fedora 28 build?

**Comment by Conan-Kudo** [comment]
Scratch build being run to see if issue is fixed: https://koji.fedoraproject.org/koji/taskinfo?taskID=25834766

**Comment by AlanGriffiths** [comment]
bors r=RAOF

**Pull request merged**
