### PR TITLE
Remove dead Wayland keymap code

### PR DESCRIPTION
**Pull request by wmww**
I believe this is not related to #997, but it is a possibility

### CODE REVIEW

**Comment by wmww** [comment]
Still waiting for review

**Comment by AlanGriffiths** [comment]
> Still waiting for review

As discussed elsewhere I think the problem is that this is not called, not that it should not exist.

**Comment by wmww** [comment]
I think it should not exist because it's a redundant code path. The keymap *should* be changed via `WaylandSurfaceObserver::keymap_changed()` -> `WlKeyboard::set_keymap(Keymap const&)` which is left untouched.

**Comment by wmww** [comment]
bors r=AlanGriffiths

**Comment by AlanGriffiths** [comment]
Oh, this hung after the switch to travis.com? Merged

**Pull request merged**
