### PR TITLE
Send keyboard state with wl_keyboard.enter event.

### PR DESCRIPTION
**Pull request by RAOF**

### CODE REVIEW

**Comment by RAOF** [comment]
bors try

**Comment by AlanGriffiths** [comment]
Failure shoudln't be related:

356/356 Test  #39: mir_acceptance_tests.NestedServer.* .....................................................***Timeout 600.01 sec

bors r+

**Comment by AlanGriffiths** [comment]
@Saviq there's been a few linode/spread issues today.

Bors r+

**Comment by Saviq** [comment]
Indeed, a handful of them timed out. That last one seems to be a compiler error on Fedora though?

**Comment by AlanGriffiths** [comment]
> Indeed, a handful of them timed out. That last one seems to be a compiler error on Fedora though?
So it  seems. It passed before though: https://travis-ci.org/MirServer/mir/jobs/337993184

But this looks weird:

```
$ export SYSTEM=fedora-27
$ export VARIANT=amd64

$ export CXX=g++
$ export CC=gcc
$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

bors r+

**Comment by RAOF** [comment]
The most recent failure was 
a) Spread failing to launch the Ubuntu 16.04 Linode instance, which is transitory, and
b) Fedora 27 exploding somewhere in glm.

Neither of these are actually Our Fault™ (although they might be our problem). @Conan-Kudo - any insight on glm suddenly blowing up on Fedora 27?

**Comment by Conan-Kudo** [comment]
@RAOF I don't know what glm is?

**Comment by AlanGriffiths** [comment]
I see in the build log:
```
[MIRROR] gcc-c++-7.3.1-2.fc27.x86_64.rpm: Status code: 404 for http://mirror.its.dal.ca/pub/fedora/linux/updates/27/x86_64/Packages/g/gcc-c++-7.3.1-2.fc27.x86_64.rpm
[MIRROR] gcc-7.3.1-2.fc27.x86_64.rpm: Status code: 404 for http://mirror.its.dal.ca/pub/fedora/linux/updates/27/x86_64/Packages/g/gcc-7.3.1-2.fc27.x86_64.rpm
(18/246): gcc-c++-7.3.1-2.fc27.x86_64.rpm       7.9 MB/s |  11 MB     00:01    
```
I *think* the problem lies in: /usr/include/glm/simd/platform.h which fails to detect g++ 7.3 vis:
```
#	elif (__GNUC__ == 7) && (__GNUC_MINOR__ == 2)
#		define GLM_COMPILER (GLM_COMPILER_GCC72)
#	elif (__GNUC__ >= 8)
#		define GLM_COMPILER (GLM_COMPILER_GCC80)
#	else
#		define GLM_COMPILER (GLM_COMPILER_GCC)
#	endif
```
As a data point, my F27 system had a bunch of updates pending. I've installed them and run a clean build of Mir successfully.

BUT for me:
```
$ g++ --version
g++ (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)
```
@Saviq @RAOF you guys understand how the spread is set up: why is it picking up a newer g++?

**Comment by Conan-Kudo** [comment]
GCC 7.3.1 was just pushed this morning:
* F27: https://bodhi.fedoraproject.org/updates/FEDORA-2018-75d88970d0
* F26: https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa879be08e

**Comment by Saviq** [comment]
It's just using whatever [Linode has prepared](https://www.linode.com/distributions) as the image and then installs the packages as per [the spread task](https://github.com/MirServer/mir/blob/master/spread/build/fedora/task.yaml#L4), so it's not doing much special.

You can always try locally with lxd:
```
$ snap install spread
$ cd $MIR_SOURCE
$ spread lxd:fedora-27:spread/build/fedora:amd64
```

**Comment by AlanGriffiths** [comment]
@Conan-Kudo I hope glm-devel was updated with compiler detection to match?

**Comment by Conan-Kudo** [comment]
@AlanGriffiths It was in Rawhide, but not any built version for F27. :(

If you can file a bug for that against `glm`, then I can get this fixed.

**Comment by Saviq** [comment]
You *could* try locally in lxd except for [this issue](https://github.com/snapcore/spread/issues/42).

**Comment by AlanGriffiths** [comment]
@Conan-Kudo https://bugzilla.redhat.com/show_bug.cgi?id=1542941

**Comment by AlanGriffiths** [comment]
After a manual refresh I too got an update to g++7.3.1 and can reproduce. ;)

**Comment by AlanGriffiths** [comment]
We understand the issue. @Saviq in your role as owner could you land this PR? 

(Also, we should probably disable Fedora 27 builds for the time being.)

**Pull request merged**
