### PR TITLE
Better background for miral-shell

### PR DESCRIPTION
**Pull request by AlanGriffiths**
When we were in Den Haag I took a picture of the Peace Wall to use as a Mir backgound...

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Oh! I guess that was a timeout. (Writing C++ via python can be slow.)

**Comment by gerboland** [comment]
Is there a way to turn this off?

I did once notice the startup animation wasn't perfect, where I saw the wallpaper first, then the startup animation client started and did the fade-from-black thing.

Also it exposes the lack of text antialiasing, or is it transparency of the aliased bits?

**Comment by AlanGriffiths** [comment]
> Is there a way to turn this off?

Don't approve the MP?

> I did once notice the startup animation wasn't perfect, where I saw the wallpaper first, then the startup animation client started and did the fade-from-black thing.

Yes, there's currently no synchronization there.

> Also it exposes the lack of text antialiasing, or is it transparency of the aliased bits?

Well, I'm not entirely convinced by the pre-existing appearance either. The revised formula I chose may not be right:

```
    dest[col] = (0xff*src[col / 4] + (dest[col] * (0xff - src[col / 4])))/0xff;
```

**Comment by gerboland** [comment]
It works ok. Text rendering is improved too. LGTM

bors r+

**Pull request merged**
