### PR TITLE
codecov: don't complain about coverage going down

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Are we seeing a problem this fixes?

**Comment by Saviq** [comment]
> Are we seeing a problem this fixes?

Codecov will put a red ✗ against the PR, so it can deter reviewers.

**Comment by AlanGriffiths** [comment]
> @AlanGriffiths actually, maybe it's better to disable the statuses altogether:

I think that is clearer on the intent.

**Comment by Saviq** [comment]
> I think that is clearer on the intent.

Done.

**Review by AlanGriffiths — APPROVED** [review]
OK, let's try it this way

**Pull request merged**
