### PR TITLE
log: Annotate log functions with [[gnu::format]] attributes

### PR DESCRIPTION
**Pull request by RAOF**
And then fix all the places where we were accidentally invoking nasal daemons.

### CODE REVIEW

**Comment by RAOF** [comment]
Turns out we actually have a bunch of Undefined Behaviour™ in our logging. Notably, there were some log calls which have a mismatching number of format specifiers and actual arguments (eep!), and it turns out that passing a non `void*` to the `%p` format specifier is *technically* UB.

**Comment by RAOF** [comment]
I thought about adding some “this fails to compile” tests, but decided it was a little too much effort. I could be persuaded otherwise…

**Comment by AlanGriffiths** [comment]
Ah! The joy of format types vs typedef'ed types.
```c++
/spread/mir/src/server/frontend_xwayland/xwayland_wm.cpp:181:78: error: format â€˜%luâ€™ expects argument of type â€˜long unsigned intâ€™, but argument 2 has type â€˜std::map<unsigned int, std::shared_ptr<mir::frontend::XWaylandSurface> >::size_type {aka unsigned int}â€™ [-Werror=format=]
         log_debug("Closing %lu XWayland surface(s)...", local_surfaces.size());
```

**Review by AlanGriffiths — APPROVED** [review]
bors r+

**Pull request merged**
