### PR TITLE
Refactor in an attempt to avoid compiler issues

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes: #3017 (maybe)

### CODE REVIEW

**Comment by Saviq** [comment]
Building here: https://launchpad.net/~saviq/+archive/ubuntu/ppa

**Comment by Saviq** [comment]
Nope:

https://launchpadlibrarian.net/683473383/buildlog_ubuntu-mantic-ppc64el.mir_2.15.0-test1_BUILDING.txt.gz

**Comment by AlanGriffiths** [comment]
I should retrieve the incantation to do that myself!

**Comment by Saviq** [comment]
> I should retrieve the incantation to do that myself!

It's just a 
```
dch -D mantic --local -test "test build"
dpkg-buildpackage -S
dput ppa:… ../mir_*.source.changes
```

**Comment by AlanGriffiths** [comment]
> > I should retrieve the incantation to do that myself!
> 
> It's just a
> 
> ```
> dch -D mantic --local -test "test build"
> dpkg-buildpackage -S
> dput ppa:… ../mir_*.source.changes
> ```
> 
> I refreshed at https://launchpad.net/~saviq/+archive/ubuntu/ppa.

I don't see that incantation on https://help.launchpad.net/Packaging/PPA/BuildingASourcePackage

Also IIUC `dpkg-buildpackage -S` actually builds locally. Isn't there a way to bypass that step for testing?

**Comment by AlanGriffiths** [comment]
> This last approach did work:

Well, I can't see the `RealKMSOutputTest` failures on alpine_edge being related to this. And the Snap failures look like connectivity. So I'll mark "Ready for review"

**Review by Saviq — APPROVED** [review]
Yup.

**Pull request merged**
