### PR TITLE
[ci] add 22.04 jammy jellyfish

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
One last time.

bors try

**Comment by Saviq** [comment]
Actually.

bors try-

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
OK. Now.

bors try

**Comment by AlanGriffiths** [comment]
The ubuntu_devel failure is because wlcs has not been uploaded to the PPA for kinetic

**Comment by Saviq** [comment]
> The ubuntu_devel failure is because wlcs has not been uploaded to the PPA for kinetic

Yeah, it picks up the archive one:
```plain
Unpacking wlcs:amd64 (1.3.0-4) ...
```

**Comment by Saviq** [comment]
It's fixed now 👆.

**Review by AlanGriffiths — APPROVED** [review]
bors merge

**Pull request merged**
