### PR TITLE
Sync with wlcs master

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by wmww** [comment]
Want to pull in your latest PR from wlcs (which just got merged)?

**Comment by AlanGriffiths** [comment]
@wmww done

**Comment by AlanGriffiths** [comment]
Hmm mir_wlcs_tests.CopyCutPaste.* failing on 16.04 doesn't sound like a coincidence. Let's see if it is intermittent:

bors try

**Comment by AlanGriffiths** [comment]
Temporarily re-purposed for checking 16,04 workaround works on all platforms

**Comment by AlanGriffiths** [comment]
Restored now workaround has been proved and landed

**Pull request merged**
