### PR TITLE
[autopkgtest] Add file missing from initial autopkgtest commit.

### PR DESCRIPTION
**Pull request by RAOF**
Oops. The autopkgtest calls this CMake snippet, so it should be in the tree!

### CODE REVIEW

**Review by AlanGriffiths — COMMENTED** [review]
I'm not clear where or how this is invoked. (Nor how we would detect that it broke in future)

**Comment by Saviq** [comment]
> I'm not clear where or how this is invoked. (Nor how we would detect that it broke in future)

The Ubuntu infrastructure runs this:
https://github.com/MirServer/mir/blob/main/debian/tests/wlcs

As defined by:
https://github.com/MirServer/mir/blob/main/debian/tests/control

We'd need to build (we do) && install (we don't) packages in CI and run the tests.

**Review by Saviq — COMMENTED** [review]
@RAOF I can't see any reference to this file anywhere, and naively running `sh debian/tests/wlcs`, having installed the dependencies, seems to work?

And I've not found this file anywhere else…

**Comment by RAOF** [comment]
Oh, whoops. I mistook this for `PrintExcludedTests.cmake`, which I *did* add, and *would* cause `sh debian/tests/wlcs` to fail if we didn't.

**Pull request closed without merging**
