### PR TITLE
Provide sensible output names on kms based platforms

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes: #2815

### CODE REVIEW

**Review by graysonguarino — APPROVED** [review]
LGTM, but something in CI seems to be acting up right now

bors delegate

**Comment by AlanGriffiths** [comment]
> something in CI seems to be acting up right now

Not really CI, Ubuntu archives and other downloads are s..l....o......w

**Comment by AlanGriffiths** [comment]
Let's see if things are now working...

bors r=graysonguarino

**Comment by Saviq** [comment]
```
../../../../../../src/platforms/gbm-kms/server/kms/real_kms_display_configuration.cpp:134:19: error: use of ‘auto’ in parameter declaration only available with ‘-fconcepts’ [-Werror]
  134 | void name_outputs(auto& outputs)
      |                   ^~~~
```

**Review by graysonguarino — APPROVED** [review]
There we go!

bors merge

**Pull request merged**
