### PR TITLE
Mir release 1.7.1

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Mir release 1.7.1

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
I know there's some X11 fixes pending, but this is a starting point.

**Comment by AlanGriffiths** [comment]
> I know there's some X11 fixes pending, but this is a starting point.

Latest cherry-picks have fixed all the known blockers.

@wmww, @RAOF we're good to start testing 1.7.1~rc64 in earnest. (At the time of writing it is building in ppa:mir-team/rc.)

**Comment by AlanGriffiths** [comment]
## Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

Target|Tested| Status| Comments
------------ | -------------|---|--
18.04LTS||| 
16.04LTS|||
20.04LTS|rc64|Completed| #1201
19.10|||
Nvidia|||

### 1. Qt app menus appear in weird places.

This seems to be a Qt issue as it can be reproduced with `QT_QPA_PLATFORM=wayland <app>` on Gnome DE.

## mir-test-tools

Target|Tested| Status| Comments
------------ | -------------|---|--
18.04LTS|||
16.04LTS|||
19.10|||
Core18 (AMD64)|||
Core18 (armhf)|||

## mir-kiosk
Target|Tested| Status| Comments
------------ | -------------|---|--
18.04LTS|||
16.04LTS|||
19.10|||
Core18 (AMD64)|||
Core18 (armhf)|||

**Comment by AlanGriffiths** [comment]
@RAOF could you have a look at #1309 to ensure we're not breaking Nvidia with this?

**Comment by wmww** [comment]
I have determined that neither Firefox on XWayland on Mir on NVIDIA or Firefox on Wayland on Mir on NVIDIA were in a better state last release (v1.7.0)

**Comment by AlanGriffiths** [comment]
Merged by hand (because of the conflicts)

**Pull request closed without merging**
