### PR TITLE
{eglstream,mesa}-kms: Ensure queried nodes actually support modesetting.

### PR DESCRIPTION
**Pull request by RAOF**
If the NVIDIA drivers are in use, but the experimental KMS support is not enabled,
the eglstream-kms driver would still bind to the device as the EGL implementation
claims to support everything we need.

Check explicitly for modesetting support on the node we're planning to use, so
we can fall back to something that might work. (Fixes: #672)

### CODE REVIEW

**Comment by RAOF** [comment]
This makes my laptop work, both with `nvidia_drm.modeset=1` enabled and without it in hybrid mode.

**Comment by wmww** [comment]
On Pop!_OS in NVIDIA mode, I still get
```
waiting for /run/user/1000/miral_socket
[2018-12-18 14:59:17.074502] mirserver: Starting
[2018-12-18 14:59:17.078648] <DEBUG> mirserver: Using logind for session management
[2018-12-18 14:59:17.078765] mircommon: Loading modules from: ./bin/../lib/server-modules/
[2018-12-18 14:59:17.078813] mircommon: Loading module: ./bin/../lib/server-modules/graphics-mesa-kms.so.16
[2018-12-18 14:59:17.078835] mircommon: Loading module: ./bin/../lib/server-modules/server-mesa-x11.so.16
[2018-12-18 14:59:17.078849] mircommon: Loading module: ./bin/../lib/server-modules/input-evdev.so.7
[2018-12-18 14:59:17.081114] mircommon: Loading module: ./bin/../lib/server-modules/input-stub.so
[2018-12-18 14:59:17.081860] mircommon: Loading module: ./bin/../lib/server-modules/graphics-dummy.so
[2018-12-18 14:59:17.081875] mircommon: Loading module: ./bin/../lib/server-modules/graphics-throw.so
[2018-12-18 14:59:17.105675] mesa-kms: Device /dev/dri/card0 does not support KMS: Invalid argument
[2018-12-18 14:59:17.106667] mesa-kms: Device /dev/dri/card1 does not support KMS: Invalid argument
[2018-12-18 14:59:17.106728] mirplatform: Found graphics driver: mir:mesa-kms (version 1.0.0) Support priority: 0
[2018-12-18 14:59:17.106745] mirplatform: Found graphics driver: mir:mesa-x11 (version 1.0.0) Support priority: 0
[2018-12-18 14:59:17.106796] mirplatform: Found graphics driver: mir:stub-graphics (version 1.0.0) Support priority: 1
[2018-12-18 14:59:17.106806] mirplatform: Found graphics driver: throw-on-creation (version 1.0.0) Support priority: 0
[2018-12-18 14:59:17.106950] mirserver: Selected driver: mir:stub-graphics (version 1.0.0)
[2018-12-18 14:59:17.115295] mirserver: Using software cursor
[2018-12-18 14:59:17.115874] mircommon: Loading modules from: ./bin/../lib/server-modules/
[2018-12-18 14:59:17.115913] mircommon: Loading module: ./bin/../lib/server-modules/graphics-mesa-kms.so.16
[2018-12-18 14:59:17.115934] mircommon: Loading module: ./bin/../lib/server-modules/server-mesa-x11.so.16
[2018-12-18 14:59:17.115945] mircommon: Loading module: ./bin/../lib/server-modules/input-evdev.so.7
[2018-12-18 14:59:17.150031] mirserver: Selected input driver: mir:evdev-input (version: 1.0.0)
[2018-12-18 14:59:17.155086] mirserver: Mir version 1.0.0
ERROR: /home/wmww/data/code/wayland/mir/src/renderers/gl/renderer.cpp(57): Throw in function mir::renderer::gl::CurrentRenderTarget::CurrentRenderTarget(mir::graphics::DisplayBuffer*)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >
std::exception::what: DisplayBuffer does not support GL rendering
```

**Comment by RAOF** [comment]
Urgh. Please try again; I hit one of the surprisingly buried razors in the DRM API.

**Comment by AlanGriffiths** [comment]
bors r=gerboland

**Pull request merged**
