### PR TITLE
bors: wait for travis PR testing

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by RAOF** [comment]
LGTM
bors r+

**Comment by Saviq** [comment]
Oh I thought it would wait for the status and not just reject it... not so sure we want this then...

**Comment by Saviq** [comment]
No, it rejected because `continuous-integration/travis-ci/pr` wasn't done... I was hoping that it would wait for it, but it plain rejected it... so I'm not sure we actually want that behaviour, since it tests before pushing to master anyway...

**Comment by Saviq** [comment]
I'm gonna close this and let bors do the testing for us on staging, no need to wait for the PR result.

**Pull request closed without merging**
