### PR TITLE
Release 2.8.0

### LINKED ISSUE #2154: [mir_demo_client_wayland_egl_spinner] fails on Xvfb
`mir_demo_client_wayland_egl_spinner` works when running on a real X11 backend but fails on `Xvfb`.

Real (Xwayland/GNOME) backend:
```
env -u WAYLAND_DISPLAY bin/mir_demo_server --test-client bin/mir_demo_client_wayland_egl_spinner
```
Failure when running on `Xvfb`:
```plain
env -u WAYLAND_DISPLAY xvfb-run bin/mir_demo_server --test-client bin/mir_demo_client_wayland_egl_spinner
...
[2021-08-24 14:46:30.444976] < -warning- > gbm-kms-buffer-allocator: Failed to bind EGL Display to Wayland display, falling back to software buffers: /home/alan/CLionProjects/mir/src/platform/graphics/egl_extensions.cpp(92): Throw in function mir::graphics::EGLExtensions::WaylandExtensions::WaylandExtensions(EGLDisplay)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: EGL display doesn't support EGL_WL_bind_wayland_display

[2021-08-24 14:46:30.445011] <information> gbm-kms-buffer-allocator: Cannot enable linux-dmabuf import support: EGL_EXT_image_dma_buf_import_modifiers not supported
[2021-08-24 14:46:30.445025] < - debug - > gbm-kms-buffer-allocator: Detailed error: : /home/alan/CLionProjects/mir/src/platform/graphics/egl_extensions.cpp(206): Throw in function mir::graphics::EGLExtensions::EXTImageDmaBufImportModifiers::EXTImageDmaBufImportModifiers(EGLDisplay)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: EGL_EXT_image_dma_buf_import_modifiers not supported
...
[2021-08-24 14:46:40.556321] <information> server_example_test_client.cpp: Client terminated by signal 11
```

In particular, this affects running smoke tests on `Xvfb`.

### A test setup where you can see what is going on

From your build directory:
```
sudo apt install xvfb x11vnc gvncviewer
env -u WAYLAND_DISPLAY x11vnc -create -localhost -cursor none -env FD_PROG=$(realpath --no-symlinks bin/mir_demo_server) -gone 'killall Xvfb'&
```
Wait for:
> The VNC desktop is:      octopull-PROX15-20:0
> PORT=5900
```
gvncviewer localhost
```
This will give you a (black) VNC window onto what is happening in the Xvfb session.

Now, if you're on a Wayland desktop, that will have created `wayland-1` (on an X11 desktop it will create)= `wayland-0`).

In another terminal/tab run
```
WAYLAND_DISPLAY=wayland-1 bin/mir_demo_client_wayland_egl_spinner
```
This will sometimes crash without showing anything, sometimes show for a second or two, and occasionally run to completion without error.

### LINKED ISSUE #2324: Opening Kate submenus causes menus to disappear
Repro: 
- Open Kate on Wayland
- Open a few submenus
- Eventually the main menu will disappear

Introduced somewhere between v2.5.0 and v2.6.0, I'll update this issue once I bisect down to a specific commit.

Kate running on XWayland is fine.

### LINKED ISSUE #2331: Keyboard focus/keyboard event inconsistancy
#2245 we get
```
Attempt to send keyboard event to wl_surface@# even though it was not given keyboard focus
```
If Mir sends the Wayland frontend keyboard events for a surface that does not have keyboard focus. The problem is there is no synchronization between switching keyboard focus and sending input events, so events sent to the wrong surface could intermittently slip through (this has not been observed in the wild AFAIK). We should either restore the old behavior, or somehow ensure events arrive correctly.

### LINKED ISSUE #2338: [2.7~rc6] fatal error
With ubuntu-frame `beta` (built with [2.7.0~rc60]) and qterminal installed.

From a terminal:

```
export WAYLAND_DISPLAY=wayland-99
ubuntu-frame&
QT_QPA_PLATFORM=wayland qterminal
```

Now, focus on the "Mir-on-X" window and press `Ctrl-Shift-W` and when confirm exit appears press "n".

Finally press a letter.

Expect: the letter appears in the terminal tab
Actual: Mir crashes with:
```
Mir fatal error: Attempt to send keyboard event to wl_surface@8 even though it was not given keyboard focus
```

### LINKED ISSUE #2341: We send pointer events without checking supported version
Repro:
- open glmark-es2-wayland
- scroll

It crashes, complaining about a wl_pointer opcode. Present in 2.6, I'm not sure when it was introduced but I believe it was somewhat recently.

### LINKED ISSUE #2343: Too easy to send unsupported events
If a client binds to a version of a protocol that is older than what we support, sending newer events will generally crash the client. We should not do this. As #2341 demonstrates it is quite easy to do this accidentally. We should consider changing the generated code to either make this harder, or make it harmless.

### LINKED ISSUE #2377: ThreadedDispatcherSignalTest.keeps_dispatching_after_signal_interruption is flaky
This test will *sometimes* fail, with `result.exited_normally()` being false at line 391.

Annoyingly, this only seems to happen when running as a part of the full test suite; just running the `ThreadedDispatcher*` tests in a loop is insufficient to reproduce.

### PR DESCRIPTION
**Pull request by Saviq**
---
> - ABI summary:
>   - miral ABI unchanged at 4
>   - mircommon ABI bumped to 9
>   - mircookie ABI unchanged at 2
>   - mircore ABI unchanged at 1
>   - miroil ABI unchanged at 1
>   - mirplatform ABI unchanged at 23
>   - mirserver ABI bumped to 58
>   - mirwayland ABI unchanged at 3
>   - mirplatformgraphics ABI bumped to 20
>   - mirinputplatform ABI unchanged at 8
> - Enhancements:
>   - Move generated protocol code to build directory (#2300)
>   - Allow --app-env-amend to be supplied multiple times (#2333)
>   - Make window title a configuration option (#2349)
>   - Add fatal_error if unable to bind Wayland socket (#2350)
>   - Add `mold` to the list of supported linkers (#2353)
>   - Platform refactoring towards hybrid GPU support (#2358, #2378, #2407)
>   - Implement wlr_screencopy_unstable_v1 for screenshots (#2383)
>   - Refactor out mf::MirDisplay (#2406)
> - Bugs fixed:
>   - Synchronize buffer swaps to video frame in egl spinner (Fixes #2154)
>   - Do not give menus keyboard focus (Fixes #2324)
>   - Refactor Wayland keyboard input (Fixes #2331)
>   - Further simplify and correct keyboard focus setting (Fixes #2338)
>   - wl_pointer: do not send events when not compatible (Fixes #2341)
>   - Kill clients with error instead of sending unsupported (Fixes #2343)
>   - Initialize sig_handler_desc.sa_mask (#2386)
>   - Fix ThreadedDispatcherSignalTest.keeps_dispatching... (Fixes #2377)

### CODE REVIEW

**Comment by Saviq** [comment]
# rc2

## Debs

Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

### Installed from from ppa:mir-team/rc

Platform|22.04LTS|21.10|20.04LTS
--|--|--|--
gbm-kms|||
gbm-x11|||
eglstream-kms||||
dispmanx||||

Console|22.04LTS|21.10|20.04LTS
--|--|--|--
minimal|||
linux-VT|||
logind|||

WM|22.04LTS|21.10|20.04LTS
--|--|--|--
floating|||
tiling|||
kiosk|||

**Review by AlanGriffiths — APPROVED** [review]
Changelog looks legit

**Review by graysonguarino — APPROVED** [review]

**Comment by AlanGriffiths** [comment]
The rc2 based `beta` snaps of egmde and ubuntu-frame are looking good:

mir-2 8~rc2

**Comment by RAOF** [comment]
Something in 22.04's Mesa stack has changed, and my hybrid AMD/NVIDIA system no longer works: bug #2426. I can fix this by handling the exception, but haven't quite got the code done yet.

**Comment by RAOF** [comment]
We should cherry-pick #2428, #2429, #2430 when they've landed.

**Comment by Saviq** [comment]
> We should cherry-pick #2428, #2429, #2430 when they've landed.

Done.

# rc4

## Debs

Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

### Installed from from ppa:mir-team/rc

Platform|22.04LTS|21.10|20.04LTS
--|--|--|--
gbm-kms|
gbm-x11|
eglstream-kms|
dispmanx|

Console|22.04LTS|21.10|20.04LTS
--|--|--|--
minimal|
linux-VT|
logind|

WM|22.04LTS|21.10|20.04LTS
--|--|--|--
floating|
tiling|
kiosk|

**Comment by wmww** [comment]
On my 21.10 system I'm unable to verify VT support on either this release or 2.7. `sudo miral-shell --console-provider vt --vt 4` switches to TTY4, doesn't show Mir and hangs the system. The power button will gracefully shut down the system, but it is otherwise unresponsive, including to TTY switches. Let me know if I'm doing something wrong.

**Comment by RAOF** [comment]
> On my 21.10 system I'm unable to verify VT support on either this release or 2.7. `sudo miral-shell --console-provider vt --vt 4` switches to TTY4, doesn't show Mir and hangs the system.

So, `sudo miral-shell` will *probably* fail to start Mir because `sudo` will strip `XDG_RUNTIME_DIR` from the command's environment, and so libwayland will fail to bind the Wayland socket and Mir will fail to start.

That seems to leave the VT subsystem in a strange state, but I'm not sure if that's a Mir bug - the Mir process *has terminated* and so definitely doesn't own any VT leases.

**Comment by AlanGriffiths** [comment]
> On my 21.10 system I'm unable to verify VT support on either this release or 2.7. `sudo miral-shell --console-provider vt --vt 4` switches to TTY4, doesn't show Mir and hangs the system. The power button will gracefully shut down the system, but it is otherwise unresponsive, including to TTY switches. Let me know if I'm doing something wrong.

I can reproduce this on 22.04. As Chris says, while Mir provokes this lockup, it really shouldn't happen (regardless of what Mir does).

Here's a command that "works":
```
sudo mkdir /run/user/0
sudo XDG_RUNTIME_DIR=/run/user/0 miral-app -demo-server --console-provider vt --vt 4
```
(Using `-kiosk` also works, but with the default miral-shell launching the terminal fails for reasons we don't care about.)

**Comment by Saviq** [comment]
A regression from 2.7.0 on Focal at least:
- #2431

**Comment by AlanGriffiths** [comment]
> The `mir-smoke-test-runner` when run on `miral-app` in kiosk mode on an Dell XPS 15 9550 via SSH is failing the smoke tests

Looks like installing `inotify-tools` would make a difference

**Comment by graysonguarino** [comment]
> > The `mir-smoke-test-runner` when run on `miral-app` in kiosk mode on an Dell XPS 15 9550 via SSH is failing the smoke tests
> 
> Looks like installing `inotify-tools` would make a difference

That would be wise. I've updated the original comment with the log after `inotify-tools` is installed.

**Comment by AlanGriffiths** [comment]
> miral-app -kiosk --startup-apps mir-smoke-test-runner

This is not going to work as written.

`miral-kiosk` (as started by `miral-app`) is a _Wayland only_ compositor it doesn't run Xwayland to support X11 applications.

`mir-smoke-test-runner` runs `mir_demo_server` which tries to find a platform and expectedly fails:

1. it won't be able to run on the hardware as you already have a desktop or `miral-kiosk` using it;
2. it won't be able to run on X11 as Xwayland isn't provided by `miral-kiosk`; and,
3. you haven't set `MIR_SERVER_WAYLAND_HOST` for it to run on Wayland.

If you run `miral-app -kiosk` and then, in the terminal that this starts in the "Mir on X" window, run `MIR_SERVER_WAYLAND_HOST=$WAYLAND mir-smoke-test-runner` then the tests will run nested on the `miral-kiosk`.

But why are you doing this? Why test that the Mir examples run on a Mir server nested on a Mir server... (I'm not sure what "via SSH" implies, are you using X-forwarding to host all this on an X server another machine?)

**Comment by RAOF** [comment]
Oof. Also needs #2433 cherry-picked.

**Comment by AlanGriffiths** [comment]
I can also confirm that `egmde 155-mir2.8.0~rc5-snap197` (currently the `beta` channel) has been working fine for most of a day.

**Comment by Saviq** [comment]
bors r=AlanGriffiths,graysonguarino,RAOF,wmww,Saviq

**Pull request merged**
