### PR TITLE
Tidy miral dependencies

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Tidy miral dependencies: miral has dependencies on Mir's command line options (mir/options/configuration.h) and there's no obvious reason why that has to be a unpublished header.

Not resolved by this: keymap.cpp depends on mir/udev/wrapper.h. (That appears to be a historical accident.)

### CODE REVIEW

**Comment by wmww** [comment]
Is there a reason for the build failures?

**Comment by AlanGriffiths** [comment]
Hmm. Looks unrelated:
```plain
cd /spread/mir/build-amd64/tests/mir_test && /usr/bin/c++  -DEGL_NO_X11 -DGTEST_VERSION_MAJOR=1 -DGTEST_VERSION_MINOR=10 -DGTEST_VERSION_PATCH=0 -DLOG_NDEBUG=1 -DLTTNG_UST_HAVE_SDT_INTEGRATION -DMESA_EGL_NO_X11_HEADERS -DMIR_BUILD_PLATFORM_MESA_KMS -DMIR_DRMMODEADDFB_HAS_CONST_SIGNATURE -DMIR_LIBINPUT_HAS_ACCEL_PROFILE=1 -DMIR_SERVER_EGL_OPENGL_API=EGL_OPENGL_ES_API -DMIR_SERVER_EGL_OPENGL_BIT=EGL_OPENGL_ES2_BIT -DMIR_SERVER_GLEXT_H="<GLES2/gl2ext.h>" -DMIR_SERVER_GL_H="<GLES2/gl2.h>" -DMIR_VERSION_MAJOR=1 -DMIR_VERSION_MICRO=0 -DMIR_VERSION_MINOR=7 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/spread/mir/include/core -I/spread/mir/include/common -I/spread/mir/include/cookie -I/spread/mir/build-amd64/src/capnproto -I/spread/mir/build-amd64/src/protobuf -I/spread/mir/include/platform -I/spread/mir/include/miral -I/spread/mir/include/server -I/usr/include/uuid -I/spread/mir/include/client -I/spread/mir/include/test -I/spread/mir/include/renderer -I/spread/mir/include/renderers/gl -I/spread/mir/tests/include  -g -O0 -fdebug-prefix-map=/spread/mir=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -pthread -g -std=c++14 -Wall -fno-strict-aliasing -pedantic -Wnon-virtual-dtor -Wextra -fPIC -Werror -Wno-psabi -Wno-error=null-dereference -Wno-error=overloaded-virtual -Wno-sign-compare -fno-lto -O2 -g -DNDEBUG   -std=c++14 -o CMakeFiles/mir-public-test.dir/display_config_matchers.cpp.o -c /spread/mir/tests/mir_test/display_config_matchers.cpp
In file included from /spread/mir/tests/mir_test/display_config_matchers.cpp:19:
/spread/mir/include/test/mir/test/display_config_matchers.h:25:10: fatal error: gmock/gmock.h: No such file or directory
   25 | #include <gmock/gmock.h>
      |          ^~~~~~~~~~~~~~~
```
https://api.travis-ci.com/v3/job/280923810/log.txt

**Comment by AlanGriffiths** [comment]
bors r=wmww

**Comment by RAOF** [comment]
bors r=wmww,RAOF

**Comment by AlanGriffiths** [comment]
This is weird.

Travis "passed" the bors job: https://travis-ci.com/MirServer/mir/builds/146540629
Bors cancelled the job: https://app.bors.tech/batches/44731

@Saviq can you spot what happened?

**Comment by AlanGriffiths** [comment]
> can you spot what happened?

Oh! I guess this is it:
> {{:badmatch,
>   {:error, :push, 422,
>    "{\"message\":\"Required status check \\\"Travis CI - Pull Request\\\" is failing.\",\"documentation_url\":\"https://help.github.com/articles/about-protected-branches\"}"}},

https://app.bors.tech/repositories/1191/log

Has bors lost push access to master?

**Comment by AlanGriffiths** [comment]
OK, bors succeeded in landing #1226, so problems were probably transient.

bors r=wmww,RAOF

**Comment by AlanGriffiths** [comment]
bors r=wmww,RAOF

**Comment by AlanGriffiths** [comment]
Nope, still not working! Same happened again.

https://app.bors.tech/repositories/1191/log#batch-44754

Using my super-powers to merge it directly.

**Pull request merged**
