### PR TITLE
Reimplement idle_inhibit_unstable_v1

### LINKED ISSUE #2836: Enabling zwp_idle_inhibit_manager_v1 causes Mir to crash with some applications
(The latest releases of) [Taisei](https://github.com/taisei-project/taisei) & [Teeworlds](https://github.com/teeworlds/teeworlds) as well as some other closed-source applications that can spawn Wayland windows via SDL2 cause the following error in the logs when their window is closed.
```
[2023-02-13 15:05:53.822899] < -warning- > frontend:Wayland: Exception processing WlSurface::~WlSurface() request: /build/source/src/server/frontend_wayland/window_wl_surface_role.cpp(416): Throw in function surface_destroyed
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: wl_surface@28 destroyed before associated role

error in client communication (pid 204373)
```

If
- there is no current X11/Wayland session (i.e. runlevel 3),
- a new Mir session is started (on a tty or via ssh) with the `zwp_idle_inhibit_manager_v1` Wayland extension enabled, and
- within this session, one such application causes this error

then this instead crashes the entire Mir session. I've verified this behaviour on NixOS unstable (miral-app & Miriway) and Ubuntu 22.10 (ubuntu-frame snap & source-built miral-app), Mir 2.12.0 and current master (a35b39748317414f2ccba627cedb8d8da33d8618).
```
!!! Fatal signal received. Attempting cleanup, but deadlock may occur
Mir fatal error: Unsupported attempt to continue after a fatal signal: SIGSEGV
!!! Fatal signal received. Attempting cleanup, but deadlock may occur
Mir fatal error: Unsupported attempt to continue after a fatal signal: SIGABRT
```
Here is the gdb backtrace with debug information.
```
Thread 16 "Mir/Wayland" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fd37ee840 (LWP 435461)]
0x0000007ff6bdd5a0 in wl_closure_invoke (closure=closure@entry=0x7fc0052830, flags=flags@entry=2, target=<optimized out>, opcode=0, data=<optimized out>, data@entry=0x7fc0000fb0) at ../src/connection.c:1021
1021	../src/connection.c: No such file or directory.
(gdb) bt
#0  0x0000007ff6bdd5a0 in wl_closure_invoke (closure=closure@entry=0x7fc0052830, flags=flags@entry=2, target=<optimized out>, opcode=0, data=<optimized out>, data@entry=0x7fc0000fb0) at ../src/connection.c:1021
#1  0x0000007ff6bd97d0 in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x7fc0000fb0) at ../src/wayland-server.c:437
#2  0x0000007ff6bdb678 in wl_event_loop_dispatch (loop=0xe2e750, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
#3  0x0000007ff6bd9a44 in wl_display_run (display=display@entry=0xe2e660) at ../src/wayland-server.c:1431
#4  0x0000007ff7736450 in <lambda(wl_display*)>::operator() (__closure=<optimized out>, d=0xe2e660) at /build/source/src/server/frontend_wayland/wayland_connector.cpp:394
#5  std::__invoke_impl<void, mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> (__f=...) at /nix/store/4mhhaggjp57h7sr8diiiskbb86nh4ppy-gcc-9.5.0/include/c++/9.5.0/bits/invoke.h:60
#6  std::__invoke<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> (__fn=...) at /nix/store/4mhhaggjp57h7sr8diiiskbb86nh4ppy-gcc-9.5.0/include/c++/9.5.0/bits/invoke.h:95
#7  std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> >::_M_invoke<0, 1> (this=<optimized out>) at /nix/store/4mhhaggjp57h7sr8diiiskbb86nh4ppy-gcc-9.5.0/include/c++/9.5.0/thread:244
#8  std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> >::operator() (this=<optimized out>) at /nix/store/4mhhaggjp57h7sr8diiiskbb86nh4ppy-gcc-9.5.0/include/c++/9.5.0/thread:251
#9  std::thread::_State_impl<std::thread::_Invoker<std::tuple<mir::frontend::WaylandConnector::start()::<lambda(wl_display*)>, wl_display*> > >::_M_run(void) (this=<optimized out>) at /nix/store/4mhhaggjp57h7sr8diiiskbb86nh4ppy-gcc-9.5.0/include/c++/9.5.0/thread:195
#10 0x0000007ff7cb0984 in execute_native_thread_routine () from /nix/store/f01gwicpyspl4qf7h8cwvgzg5x4s2a0g-gcc-9.5.0-lib/lib/libstdc++.so.6
#11 0x0000007ff799bdb4 in start_thread () from /nix/store/yy19vx24hhn7snsv7pffnqh1mknfp1sq-glibc-2.35-224/lib/libc.so.6
#12 0x0000007ff7a0289c in thread_start () from /nix/store/yy19vx24hhn7snsv7pffnqh1mknfp1sq-glibc-2.35-224/lib/libc.so.6
```

---

https://wayland.app/protocols/idle-inhibit-unstable-v1 indicates that Sway also supports this extension, and these applications don't crash there.
image

Unsure if relevant to this, but the applications also print the following on startup.
```
[2023-02-12 23:02:27.012698] < -warning- > mirserver: WlRegion::subtract not implemented. ignoring.
```

### LINKED ISSUE #2838: [Wayland] idle_inhibit_unstable_v1 is badly broken
1. `zwp_idle_inhibit_manager_v1.create_inhibitor` does not create a `zwp_idle_inhibitor_v1` unless the surface has input focus (it should always create an inhibitor)
2. `zwp_idle_inhibitor_v1` does not release and (re)acquire the wake lock according to the surface's "visual relevance"

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes #2838
Fixes #2836

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
We can likely do better than this with the visibility detection, but this covers simple usecases without being broken.

**Comment by AlanGriffiths** [comment]
The problems this fixes can be seen with, for example, neverputt on 23.04

**Review by wmww — CHANGES_REQUESTED** [review]
I feel like this adds more complexity than needed, especially to the already long and complex wl_surface implementation. Ideally we could either merge some of this new functionality into wayland_surface_observer.cpp or keep it contained in idle_inhibit_v1.cpp.

**Comment by AlanGriffiths** [comment]
Superseded by #2842

**Pull request closed without merging**
