### PR TITLE
Remember to restore Debian/sid and Alpine/edge builds

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
umockdev 0.17.6 is in jammy, let's see...

**Comment by Saviq** [comment]
> umockdev 0.17.6 is in jammy, let's see...

Jammy is b0rked due to the yaml-cpp/libstdc++ issue. But rawhide went fine, so it seems to have worked.

**Comment by AlanGriffiths** [comment]
> > umockdev 0.17.6 is in jammy, let's see...
> 
> Jammy is b0rked due to the yaml-cpp/libstdc++ issue. But rawhide went fine, so it seems to have worked.

Don't count on it yet: we're still waiting on Alpine/edge

**Review by Saviq — APPROVED** [review]
Yup.

bors merge

**Pull request merged**
