### PR TITLE
Release 2.6.0

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by Saviq** [comment]
Saw a couple failures:
https://launchpadlibrarian.net/572054872/buildlog_ubuntu-jammy-amd64.mir_2.6.0~rc1-gdac6816ab2-0ubuntu22.04_BUILDING.txt.gz
https://launchpadlibrarian.net/572053819/buildlog_ubuntu-focal-arm64.mir_2.6.0~rc1-gdac6816ab2-0ubuntu20.04_BUILDING.txt.gz

```plain
	 30 - wlcs.ClippedLargerRegion/RegionSurfaceInputCombinations.* (Timeout)
	132 - miral-test.WaylandExtensions.* (Timeout)
```

**Comment by AlanGriffiths** [comment]
> Saw a couple failures:

Ack. Not obvious what that might be, so am retrying those (PPA) builds.

**Comment by AlanGriffiths** [comment]
# rc1

## Debs

Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

### Installed from from ppa:mir-team/rc

Platform|21.10|21.04|20.04LTS
--|--|--|--
gbm-kms|||
gbm-x11|||
eglstream-kms|||
dispmanx|||

Console|21.10|21.04|20.04LTS
--|--|--|--
minimal|||
linux-VT|||
logind|||

WM|21.10|21.04|20.04LTS
--|--|--|--
floating|||
tiling|||
kiosk|||

**Comment by wmww** [comment]
I found a couple issues: #2241, #2240. #2241 is probably new (at least in the sense that we've touched the code and it was broken in a different way last time). Perhaps worth fixing.

**Comment by RAOF** [comment]
We *might* want to add #2243 here, to cut down on the special casing needed for Mali.

**Comment by AlanGriffiths** [comment]
> I never remember which console services are which or how to test them.

|console provider|use|
|--|--|
|logind|Desktop login session (either from greeter or from VT\<n\>)|
|minimal|A stub used by Mir-on-X/Mir-on-Wayland|
|VT|On Core (needs root)|

**Comment by AlanGriffiths** [comment]
# rc3

## Debs

Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

### Installed from from ppa:mir-team/rc

Platform|21.10|21.04|20.04LTS
--|--|--|--
gbm-kms|||
gbm-x11|||
eglstream-kms|||
dispmanx|||

Console|21.10|21.04|20.04LTS
--|--|--|--
minimal|||
linux-VT|||
logind|||

WM|21.10|21.04|20.04LTS
--|--|--|--
floating|||
tiling|||
kiosk|||

**Comment by wmww** [comment]
#2247 doesn't need to block, but we should confirm it's pre-existing.

**Comment by RAOF** [comment]
I see #2248 on 22.04 & 20.04, but everything seems to actually work, so it's probably cosmetic.

**Comment by AlanGriffiths** [comment]
bors merge

**Comment by AlanGriffiths** [comment]
bors retry

**Pull request merged**
