### PR TITLE
eglstream-kms: Actually save CRTC on startup

### PR DESCRIPTION
**Pull request by RAOF**
Since we try to restore it on shutdown we should probably save it on startup!

Fixes: #1466

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
@Saviq as you raised the original bug, are you set up to try this?

**Comment by RAOF** [comment]
FWIW I tested this on *my* nvidia system and it no longer complains. But my system is somewhat atypical, in that the nvidia card doesn't normally have a framebuffer *at all*.

**Comment by AlanGriffiths** [comment]
bors merge

**Comment by Saviq** [comment]
> @Saviq as you raised the original bug, are you set up to try this?

Also FWIW, I only saw this in the CI lab, don't have Nvidia here.

Will run it there again to see if it's gone.

**Pull request merged**
