### PR TITLE
[travis] disable fedora builds for now and use IPv4 in spread

### PR DESCRIPTION
**Pull request by Saviq**
glm-devel didn't get an update along with gcc:

https://bugzilla.redhat.com/show_bug.cgi?id=1542941

### CODE REVIEW

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Comment by Saviq** [comment]
bors try

**Comment by Conan-Kudo** [comment]
@AlanGriffiths @Saviq Update is in testing: https://bodhi.fedoraproject.org/updates/FEDORA-2018-c7f888e819

**Pull request merged**
