### PR TITLE
spread: optimize in sbuild, too

### PR DESCRIPTION
**Pull request by Saviq**
Otherwise symbols may not be as we expect them.

### CODE REVIEW

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
You should need to revert 555c3a06eaf613e4d18e81c0b23c6854509c9975 too!

**Review by AlanGriffiths — APPROVED** [review]
Not sure if this is now stale?

bors try

**Comment by Saviq** [comment]
Not stale, but slow. And requires a fix in spread.

**Comment by Saviq** [comment]
This got folded into #2156

**Pull request closed without merging**
