### PR TITLE
Deprecate mir_keyboard_event_key_code()

### PR DESCRIPTION
**Pull request by wmww**
Stacked on top of #2074

### CODE REVIEW

**Comment by wmww** [comment]
Marked as draft until prerequisite PR lands and this gets moved to it's final form.

**Review by AlanGriffiths — APPROVED** [review]
LGTM

bors r+

**Comment by AlanGriffiths** [comment]
> cannot provision google:ubuntu-20.04-64

Looks like things are busy. Let's contribute to the problem:

bors retry

**Comment by wmww** [comment]
bors r=AlanGriffiths

**Pull request merged**
