### PR TITLE
AnonymousShmFile: Use memfd where available.

### PR DESCRIPTION
**Pull request by RAOF**

### CODE REVIEW

**Comment by RAOF** [comment]
I felt like doing something quick and simple.

@gerboland - this might plausibly fix #120 ?

**Comment by AlanGriffiths** [comment]
@mariogrip does this impact UBports in any negative way?

From what you've told me your oldest kernels are 3.4 (which predates 3.17 when memfd was added). Although, hopefully, that might change for 16.04 based versions? So, is that still true for devices on which you'd deploy future releases of Mir?

It looks as though this ought to work on older kernels, provided you can successfully compile it?

**Comment by gerboland** [comment]
Alan has raised my only concern.

**Comment by gerboland** [comment]
I talked with @mariogrip  about this, he has to support kernels as old as 3.4. Could we keep the old shm file approach as a fall-back?

**Comment by AlanGriffiths** [comment]
> @gerboland "I talked with @mariogrip about this, he has to support kernels as old as 3.4. Could we keep the old shm file approach as a fall-back?"

Am I misreading the code. I thought that was what we had?

**Comment by gerboland** [comment]
No, my bad, I skimmed too fast.

**Pull request merged**
