### PR TITLE
platform/Display: Remove register_pause_resume_handlers

### PR DESCRIPTION
**Pull request by RAOF**
The `ConsoleServices` is a singleton, and which the `DisplayPlatform` only needs
to interact with during construction (in order to `acquire_device`).

There's no need to force the `Display` to keep a reference to the `ConsoleServices`
purely so that it can forward `register_pause_resume_handlers` to it.

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
WFM but this does need a mirserver soname bump as ServerConfiguration vtab has changed

bors merge

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
This one needs fixing:

```plain
[ FAILED ] DisplayServerMainLoopEvents.postpones_configuration_when_paused (87 ms)
```

**Comment by RAOF** [comment]
I still can't see why the initial code changes resulted in the arm64 tests becoming flaky, but this has now looped 10,000 times locally without a failure, so is probably now not significantly flaky.

**Review by AlanGriffiths — APPROVED** [review]
Re the tests changes: I now don't see why the tests ever worked as the functor runs "after constructing the server, but before invoking DisplayServer::run()", but the tests rely on the server running to process events.

We could probably add better support for such tests, but this works.

bors merge

**Pull request merged**
