### PR TITLE
[wayland] don't send/apply input events after rebuilding state

### PR DESCRIPTION
**Pull request by AlanGriffiths**
[wayland] don't send/apply input events after rebuilding state. (Fixes: #1607)

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Note: to unblock 2.0 I've added this in rc5.

I know this doesn't solve all our focus issues (e.g. #1625) but it works better for me than the status quo.

**Comment by wmww** [comment]
So sorry. I meant to review this right away yesterday, but I lost the tab somehow and forgot about it.

**Comment by wmww** [comment]
I don't understand *why* any of this is a good idea. Why is Mir sending events to the wrong surface? Why is the correct response to send the currently focused surface (which Mir didn't request), but still change the focus? Why is modifier state only updated if the requested surface is currently focused?

**Comment by AlanGriffiths** [comment]
> I don't understand why any of this is a good idea.

Because it improves the behaviour?

> Why is Mir sending events to the wrong surface? 

I've yet to figure that out. I know we have a focus tracking issue, and all this was, and is, a workaround.

> Why is the correct response to send the currently focused surface (which Mir didn't request), but still change the focus? 

If we don't then (empirically) we end up with the client autorepeating keys.

> Why is modifier state only updated if the requested surface is currently focused?

The modifier state tracks the state of the hardware and needs to be updated with input events. Unless it is resync'd with the hardware.

If we call `focussed()` then we read the *current* hardware status which already reflects current event. The previous workaround got this wrong and processed, for example, a key down for an already pressed key. Multiple key down events is "legal" according to XKB, but the accounting then requires multiple key releases to unpress the key (which never happens and leads to the "locked" keys we sometimes saw).

**Pull request merged**
