### PR TITLE
Revert the changes that cause  #2313

### LINKED ISSUE #2313: Double free on exit
```plain
$ mir_demo_server
```
And close with [X] in the corner, or `Ctrl-Alt-BkSp`...
```
...
double free or corruption (fasttop)
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes  #2313

### CODE REVIEW

**Review by wmww — APPROVED** [review]
Approving so Alan can merge if a better fix doesn't come along in time
bors delegate

**Comment by wmww** [comment]
bors delegate+

**Comment by RAOF** [comment]
#2315 also fixes this

**Comment by AlanGriffiths** [comment]
> #2315 also fixes this

We'll go with that

**Pull request closed without merging**
