### PR TITLE
platforms: Enable linux-dmabuf on X11 and Wayland platforms

### PR DESCRIPTION
**Pull request by RAOF**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
As well as the traditional rpi problems, this appears to include #1781 which is marked "no-merge"

**Comment by AlanGriffiths** [comment]
Now just the traditional rpi problems. ;)

**Comment by RAOF** [comment]
What's missing here? As far as I'm aware, this is good to land?

**Comment by AlanGriffiths** [comment]
Sorry, got distracted after pushing conflict resolution.

bors r+

**Review by AlanGriffiths — APPROVED** [review]

**Pull request merged**
