### PR TITLE
[bors] reduce timeout to 30 minutes and fix bors

### PR DESCRIPTION
**Pull request by Saviq**
Now that Travis isn't throttling us, this should be enough.

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
It probably should.

bors r+

**Comment by Saviq** [comment]
I think bors got confused:

bors r-

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Comment by Saviq** [comment]
D'uh.

bors r=AlanGriffiths,Saviq

**Comment by Saviq** [comment]
D'uh².

bors r=AlanGriffiths,Saviq

**Pull request merged**
