### PR TITLE
Better grabbing popups

### LINKED ISSUE #2604: Popups dismissed by Mir when parent clicked
#2330 Fixed several previous and reoccurring issues (see #2324 for an upsettingly in-depth analysis), however it appears it's still not doing quite the same thing as other compositors.

The current Mir code roughly gives grabbing popups pointer focus but not keyboard focus. Therefore, when the user clicks on the parent window outside of a popup the click is consumed and the popup is dismissed. In wlroots and weston in this situation the parent gets the click events, and the popup is not automatically dismissed by the compositor.

To see a difference in behavior:
- Open Kate
- Open a menu and hover over an item with a submenu (the submenu will appear)
- Click
- On Mir, the submenu disappears
- On wlroots/weston the submenu does not disappear

In fixing this we must be mindful to not reintroduce #1941 or #2241. Those should be tested in WLCS, but I'll verify that.

### PR DESCRIPTION
**Pull request by wmww**
Fixes #2604 and #2585 by decoupling focus state from dismissing popup grabs. Draft because it doesn't have tests yet, but it should work.

### CODE REVIEW

**Comment by Saviq** [comment]
```
[ RUN ] AbstractShell.removing_focus_from_menu_closes_it
/spread/mir/tests/unit-tests/scene/test_abstract_shell.cpp:972: Failure
Actual function call count doesn't match EXPECT_CALL(mock_surface1, request_client_surface_close())...
Expected: to be called once
Actual: never called - unsatisfied and active
[ FAILED ] AbstractShell.removing_focus_from_menu_closes_it (0 ms)
```

**Review by Saviq — COMMENTED** [review]
Empirically, this fixes #2585.

**Review by AlanGriffiths — APPROVED** [review]
> Draft because it doesn't have tests yet, but it should work.

Looks sensible, appears to work, and even has tests!

Still marked "draft" though

bors delegate

**Comment by wmww** [comment]
> Still marked "draft" though

Huh? On my side it says I marked it ready for review 4 days ago.

bors r+

**Comment by AlanGriffiths** [comment]
> Huh? On my side it says I marked it ready for review 4 days ago.

I see that too. Now. I wonder what I was looking at?

**Pull request merged**
