### PR TITLE
Support zwp_text_input_manager_v2

### LINKED ISSUE #2260: Support text-input protocol for Qt clients
According to https://github.com/qt/qtwayland/tree/dev/src/3rdparty/protocol, Qt has `text-input-unstable-v2.xml` and `text-input-unstable-v4-wip.xml`. I don't know if the latter is implemented, but various sources indicate the former is. This tells me they're going to skip v3 entirely (the protocol Mir supports).

Our text input implementation was built with the idea that we could support multiple protocols, and it seems that is what we'll need to do if we want Qt to work.

### PR DESCRIPTION
**Pull request by wmww**
This older text input protocol is the only one currently supported by Qt. I can't find any plans for them to upgrade to v3, so I thought it would be a good idea to support it.

It's a quick and dirty implementation based on our v3 support. It probably wont work perfectly in all cases (in particularly there might be problems with more complex languages that use pre-edit strings), but this does allow typing on Squeekboard in English in Kate.

As with the v3 version there are no security concerns with this side of the transaction, so this protocol is enabled by default.

Fixes #2260.

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
Looks uncontroversial, but I can't verify on 20.04. OSK does not appear, although Qt does bind to the global:

```plain
$ WAYLAND_DEBUG=client kate 2>&1 | grep zwp_text_input
[3995372.161] wl_registry@2.global(14, "zwp_text_input_manager_v2", 1)
[3995372.168]  -> wl_registry@2.bind(14, "zwp_text_input_manager_v2", 1, new id [unknown]@14)
[3995372.175]  -> zwp_text_input_manager_v2@14.get_text_input(new id zwp_text_input_v2@15, wl_seat@6)
[3995372.180] wl_registry@2.global(15, "zwp_text_input_manager_v3", 1)
[3996786.520] wl_registry@13.global(14, "zwp_text_input_manager_v2", 1)
[3996786.545] wl_registry@13.global(15, "zwp_text_input_manager_v3", 1)
[3997143.377] zwp_text_input_v2@15.enter(329, wl_surface@8)
[4043742.011] zwp_text_input_v2@15.leave(343, nil)
```

bors delegate

**Comment by AlanGriffiths** [comment]
> Looks uncontroversial, but I can't verify on 20.04. OSK does not appear

Also on 21.10

**Comment by AlanGriffiths** [comment]
Here's the WAYLAND_DEBUG log from kate (deb install) on 21.10: [kate.log](https://github.com/MirServer/mir/files/7848799/kate.log)

**Comment by AlanGriffiths** [comment]
> Here's the WAYLAND_DEBUG log from kate (deb install) on 21.10: [kate.log](https://github.com/MirServer/mir/files/7848799/kate.log)

Hmm, that doesn't bind `zwp_text_input_manager_v2`

**Comment by AlanGriffiths** [comment]
Here's a log from 20.04 (that does bind `zwp_text_input_manager_v2`): [kate.log](https://github.com/MirServer/mir/files/7848892/kate.log)

**Comment by wmww** [comment]
Keyboard doesn't show up for Kate on Arch (Qt: 5.15.2+kde+r38-1). Works for gedit.

**Comment by wmww** [comment]
Setting `QT_IM_MODULE` to `qtvirtualkeyboard` (or anything) causes Qt to not bind to the text input. Since in both of your logs do bind to something I don't think that's relevant, but worth noting.

**Comment by wmww** [comment]
I'm going to take a break and come back to this later

**Comment by AlanGriffiths** [comment]
I don't know (haven't investigated) where it originates, but...
```
$ export | grep QT
declare -x QT_ACCESSIBILITY="1"
declare -x QT_IM_MODULE="ibus"
```

So All I needed was:

```
$ env -u QT_IM_MODULE QT_QPA_PLATFORM=wayland kate README.md
```

bors r+

**Pull request merged**
