### PR TITLE
cmake: Fix running WLCS tests under ptest

### PR DESCRIPTION
**Pull request by RAOF**
This fixes running the WLCS tests under ptest, rather than silently(!) failing to run them and reporting success.

It also implements the ptest support for checking that the XFAIL tests actually fail.

### CODE REVIEW

**Comment by RAOF** [comment]
See also #1939, which is orphaned since its dependent branch got merged.

**Comment by RAOF** [comment]
Once WLCS has built in the mir-team/dev PPA this should be landable.

**Comment by RAOF** [comment]
bors try

**Comment by RAOF** [comment]
Bah! Why does `BadBufferTest` fail in the CI environment?!

**Comment by RAOF** [comment]
So, two problems:
 * something is strange in the non-sbuild CI environment around shared memory (maybe the place we allocate shm files in is a real fs, rather than a tmpfs there?)
 * The BadBuffer test which tests that a SIGSEGV is caught fails on sbuild:arm64 - this would seem to be a qemu-user-static bug, as the test passes on a real arm64 RPi 4.

We solve this by adding a configure option to mark that test as XFAIL, and setting it in the non-sbuild Ubuntu tasks and on the arm64 sbuild task.

**Review by AlanGriffiths — APPROVED** [review]
bors r+

**Comment by RAOF** [comment]
Damnit! We've broken some tests between my last push and bors' attempted merge :(

**Comment by RAOF** [comment]
#1988 is the PR that broke the tests.

**Comment by AlanGriffiths** [comment]
Now #1993 has landed, this should be unblocked

bors r+

**Pull request merged**
