### PR TITLE
Fix process snap version check

### PR DESCRIPTION
**Pull request by AlanGriffiths**
We want to update "edge" channels when master has a different version. E.g.

     >>> "1.6.0+dev73".startswith("1.6.0")
     True
     >>> "1.6.0+dev73" =="1.6.0"
     False

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
And, on the good side. `mir-kiosk --edge` is, at last, syncing with master.

**Comment by AlanGriffiths** [comment]
> So I'd say this is good as-is, can you please show what were you expecting that didn't happen?

Since the release of 1.6.0 the edge channel had remained on 1.6.0 and not picked up subsequent revs as expected.

**Comment by Saviq** [comment]
With the current approach, notice it will trigger `+dev118` builds even though it should not:
```
./tools/process_snaps.py 2>&1 | grep -i -e version -e triggering
Parsed upstream version: 1.6.0+dev118-gb24bd36da5
Got store versions: {'i386': '1.6.0+dev118-snap93', 'amd64': '1.6.0+dev118-snap93', 'armhf': '1.6.0+dev118-snap93', 'arm64': '1.6.0+dev118-snap93'}
Triggering mir-kiosk-edge…
Parsed upstream version: 1.6.0
Got store versions: {'i386': '1.6.0-snap93', 'amd64': '1.6.0-snap93', 'armhf': '1.6.0-snap93', 'arm64': '1.6.0-snap93'}
Skipping mir-kiosk: store versions are current
Got store versions: {'i386': '0.3.0', 'amd64': '0.3.0', 'armhf': '0.3.0', 'arm64': '0.3.0'}
Skipping mir-kiosk-apps: store versions are current
Got store versions: {'i386': '78.0.3904.108', 'amd64': '78.0.3904.108', 'armhf': '78.0.3904.108', 'arm64': '78.0.3904.108'}
Skipping chromium-mir-kiosk: store versions are current
Parsed upstream version: 1.6.0+dev118-gb24bd36da5
Got store versions: {'i386': '1.6.0+dev118-snap56', 'amd64': '1.6.0+dev118-snap56', 'armhf': '1.6.0+dev118-snap56', 'arm64': '1.6.0+dev118-snap56'}
Triggering mir-test-tools-edge…
Parsed upstream version: 1.6.0
Got store versions: {'i386': '1.6.0-snap56', 'amd64': '1.6.0-snap56', 'armhf': '1.6.0-snap56', 'arm64': '1.6.0-snap56'}
Skipping mir-test-tools: store versions are current
Parsed upstream version: 1.6.0+dev118-gb24bd36da5
Got store versions: {'i386': '90-mir1.6.0+dev118-snap68', 'amd64': '90-mir1.6.0+dev118-snap68', 'armhf': '90-mir1.6.0+dev118-snap68', 'arm64': '90-mir1.6.0+dev118-snap68'}
Triggering egmde-mir-master…
Parsed upstream version: 1.6.0
Got store versions: {'i386': '89-mir1.6.0-snap68', 'amd64': '89-mir1.6.0-snap68', 'armhf': '89-mir1.6.0-snap68', 'ppc64el': '89-mir1.6.0-snap68', 'arm64': '89-mir1.6.0-snap68'}
Skipping egmde: store versions are current
Parsed upstream version: 1.6.0+dev118-gb24bd36da5
Got store versions: {'i386': '90-mir1.6.0+dev118-snap33', 'amd64': '90-mir1.6.0+dev118-snap33', 'armhf': '90-mir1.6.0+dev118-snap33', 'arm64': '90-mir1.6.0+dev118-snap33'}
Triggering egmde-confined-desktop…
```

**Comment by Saviq** [comment]
With this commit, however, everything is correctly skipped:
```
Parsed upstream version: 1.6.0+dev118
Got store versions: {'i386': '1.6.0+dev118-snap93', 'amd64': '1.6.0+dev118-snap93', 'armhf': '1.6.0+dev118-snap93', 'arm64': '1.6.0+dev118-snap93'}
Skipping mir-kiosk: store versions are current
Parsed upstream version: 1.6.0
Got store versions: {'i386': '1.6.0-snap93', 'amd64': '1.6.0-snap93', 'armhf': '1.6.0-snap93', 'arm64': '1.6.0-snap93'}
Skipping mir-kiosk: store versions are current
Got store versions: {'i386': '0.3.0', 'amd64': '0.3.0', 'armhf': '0.3.0', 'arm64': '0.3.0'}
Skipping mir-kiosk-apps: store versions are current
Got store versions: {'i386': '78.0.3904.108', 'amd64': '78.0.3904.108', 'armhf': '78.0.3904.108', 'arm64': '78.0.3904.108'}
Skipping chromium-mir-kiosk: store versions are current
Parsed upstream version: 1.6.0+dev118
Got store versions: {'i386': '1.6.0+dev118-snap56', 'amd64': '1.6.0+dev118-snap56', 'armhf': '1.6.0+dev118-snap56', 'arm64': '1.6.0+dev118-snap56'}
Skipping mir-test-tools: store versions are current
Parsed upstream version: 1.6.0
Got store versions: {'i386': '1.6.0-snap56', 'amd64': '1.6.0-snap56', 'armhf': '1.6.0-snap56', 'arm64': '1.6.0-snap56'}
Skipping mir-test-tools: store versions are current
Parsed upstream version: 1.6.0+dev118
Got store versions: {'i386': '90-mir1.6.0+dev118-snap68', 'amd64': '90-mir1.6.0+dev118-snap68', 'armhf': '90-mir1.6.0+dev118-snap68', 'arm64': '90-mir1.6.0+dev118-snap68'}
Skipping egmde: store versions are current
Parsed upstream version: 1.6.0
Got store versions: {'i386': '89-mir1.6.0-snap68', 'amd64': '89-mir1.6.0-snap68', 'armhf': '89-mir1.6.0-snap68', 'ppc64el': '89-mir1.6.0-snap68', 'arm64': '89-mir1.6.0-snap68'}
Skipping egmde: store versions are current
Parsed upstream version: 1.6.0+dev118
Got store versions: {'i386': '90-mir1.6.0+dev118-snap33', 'amd64': '90-mir1.6.0+dev118-snap33', 'armhf': '90-mir1.6.0+dev118-snap33', 'arm64': '90-mir1.6.0+dev118-snap33'}
Skipping egmde-confined-desktop: store versions are current
```

**Comment by Saviq** [comment]
bors delegate=alan_g

**Comment by AlanGriffiths** [comment]
Works for me

bors r=Saviq

**Pull request merged**
