### PR TITLE
server: Allow mirclient connector construction to fail.

### PR DESCRIPTION
**Pull request by RAOF**
We've deprecated mirclient. There are a bunch of platform interfaces which are needed
*only* by the mirclient interfaces, so allow platforms to throw instead of providing
a stub implementation (that then won't work anyway) of these interfaces.

Platforms which currently support mirclient are unaffected; only platforms which don't
support mirclient anyway will change behaviour.

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
I have concerns about using exceptions for "normal" control flow, but I guess it isn't trivial to deal with `RenderingPlatform::make_ipc_operations()` otherwise.

I think what I'd prefer is for `the_connector()` to default to a stub implementation (with a new configuration option to enable it). Then there would be no need to handle the exception (here at least) as enabling the option for an unsupported platform is a user/configuration error.

**Comment by RAOF** [comment]
That would be an option. I did it this way because it's minimally disruptive for existing users - anything that currently works continues to work, and systems which used to cause mirclients to fail on connect instead don't expose a mirclient socket.

I guess we *do* plan to deprecate mirclient in the near-term future, so I guess it's not *so* disruptive for users who currently use mirclient-clients to add an extra command-line option...

**Comment by AlanGriffiths** [comment]
> I guess we _do_ plan to deprecate mirclient in the near-term future, so I guess it's not _so_ disruptive for users who currently use mirclient-clients to add an extra command-line option...

I guess how we do that is something to discuss that goes beyond the scope of this PR.

There's a range of options: from a `miral::MirClientSupport` that allows the shell to "opt in" to a configuration option to, not having a visible configuration option and just testing for an environment variable "MIR_ENABLE_MIRCLIENT_LEGACY".

Something to discuss at tomorrow's sync?

**Comment by RAOF** [comment]
Sure!

**Pull request closed without merging**
