### PR TITLE
Release 2.14.1

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
> ##
> 
> > Merging [#2980](https://app.codecov.io/gh/MirServer/mir/pull/2980?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=MirServer) ([27de7b2](https://github.com/MirServer/mir/commit/27de7b2778669df36fd9b66acc235909a5bfd465)) into [main](https://app.codecov.io/gh/MirServer/mir/commit/fbdeb72e1091e892c4f4b6cf21e5a027690024c8?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=MirServer) ([fbdeb72](https://github.com/MirServer/mir/commit/fbdeb72e1091e892c4f4b6cf21e5a027690024c8)) will **decrease** coverage by `0.01%`.

Wow! we're counting the changelog as code?

**Comment by AlanGriffiths** [comment]
Oops! The PPA builds are failing because some recent wlcs changes have not been released.

**Comment by AlanGriffiths** [comment]
# ~rc1

[TestPlan](https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir)

Platform|20.04LTS|22.04LTS|23.04|23.10
--|--|--|--|--
gbm-kms|||@AlanGriffiths|
gbm-x11|||@AlanGriffiths|
gbm-wayland||||
eglstream-kms||| 

Platform|20.04LTS|22.04LTS|23.04|23.10
--|--|--|--|--
minimal|||@AlanGriffiths|
linux-VT|||@AlanGriffiths|
logind|||@AlanGriffiths|

Platform|20.04LTS|22.04LTS|23.04|23.10
--|--|--|--|--
floating|||@AlanGriffiths|
tiling|||@AlanGriffiths|
kiosk|||@AlanGriffiths|

**Comment by AlanGriffiths** [comment]
Note to testers:

This is available from ppa:mir-team/rc:

    sudo apt-add-repository ppa:mir-team/rc
    sudo apt install mir-demos mir-test-tools mir-graphics-drivers-desktop [mir-graphics-drivers-nvidia]

Our various Mir-based snaps have this on the `beta`/`22/beta` channels:

Snap|channel
--|--
ubuntu-frame|`22/beta`
mir-test-tools|`22/beta`
miriway|`beta`

**Review by Saviq — CHANGES_REQUESTED** [review]
Need to bump CMake version… will need to go 2.14.1 now for the PPA to be happy.

**Review by Saviq — APPROVED** [review]
Good to tag!

**Pull request merged**
