### PR TITLE
Move to c++20

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
bors try

**Review by wmww — APPROVED** [review]
LGTM
bors r+

**Comment by Saviq** [comment]
Looks like [20.04 no likey](https://github.com/MirServer/mir/runs/4792858993?check_suite_focus=true#step:5:3891):

```plain
/spread/mir/src/include/server/mir/scene/null_session_listener.h:32:13: error: exception specification is not available until end of class definition
    virtual ~NullSessionListener() noexcept(true) = default;
            ^
1 error generated.
make[3]: *** [src/server/CMakeFiles/mirserverobjects.dir/build.make:118: src/server/CMakeFiles/mirserverobjects.dir/default_server_configuration.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

**Comment by AlanGriffiths** [comment]
bors r=wmww

**Pull request merged**
