### PR TITLE
LTTNG: Conditionally use void tracepoints.

### PR DESCRIPTION
**Pull request by RAOF**
As is always the case, the version of LTTNG in 16.04 doesn't support something sensible.
Conditionally use void tracepoints, as I find the warnings the dummy integer tracepoints
generate annoying.

### CODE REVIEW

**Comment by wmww** [comment]
@RAOF Bunch of errors that look like this on 18.04 clang:
```
/spread/mir/src/server/report/lttng/connector_report.cpp:31:1: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
CONNECTOR_TRACE_CALL(thread_start)
^
/spread/mir/src/server/report/lttng/connector_report.cpp:29:36: note: expanded from macro 'CONNECTOR_TRACE_CALL'
#define CONNECTOR_TRACE_CALL(name) MIR_LTTNG_VOID_TRACE_CALL(ConnectorReport, mir_server_connector, name)
                                   ^
/spread/mir/src/server/report/lttng/lttng_utils.h:29:9: note: expanded from macro 'MIR_LTTNG_VOID_TRACE_CALL'
        mir_tracepoint(comp, name);                  \
        ^
/spread/mir/src/include/common/mir/report/lttng/mir_tracepoint.h:22:32: note: expanded from macro 'mir_tracepoint'
#define mir_tracepoint(c, ...) tracepoint(c, __VA_ARGS__)
                               ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/include/x86_64-linux-gnu/lttng/tracepoint.h:40:27: note: expanded from macro 'LTTNG_STAP_PROBEV'
#define LTTNG_STAP_PROBEV STAP_PROBEV
                          ^
/usr/include/x86_64-linux-gnu/sys/sdt.h:339:32: note: expanded from macro 'STAP_PROBEV'
  _SDT_PROBE_N(provider, name, _SDT_NARG(0, ##__VA_ARGS__), ##__VA_ARGS__)
                               ^
/usr/include/x86_64-linux-gnu/sys/sdt.h:334:76: note: expanded from macro '_SDT_NARG'
#define _SDT_NARG(...) __SDT_NARG(__VA_ARGS__, 12,11,10,9,8,7,6,5,4,3,2,1,0)
                                                                           ^
/usr/include/x86_64-linux-gnu/sys/sdt.h:335:9: note: macro '__SDT_NARG' defined here
#define __SDT_NARG(_0,_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12, N, ...) N
        ^
```

**Comment by AlanGriffiths** [comment]
Yes, needs a bit more of this pixie dust:
```
check_cxx_compiler_flag(-Wno-gnu-zero-variadic-macro-arguments, ...
```

**Comment by wmww** [comment]
Looks good
bors r+

**Comment by RAOF** [comment]
bors r=wmww

What's up, bors?

**Pull request merged**
