### PR TITLE
musl-tests

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Update test expectations to work on musl libc

### CODE REVIEW

**Comment by z3ntu** [comment]
```
[ RUN      ] SharedLibrary.load_nonexistent_function_fails_with_useful_info                                                                                                                 
/home/luca/mir/tests/unit-tests/shared_library_test.cpp:103: Failure                                                                                                                        
Value of: info                                                                                                                                                                               
Expected: has substring "./bin/../lib/client-modules/dummy.so"                                                                                                                              
  Actual: "/home/luca/mir/src/common/sharedlibrary/shared_library.cpp(54): Throw in function void* mir::SharedLibrary::load_symbol(const char*) const\nDynamic exception type: boost::except$
on_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >\nstd::exception::what: Symbol not found: yo_dawg\n"
Name of library                                                                                                                                                                              
[  FAILED  ] SharedLibrary.load_nonexistent_function_fails_with_useful_info (0 ms)
```
This test just has to be disabled for musl I think

The rest of the test succeed until
```
[ RUN      ] ProbingClientPlatformFactory.ThrowsErrorWhenNoPlatformPluginProbesSuccessfully
Segmentation fault
```
After that I don't know what happens :)



Also, please **squash** the commits before/while merging.

**Comment by z3ntu** [comment]
Update: I've gone through and ignored all the tests that were segfaulting manually and the results are:
```
$ ./bin/mir_unit_tests --gtest_filter=-ProbingClientPlatformFactory.ThrowsErrorWhenNoPlatformPluginProbesSuccessfully:ProbingClientPlatformFactory.DoesNotLeakTheUsedDriverModuleOnShutdown:ProbingClientPlatformFactory.DoesNotLeakUnusedDriverModulesOnStartup:ProbingClientPlatformFactory.CreatesMesaPlatformOnMesaKMS:ProbingClientPlatformFactory.CreatesMesaPlatformOnMesaX11:ProbingClientPlatformFactory.IgnoresNonClientPlatformModules:MesaKMS/ClientPlatformTest.platform_name/0:MesaKMS/ClientPlatformTest.platform_creates/0:MesaKMS/ClientPlatformTest.platform_creates_native_window/0:MesaKMS/ClientPlatformTest.platform_creates_egl_native_display/0:MesaKMS/ClientPlatformTest.platform_probe_returns_success_when_matching/0:MesaKMS/ClientPlatformTest.platform_probe_returns_false_when_not_matching/0:MesaX11/ClientPlatformTest.platform_name/0:MesaX11/ClientPlatformTest.platform_creates/0:MesaX11/ClientPlatformTest.platform_creates_native_window/0:MesaX11/ClientPlatformTest.platform_creates_egl_native_display/0:MesaX11/ClientPlatformTest.platform_probe_returns_success_when_matching/0:MesaX11/ClientPlatformTest.platform_probe_returns_false_when_not_matching/0

[----------] Global test environment tear-down
[==========] 1511 tests from 180 test cases ran. (51139 ms total)
[  PASSED  ] 1510 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SharedLibrary.load_nonexistent_function_fails_with_useful_info

 1 FAILED TEST
  YOU HAVE 8 DISABLED TESTS
```

**Comment by AlanGriffiths** [comment]
> Update: I've gone through and ignored all the tests that were segfaulting manually and the results are:
> 
> ```
> $ ./bin/mir_unit_tests --gtest_filter=-ProbingClientPlatformFactory.ThrowsErrorWhenNoPlatformPluginProbesSuccessfully:ProbingClientPlatformFactory.DoesNotLeakTheUsedDriverModuleOnShutdown:ProbingClientPlatformFactory.DoesNotLeakUnusedDriverModulesOnStartup:ProbingClientPlatformFactory.CreatesMesaPlatformOnMesaKMS:ProbingClientPlatformFactory.CreatesMesaPlatformOnMesaX11:ProbingClientPlatformFactory.IgnoresNonClientPlatformModules:MesaKMS/ClientPlatformTest.platform_name/0:MesaKMS/ClientPlatformTest.platform_creates/0:MesaKMS/ClientPlatformTest.platform_creates_native_window/0:MesaKMS/ClientPlatformTest.platform_creates_egl_native_display/0:MesaKMS/ClientPlatformTest.platform_probe_returns_success_when_matching/0:MesaKMS/ClientPlatformTest.platform_probe_returns_false_when_not_matching/0:MesaX11/ClientPlatformTest.platform_name/0:MesaX11/ClientPlatformTest.platform_creates/0:MesaX11/ClientPlatformTest.platform_creates_native_window/0:MesaX11/ClientPlatformTest.platform_creates_egl_native_display/0:MesaX11/ClientPlatformTest.platform_probe_returns_success_when_matching/0:MesaX11/ClientPlatformTest.platform_probe_returns_false_when_not_matching/0
> 
> [----------] Global test environment tear-down
> [==========] 1511 tests from 180 test cases ran. (51139 ms total)
> [  PASSED  ] 1510 tests.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] SharedLibrary.load_nonexistent_function_fails_with_useful_info
> 
>  1 FAILED TEST
>   YOU HAVE 8 DISABLED TESTS
> ```

I don't have time at present to reproduce and look into the segfaults and add fixes to this PR. The latest commit should deal with `mir_unit_tests --gtest_filter=SharedLibrary*` - I think that's worth landing "as is"?

**Pull request merged**
