### PR TITLE
Add miral::TestWlcsDisplayServer to mirtest-dev

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Add miral::TestWlcsDisplayServer to mirtest-dev. (Fixes: #878)

This is the second and final part of what a downstream would need to test their own server.

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
If you want to test this out, then there's https://github.com/AlanGriffiths/egmde/tree/primary-selection

Build and install this branch, then build egmde and run:
```plain
`pkg-config --variable test_runner wlcs` <path to build>/egmde-wlcs.so
```

(wlcs doesn't have the primary-selection tests (yet), but it can test the stuff taken from Mir.)

**Comment by AlanGriffiths** [comment]
And now there's a wlcs "primary-selection" branch too (not yet proposed):
```plain
$ cmake-build-debug/wlcs ../egmde/cmake-build-debug/egmde-wlcs.so --gtest_filter=Prim*
Note: Google Test filter = Prim*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from PrimarySelection
[ RUN      ] PrimarySelection.source_can_offer
[       OK ] PrimarySelection.source_can_offer (12 ms)
[----------] 1 test from PrimarySelection (12 ms total)

[----------] Global test environment tear-down
[==========] 1 tests from 1 test cases run. (12ms total elapsed)
[  PASSED  ] 1 test
```

**Comment by Saviq** [comment]
Yeah, I checked the last two commits and they seem legit.

bors r=wmww,Saviq

**Comment by AlanGriffiths** [comment]
bors r=wmww,Saviq

**Pull request merged**
