### PR TITLE
Enable wlcs input tests

### PR DESCRIPTION
**Pull request by RAOF**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
LGTM I don't see why travis failed

bors try

**Comment by RAOF** [comment]
I also don't see why that failed? It seems that spread gave up while the remote was installing the build-deps?

bors try

**Comment by AlanGriffiths** [comment]
> I also don't see why that failed? It seems that spread gave up while the remote was installing the build-deps?

No, the build log also shows some compilation happening. It is just that whatever the problem is, it's being "folded" by Travis and we cannot see it.

**Comment by Saviq** [comment]
Ohkay so I at least got the errors out, trying it locally:

```In file included from /spread/mir/tests/acceptance-tests/wayland/wlcs/example/mir_integration.cpp:40:0:                                                                                                                                       
/spread/mir/tests/acceptance-tests/wayland/wlcs/include/mutex.h:119:6: error: extra ‘;’ [-Werror=pedantic]                                                                                                                                    
     };                                                                                                                                                                                                                                       
      ^
```

```/spread/mir/tests/acceptance-tests/wayland/wlcs/example/mir_integration.cpp: In member function ‘std::shared_ptr<mir::test::Signal> {anonymous}::InputEventListener::expect_event_with_time(std::chrono::nanoseconds)’:
/spread/mir/tests/acceptance-tests/wayland/wlcs/example/mir_integration.cpp:441:87: error: no matching function for call to ‘std::unordered_map<std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Sig$
al> >::insert(std::pair<long int, std::shared_ptr<mir::test::Signal> >)’
         expected_events.lock()->insert(std::make_pair(event_time.count(), done_signal));
                                                                                       ^
In file included from /usr/include/c++/5/unordered_map:48:0,
                 from /spread/mir/tests/acceptance-tests/wayland/wlcs/example/mir_integration.cpp:20:
/usr/include/c++/5/bits/unordered_map.h:432:7: note: candidate: std::pair<typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Defa$
lt_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__detail::__is_noexcept_hash<_Key, _Hash> > >::value, false, true> >::iterator, bool> std::uno$
dered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(const value_type&) [with _Key = std::chrono::duration<long int, std::ratio<1l, 1000000000l> >; _Tp = std::shared_ptr<mir::test::Signal>; _Hash = std::hash<std::chrono::duration<long int,
std::ratio<1l, 1000000000l> > >; _Pred = std::equal_to<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _Alloc = std::allocator<std::pair<const std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_pt$
<mir::test::Signal> > >; typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_pol$
cy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__detail::__is_noexcept_hash<_Key, _Hash> > >::value, false, true> >::iterator = std::__detail::_Node_iterator<std::pair<const std::chrono::dur$
tion<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> >, false, false>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::value_type = std::pair<const std::chrono::duration<long int, std::ratio<1l, 100000000$
l> >, std::shared_ptr<mir::test::Signal> >]
       insert(const value_type& __x)
       ^
/usr/include/c++/5/bits/unordered_map.h:432:7: note:   no known conversion for argument 1 from ‘std::pair<long int, std::shared_ptr<mir::test::Signal> >’ to ‘const value_type& {aka const std::pair<const std::chrono::duration<long int, st$
::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> >&}’
/usr/include/c++/5/bits/unordered_map.h:439:2: note: candidate: template<class _Pair, class> std::pair<typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_$
ashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__detail::__is_noexcept_hash<_Key, _Hash> > >::value, false, true$
 >::iterator, bool> std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(_Pair&&) [with _Pair = _Pair; <template-parameter-2-2> = <template-parameter-1-2>; _Key = std::chrono::duration<long int, std::ratio<1l, 1000000000l> >; _Tp $
 std::shared_ptr<mir::test::Signal>; _Hash = std::hash<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _Pred = std::equal_to<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _Alloc = std::allocator<std::p$
ir<const std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> > >]
  insert(_Pair&& __x)
  ^
/usr/include/c++/5/bits/unordered_map.h:439:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/unordered_map.h:435:32: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
       template<typename _Pair, typename = typename
                                ^
/usr/include/c++/5/bits/unordered_map.h:466:7: note: candidate: std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::iterator std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>$
:const_iterator, const value_type&) [with _Key = std::chrono::duration<long int, std::ratio<1l, 1000000000l> >; _Tp = std::shared_ptr<mir::test::Signal>; _Hash = std::hash<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; $
Pred = std::equal_to<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _Alloc = std::allocator<std::pair<const std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> > >; std::uno$
dered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::iterator = std::__detail::_Node_iterator<std::pair<const std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> >, false, false>; std::unordered_map<_$
ey, _Tp, _Hash, _Pred, _Alloc>::const_iterator = std::__detail::_Node_const_iterator<std::pair<const std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> >, false, false>; std::unordered_map<_$
ey, _Tp, _Hash, _Pred, _Alloc>::value_type = std::pair<const std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> >]
       insert(const_iterator __hint, const value_type& __x)
       ^
/usr/include/c++/5/bits/unordered_map.h:466:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/5/bits/unordered_map.h:473:2: note: candidate: template<class _Pair, class> std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::iterator std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(std::unordered_map<_Ke$
, _Tp, _Hash, _Pred, _Alloc>::const_iterator, _Pair&&) [with _Pair = _Pair; <template-parameter-2-2> = <template-parameter-1-2>; _Key = std::chrono::duration<long int, std::ratio<1l, 1000000000l> >; _Tp = std::shared_ptr<mir::test::Signa$
>; _Hash = std::hash<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _Pred = std::equal_to<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _Alloc = std::allocator<std::pair<const std::chrono::duration<lo$
g int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> > >]
  insert(const_iterator __hint, _Pair&& __x)
  ^
/usr/include/c++/5/bits/unordered_map.h:473:2: note:   template argument deduction/substitution failed:
/spread/mir/tests/acceptance-tests/wayland/wlcs/example/mir_integration.cpp:441:54: note:   cannot convert ‘std::make_pair(_T1&&, _T2&&) [with _T1 = long int; _T2 = std::shared_ptr<mir::test::Signal>&; typename std::__decay_and_strip<_T2$
::__type = std::shared_ptr<mir::test::Signal>; typename std::__decay_and_strip<_Tp>::__type = long int](done_signal)’ (type ‘std::pair<long int, std::shared_ptr<mir::test::Signal> >’) to type ‘std::unordered_map<std::chrono::duration<lon$
 int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> >::const_iterator {aka std::__detail::_Node_const_iterator<std::pair<const std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::S
ignal> >, false, false>}’
         expected_events.lock()->insert(std::make_pair(event_time.count(), done_signal));
                                                      ^
In file included from /usr/include/c++/5/unordered_map:48:0,
                 from /spread/mir/tests/acceptance-tests/wayland/wlcs/example/mir_integration.cpp:20:
/usr/include/c++/5/bits/unordered_map.h:488:2: note: candidate: template<class _InputIterator> void std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(_InputIterator, _InputIterator) [with _InputIterator = _InputIterator; _Key =
std::chrono::duration<long int, std::ratio<1l, 1000000000l> >; _Tp = std::shared_ptr<mir::test::Signal>; _Hash = std::hash<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _Pred = std::equal_to<std::chrono::duration<long i
nt, std::ratio<1l, 1000000000l> > >; _Alloc = std::allocator<std::pair<const std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> > >]
  insert(_InputIterator __first, _InputIterator __last)
  ^
/usr/include/c++/5/bits/unordered_map.h:488:2: note:   template argument deduction/substitution failed:
/spread/mir/tests/acceptance-tests/wayland/wlcs/example/mir_integration.cpp:441:87: note:   candidate expects 2 arguments, 1 provided
         expected_events.lock()->insert(std::make_pair(event_time.count(), done_signal));
                                                                                       ^
In file included from /usr/include/c++/5/unordered_map:48:0,
                 from /spread/mir/tests/acceptance-tests/wayland/wlcs/example/mir_integration.cpp:20:
/usr/include/c++/5/bits/unordered_map.h:499:7: note: candidate: void std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(std::initializer_list<typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Sele
ct1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__detail::__is_noe
xcept_hash<_Key, _Hash> > >::value, false, true> >::value_type>) [with _Key = std::chrono::duration<long int, std::ratio<1l, 1000000000l> >; _Tp = std::shared_ptr<mir::test::Signal>; _Hash = std::hash<std::chrono::duration<long int, std::
ratio<1l, 1000000000l> > >; _Pred = std::equal_to<std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _Alloc = std::allocator<std::pair<const std::chrono::duration<long int, std::ratio<1l, 1000000000l> >, std::shared_ptr<mir:
:test::Signal> > >; typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, s
td::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__detail::__is_noexcept_hash<_Key, _Hash> > >::value, false, true> >::value_type = std::pair<const std::chrono::duration<long int, std::ratio<1l, 100
0000000l> >, std::shared_ptr<mir::test::Signal> >]
       insert(initializer_list<value_type> __l)
       ^
/usr/include/c++/5/bits/unordered_map.h:499:7: note:   no known conversion for argument 1 from ‘std::pair<long int, std::shared_ptr<mir::test::Signal> >’ to ‘std::initializer_list<std::pair<const std::chrono::duration<long int, std::ratio
<1l, 1000000000l> >, std::shared_ptr<mir::test::Signal> > >’
[ 81%] Building CXX object tests/acceptance-tests/CMakeFiles/mir_acceptance_tests.dir/test_application_not_responding_detection.cpp.o
cd /spread/mir/obj-x86_64-linux-gnu/tests/acceptance-tests && /usr/bin/x86_64-linux-gnu-g++   -DLOG_NDEBUG=1 -DMESA_EGL_NO_X11_HEADERS -DMIR_BUILD_PLATFORM_MESA_KMS -DMIR_LIBINPUT_HAS_ACCEL_PROFILE=1 -DMIR_SERVER_EGL_OPENGL_API=EGL_OPENGL
_ES_API -DMIR_SERVER_EGL_OPENGL_BIT=EGL_OPENGL_ES2_BIT -DMIR_SERVER_GLEXT_H="<GLES2/gl2ext.h>" -DMIR_SERVER_GL_H="<GLES2/gl2.h>" -DMIR_VERSION_MAJOR=0 -DMIR_VERSION_MICRO=0 -DMIR_VERSION_MINOR=29 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/sp
read/mir/include/core -I/spread/mir/include/common -I/spread/mir/include/cookie -I/spread/mir/obj-x86_64-linux-gnu/src/capnproto -I/spread/mir/obj-x86_64-linux-gnu/src/protobuf -I/spread/mir/include/platform -I/spread/mir/include/miral -I
/spread/mir/include/server -I/usr/include/uuid -I/spread/mir/include/client -I/spread/mir/include/test -I/spread/mir/include/renderer -I/spread/mir/include/renderers/gl  -g -O0 -fstack-protector-strong -Wformat -Werror=format-security -Wd
ate-time  -pthread -g -std=c++14 -Werror -Wall -fno-strict-aliasing -pedantic -Wnon-virtual-dtor -Wextra -fPIC -Wno-psabi -Wno-error=overloaded-virtual -fno-lto    -include /spread/mir/obj-x86_64-linux-gnu/tests/acceptance-tests/mir_accep
tance_tests_precompiled.hpp -Winvalid-pch  -o CMakeFiles/mir_acceptance_tests.dir/test_application_not_responding_detection.cpp.o -c /spread/mir/tests/acceptance-tests/test_application_not_responding_detection.cpp
cc1plus: all warnings being treated as errors
tests/acceptance-tests/wayland/CMakeFiles/mir_wlcs_tests.dir/build.make:65: recipe for target 'tests/acceptance-tests/wayland/CMakeFiles/mir_wlcs_tests.dir/wlcs/example/mir_integration.cpp.o' failed
make[3]: *** [tests/acceptance-tests/wayland/CMakeFiles/mir_wlcs_tests.dir/wlcs/example/mir_integration.cpp.o] Error 1
make[3]: Leaving directory '/spread/mir/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:8528: recipe for target 'tests/acceptance-tests/wayland/CMakeFiles/mir_wlcs_tests.dir/all' failed
make[2]: *** [tests/acceptance-tests/wayland/CMakeFiles/mir_wlcs_tests.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

But still, we need to find out why we couldn't see that in travis...

**Pull request merged**
