### PR TITLE
Activate the logind support

### PR DESCRIPTION
**Pull request by AlanGriffiths**
This works locally and enables the logind support.

I had no time to investigate the CI failures - I assume it has something to do with failing to manage "headless" platforms. Maybe @RAOF will know what's happening.

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Trial to see if LogindConsoleServices is used when tests expect NullConsoleServices

**Comment by RAOF** [comment]
This seems to have unrelated `wlcs` changes?

**Comment by RAOF** [comment]
bors try

**Comment by RAOF** [comment]
Aha! Superseded by #426, which doesn't* fail all the tests in CI!

**Pull request closed without merging**
