### PR TITLE
cmake: Use native precompiled-headers support.

### PR DESCRIPTION
**Pull request by RAOF**
CMake 3.16 comes with in-built support for precompiled headers. Use it,
rather than our compilcated works-for-us `mir_precompiled_header` function.

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
```plain
2021-01-12T01:05:40.9613179Z CMake Error at tests/acceptance-tests/CMakeLists.txt:96 (mir_precompiled_header):
2021-01-12T01:05:40.9614051Z   Unknown CMake command "mir_precompiled_header".
```
:(

**Comment by RAOF** [comment]
Not *entirely* sure how that built locally :woman_facepalming:

**Review by wmww — APPROVED** [review]
LGTM
bros r+

**Comment by RAOF** [comment]
Does bors have special support for that misspelling? :thinking: 

bors r=wmww

**Comment by wmww** [comment]
I would expect nothing less

**Comment by Saviq** [comment]
> bros r+

> :fist_oncoming:

I.love.this.

**Pull request merged**
