### PR TITLE
Fix compilation failure with GCC-12 (missing headers)

### PR DESCRIPTION
**Pull request by gladk**
Adding missing headers, needed for compilation with GCC-12.

### CODE REVIEW

**Comment by Saviq** [comment]
Hi @gladk, could you please give a bit more context as to how you found these missing includes? We're building with GCC 12 in CI and locally, and have not seen this.

**Comment by gladk** [comment]
It is coming from [Debian Bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012998). Also we could reproduce it in the [CI](https://salsa.debian.org/mir-server-team/mir/-/jobs/3341135).

This patch resolves the problem and the package successfully built on all supported platforms in Debia.

**Review by RAOF — APPROVED** [review]
@Saviq this is a merge into the 1.8 branch, which we *don't* routinely build in CI :)

Looks sensible; all of those files use `std::array<>`, so we should be explicitly including it.

bors r+

**Comment by AlanGriffiths** [comment]
bors retry

**Comment by Saviq** [comment]
> @Saviq this is a merge into the 1.8 branch, which we _don't_ routinely build in CI :)

D'oh!

> bors r+

> bors retry

And the above is why these won't work. 1.8 still has travis in it, we'd have to move it to the new world if we really needed to.

bors r-

**Pull request merged**
