### PR TITLE
AbstractShell: refactor confinement

### PR DESCRIPTION
**Pull request by wmww**
This area is and continues to be a mess. These changes fix some problems with the new surface observer stuff I'm working on.

### CODE REVIEW

**Comment by wmww** [comment]
Uhh, CI? y u no go?

**Comment by Saviq** [comment]
> Uhh, CI? y u no go?

B/c conflicts:
> Conflicting files
> src/server/shell/abstract_shell.cpp

**Comment by Saviq** [comment]
> B/c conflicts:

Fixed.

**Comment by AlanGriffiths** [comment]
**Needs information**

[Fix surface lifetime in abstract shell tests](https://github.com/MirServer/mir/pull/2493/commits/50a3bf0e460fae5696336f2864e6da942caffb8c) seems like the wrong solution: it prevents crashes by ensuring that surfaces outlive the `shell`, I don't expect that to be necessary.

**Comment by wmww** [comment]
In production the lifetime of the surfaces is tracked with a weak_ptr, but since in the tests we use `mt::fake_shared()`, it assumes the surface is alive as long as the pointer is held. The only alternative I can think of is using real `shared_ptr`s, but that seems like more churn.

**Review by AlanGriffiths — APPROVED** [review]
> In production the lifetime of the surfaces is tracked with a weak_ptr, but since in the tests we use `mt::fake_shared()`, it assumes the surface is alive as long as the pointer is held. The only alternative I can think of is using real `shared_ptr`s, but that seems like more churn.

Seems like we could be missing real surface-lifetime related defects, but that's pre-existing

bors merge

**Pull request merged**
