### PR TITLE
Release 2.2

### PR DESCRIPTION
**Pull request by wmww**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
# rc1
Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

## mir-team/rc

Platform|20.10|20.04LTS|Notes
--|--|--|--
gbm-kms|||
gbm-x11|||
eglstream-kms|||
dispmanx|||

Console|20.10|20.04LTS|Notes
--|--|--|--
minimal||
linux-VT||
logind||

WM|20.10|20.04LTS|Notes
--|--|--|--
floating||
tiling||
kiosk||

## mir-test-tools

Host|amd64|arm64|armfh
------- | ------ | ------ | ------
18.04LTS|||
20.04LTS|||
20.10|||
UC18|||

**Comment by AlanGriffiths** [comment]
Running the rc1 mir-test-tools on 18.04 (the failing test varies, the failure doesn't):
```plain
[ RUN      ] GLMark2Wayland.windowed
[2020-11-06 16:18:34.984477] <information> mirserver: Starting
[2020-11-06 16:18:34.984549] < - debug - > mirserver: Not trying logind: "DISPLAY" is set and X need not have claimed the VT
[2020-11-06 16:18:34.984618] < - debug - > mirserver: Not using Linux VT subsystem for session management: Failed to find the current VT
[2020-11-06 16:18:34.984642] < - debug - > mirserver: No session management supported
[2020-11-06 16:18:34.984666] <information> VT switch key handler: No VT switching support available: MinimalConsoleServices does not support VT switching
[2020-11-06 16:18:34.984729] <information> mircommon: Loading modules from: /snap/mir-test-tools/4098/usr/lib/x86_64-linux-gnu/mir/server-platform
[2020-11-06 16:18:34.984781] <information> mircommon: Loading module: /snap/mir-test-tools/4098/usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-eglstream-kms.so.18
[2020-11-06 16:18:34.984812] <information> mircommon: Loading module: /snap/mir-test-tools/4098/usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-gbm-kms.so.18
[2020-11-06 16:18:34.984830] <information> mircommon: Loading module: /snap/mir-test-tools/4098/usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-wayland.so.18
[2020-11-06 16:18:34.984847] <information> mircommon: Loading module: /snap/mir-test-tools/4098/usr/lib/x86_64-linux-gnu/mir/server-platform/server-x11.so.18
[2020-11-06 16:18:34.984865] <information> mircommon: Loading module: /snap/mir-test-tools/4098/usr/lib/x86_64-linux-gnu/mir/server-platform/input-evdev.so.7
[2020-11-06 16:18:34.986078] < - debug - > eglstream: Found EGLDeviceEXT with device extensions: EGL_EXT_device_drm
[2020-11-06 16:18:34.987438] <information> gbm-kms: EGL platform does not support EGL_KHR_platform_gbm extension
[2020-11-06 16:18:34.987645] <information> gbm-kms: Failed to acquire DRM master: Operation not permitted
[2020-11-06 16:18:34.987978] <information> mirserver: Found graphics driver: mir:gbm-kms (version 2.2.0) Support priority: 0
[2020-11-06 16:18:34.987997] <information> mirserver: Found graphics driver: mir:wayland (version 2.2.0) Support priority: 0
[2020-11-06 16:18:34.988346] <information> mirserver: Found graphics driver: mir:x11 (version 2.2.0) Support priority: 192
[2020-11-06 16:18:34.988553] <information> mirserver: Selected driver: mir:x11 (version 2.2.0)
[2020-11-06 16:18:34.989541] <information> display: Screen resolution = 2560x1440
[2020-11-06 16:18:34.989568] <information> display: 1 visual(s) found
[2020-11-06 16:18:34.989582] <information> display: Using the first one :
[2020-11-06 16:18:34.989594] <information> display: ID		:	33
[2020-11-06 16:18:34.989613] <information> display: screen	:	0
[2020-11-06 16:18:34.989628] <information> display: depth		:	24
[2020-11-06 16:18:34.989651] <information> display: red_mask	:	0xFF0000
[2020-11-06 16:18:34.989665] <information> display: green_mask	:	0xFF00
[2020-11-06 16:18:34.989678] <information> display: blue_mask	:	0xFF
[2020-11-06 16:18:34.989692] <information> display: colormap_size	:	256
[2020-11-06 16:18:34.989706] <information> display: bits_per_rgb	:	8
[2020-11-06 16:18:35.044073] <information> mirserver: Using software cursor
[2020-11-06 16:18:35.044915] <information> mirserver: Selected input driver: mir:x11-input (version: 2.2.0)
ERROR: Dynamic exception type: std::_Nested_exception<std::runtime_error>
std::exception::what: Failed to bind Wayland EGL display

unknown file: Failure
C++ exception with description "Failed to start server thread" thrown in SetUp().
[2020-11-06 16:18:54.984888] <information> mirserver: Stopping
[  FAILED  ] GLMark2Wayland.windowed (20015 ms)
```

**Comment by AlanGriffiths** [comment]
> _Edit:_ can't reproduce using gbm-kms on 18.04, or on 20.04. Occurs both without and with `MIR_SERVER_BYPASS=off`

Correction, after some time (>30m) looping it failed on 20.04. That gives some hope of reproducing in a debug friendly environment.

**Comment by AlanGriffiths** [comment]
We should block until we (at least) understand #1799

**Comment by AlanGriffiths** [comment]
Confirmed I can build this branch on rawhide

**Comment by Saviq** [comment]
Another blocker: #1801.

**Comment by AlanGriffiths** [comment]
@wmww we've dealt with #1799 but #1801 is blocking.

@RAOF if #1801 proves intractable, how do you feel about changing the bypass default to "off" in the release?

**Comment by RAOF** [comment]
> @RAOF if #1801 proves intractable, how do you feel about changing the bypass default to "off" in the release?

I've not found an obvious fix for #1801 yet; I'm happy to make the default “off” for the release.

**Comment by AlanGriffiths** [comment]
# rc9
Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

## mir-team/rc

Platform|20.10|20.04LTS|Notes
--|--|--|--
gbm-kms||@AlanGriffiths|
gbm-x11||@AlanGriffiths|
eglstream-kms|||
dispmanx|||

Console|20.10|20.04LTS|Notes
--|--|--|--
minimal||@AlanGriffiths|
linux-VT|||
logind||@AlanGriffiths|

WM|20.10|20.04LTS|Notes
--|--|--|--
floating||@AlanGriffiths|
tiling||
kiosk||

## mir-test-tools

Host|amd64|arm64|armfh|Notes
------- | ------ | ------ | ------|----
18.04LTS||||
20.04LTS|@AlanGriffiths||
20.10||||
UC18||||

**Comment by AlanGriffiths** [comment]
New blocker (on 20.04 Xorg desktop):
```plain
$ mir-test-tools.performance-test 
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
Running main() from main.cpp
[==========] Running 7 tests from 4 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from GLMark2Wayland
[ RUN      ] GLMark2Wayland.fullscreen
Saving GLMark2 detailed results to: /tmp/GLMark2Wayland_fullscreen.log
[       OK ] GLMark2Wayland.fullscreen (10140 ms)
[ RUN      ] GLMark2Wayland.windowed
Segmentation fault (core dumped)
```

**Comment by AlanGriffiths** [comment]
> New blocker (on 20.04 Xorg desktop):

Following a reboot I see something different:
```plain
$ mir-test-tools.performance-test 
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
Running main() from main.cpp
[==========] Running 7 tests from 4 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from GLMark2Wayland
[ RUN      ] GLMark2Wayland.fullscreen
Saving GLMark2 detailed results to: /tmp/GLMark2Wayland_fullscreen.log
[       OK ] GLMark2Wayland.fullscreen (10789 ms)
[ RUN      ] GLMark2Wayland.windowed
ERROR: /build/mir-qEcagU/mir-2.2.0~rc9-g56624c1daf/src/platforms/x11/graphics/egl_helper.cpp(85): Throw in function void mir::graphics::X::helpers::EGLHelper::setup(Display*, Window, EGLContext)
Dynamic exception type: boost::wrapexcept<std::system_error>
std::exception::what: Failed to create EGL window surface: EGL_BAD_ALLOC (0x3003)

unknown file: Failure
C++ exception with description "Failed to start server thread" thrown in SetUp().
[  FAILED  ] GLMark2Wayland.windowed (20009 ms)
[----------] 2 tests from GLMark2Wayland (30798 ms total)

[----------] 2 tests from GLMark2Xwayland
[ RUN      ] GLMark2Xwayland.fullscreen
ERROR: /build/mir-qEcagU/mir-2.2.0~rc9-g56624c1daf/src/platforms/x11/graphics/egl_helper.cpp(85): Throw in function void mir::graphics::X::helpers::EGLHelper::setup(Display*, Window, EGLContext)
Dynamic exception type: boost::wrapexcept<std::system_error>
std::exception::what: Failed to create EGL window surface: EGL_BAD_ALLOC (0x3003)

unknown file: Failure
C++ exception with description "Failed to start server thread" thrown in SetUp().
[  FAILED  ] GLMark2Xwayland.fullscreen (20013 ms)
[ RUN      ] GLMark2Xwayland.windowed
Saving GLMark2 detailed results to: /tmp/GLMark2Xwayland_windowed.log
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Internal error:   Could not resolve keysym Invalid
Errors from xkbcomp are not fatal to the X server
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
[       OK ] GLMark2Xwayland.windowed (11931 ms)
[----------] 2 tests from GLMark2Xwayland (31945 ms total)

[----------] 2 tests from HostedGLMark2Wayland
[ RUN      ] HostedGLMark2Wayland.fullscreen
Saving host output to: /tmp/HostedGLMark2Wayland_fullscreen_host.log
Saving GLMark2 detailed results to: /tmp/HostedGLMark2Wayland_fullscreen.log
[       OK ] HostedGLMark2Wayland.fullscreen (10386 ms)
[ RUN      ] HostedGLMark2Wayland.windowed
Saving host output to: /tmp/HostedGLMark2Wayland_windowed_host.log
Saving GLMark2 detailed results to: /tmp/HostedGLMark2Wayland_windowed.log
[       OK ] HostedGLMark2Wayland.windowed (10246 ms)
[----------] 2 tests from HostedGLMark2Wayland (20632 ms total)

[----------] 1 test from CompositorPerformance
[ RUN      ] CompositorPerformance.regression_test_1563287
[2020-11-12 16:34:10.025370] < -warning- > miral: Failed to load cursor theme: default
[       OK ] CompositorPerformance.regression_test_1563287 (14641 ms)
[----------] 1 test from CompositorPerformance (14642 ms total)

[----------] Global test environment tear-down
[==========] 7 tests from 4 test suites ran. (98018 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] GLMark2Wayland.windowed
[  FAILED  ] GLMark2Xwayland.fullscreen
```

**Comment by wmww** [comment]
As I said in the call I'm not getting this error on either Sway or native X11 on 20.04. I'm also not getting
```
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
```
Might this be related?

**Comment by AlanGriffiths** [comment]
> Might this be related?

No, that's a benign side-effect of running snaps on Unity

**Comment by AlanGriffiths** [comment]
I see variations of the problem on 20.04, Rawhide and 20.10 (beware of https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1897224)

I also see it with `--revision=4122` (rc7), but not with `--revision=4119` (rc4)

**Comment by AlanGriffiths** [comment]
> As I said in the call I'm not getting this error on either Sway or native X11 on 20.04

Are you sure you have `latest/candidate: 2.2.0~rc9-snap72` of `mir-test-tools` installed?

**Comment by wmww** [comment]
```
installed:          2.2.0~rc9-snap72               (4128) 142MB -
```

**Comment by AlanGriffiths** [comment]
A few datapoints:
change|effect
--|--
`--devmode`|works
`--edge`|works
reverting `snapd` (to 2.47 (9607))|Intermittent failures
snap rebuilt locally|fails

Note: a local rebuild worked the first time with snapd reverted, but failed afterwards

**Comment by AlanGriffiths** [comment]
More weirdness (but reproduced on two machines!)

After installing `snappy-debug` the problem occurred with much reduced frequency (from at least than 3 in 4 to around 1 in 10). _Even after removing `snappy-debug` again!_

**Comment by AlanGriffiths** [comment]
> New blocker (on 20.04 Xorg desktop):

I no longer consider [this](#1810) to be a blocker for the 2.2 release. After investigating at length I'm sure that it only happens in the Mir-on-X platform and only when starting a server more than once in the same process.

**Comment by RAOF** [comment]
All the blockers have been resolved. The lack of background on dispmanx is not a regression, and is due to the background-drawing process failing to handle the weird 640x480 resolution my RPi was running at (it's got HDMI connection problems).

bors r+

**Pull request merged**
