### PR TITLE
moved moved wayland directory

### PR DESCRIPTION
**Pull request by wmww**
Made changes discussed in the Mir sync today
Done:
- moved moved wayland directory out of frontend
- renamed it frontend_wayland
- moved protocol directory into it

Will do in subsequent PR:
- move generated code into frontend_wayland/generated/
- rename generated files to be consistent and match the XML names
- move protocol XML files from installed dependency into frontend_wayland/protocol/

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
> move protocol XML files from installed dependency into frontend_wayland/protocol/

Please don't make this mandatory. Unlike in Ubuntu, we keep wayland-protocols pretty up to date in Fedora. I'd rather not have any vendoring for stuff like this.

**Comment by wmww** [comment]
@Conan-Kudo What is your concern with vendering?

my rationality is:
1. Not all distros (including Ubuntu) don't keep the protocols up to date. Some distros we may want to support in the future may not have them at all.
2. Downloading new protocol versions manually is easy.
3. Upgrading to use a new version of the protocol takes manual intervention anyway (when a library you use gets upgraded, the interface doesn't change and you get performance, security and bug fixes for free. Protocols are all interface, so a new one at best does nothing and at worst breaks the build.)
4. Many protocols (such as ones we may write or collaborate on in the future) are not in packages, and thus need to be bundled, and keeping them all in the same place is simpler.

**Comment by Conan-Kudo** [comment]
@wmww 

1. I'm okay with this as long as it's optional and non-default (or triggered when wayland-protocols are not detected in installed location)
2. Irrelevant for this
3. This should happen, because Mir needs to adapt to new protocols, and often the only way to detect them is for the build to break because of protocol changes. This is good, not bad.
4. This sounds sketchy. Why not make these part of the `wayland-protocols` development/package?

**Comment by Saviq** [comment]
Do protocols change after they stabilize, though? Or are new version of protocols introduced? Will we implement unstable interfaces?

**Comment by AlanGriffiths** [comment]
@Conan-Kudo @Saviq this is normal, expected and the practice followed by other Wayland projects (both compositors and toolkits). We don't (indeed cannot) rely on the same protocols and same versions being supported on Ubuntu 16.04 and Fedora rawhide!

These protocols (stable or unstable) are _by design_ able to maintain backwards compatibility: there is a negotiation between client and server to agree the version used. (Essentially the latest revision _both_ support.)

Mir will adapt to new protocol versions, but that means writing code to support the new features. This allows us to do so before protocols are updated on any specific target distro.

**Comment by Saviq** [comment]
Yeah, and breaking builds because of a protocol change that we can't support (because code needs to be written for it) doesn't sound like the right idea.

**Comment by Conan-Kudo** [comment]
How do you plan to notice then? Because from where I sit, I'm not sure if you have a plan for that.

**Comment by wmww** [comment]
I imagine someone will just have to check for new versions every few weeks. Unless a toolkit stops supporting an older interface version (won't happen immediately), that shouldn't cause any trouble. In theory a compositor could fall years behind and still work with new apps. The only thing that could happen is that a toolkit implements a new feature before we do, and then they can't use it while running under Mir, but depending on an external protocol package doesn't stop that.

**Pull request merged**
