### PR TITLE
MirAL 3.0

### PR DESCRIPTION
**Pull request by AlanGriffiths**
MirAL 3.0 removes deprecated stuff and rolls in changes that worked around ABI breaks.

### CODE REVIEW

**Comment by wmww** [comment]
Do we want to consider merging `Window` and `WindowInfo` here?

**Comment by wmww** [comment]
bors r-

Can we merge #1418 first so it's easier to cherry-pick onto the next 1.x release?

**Comment by AlanGriffiths** [comment]
> Can we merge #1418 first so it's easier to cherry-pick onto the next 1.x release?

Yes, will update symbols in the am.

**Pull request merged**
