### PR TITLE
ci: fix working with jammy in GitHub Actions

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
bors merge

**Comment by Saviq** [comment]
bors retry

Unless we're more consistently triggering qemu issues now?

**Comment by Saviq** [comment]
I've rebased this on #2645 to see if the shm tests are better.

**Comment by Saviq** [comment]
This didn't change since approved, so.

bors r=AlanGriffiths

**Comment by Saviq** [comment]
This better now.

bors r=AlanGriffiths

**Pull request merged**
