### PR TITLE
udev: Test (and fix) Context::char_device_from_devnum

### PR DESCRIPTION
**Pull request by RAOF**
Fixes: https://github.com/MirServer/mir-test-tools/issues/50

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
bors merge

**Comment by RAOF** [comment]
I suspect the test failure to be `umockdev`-version-related. Whatever it is *might* have been fixed in 0.17.0?

**Comment by Saviq** [comment]
I can confirm this gets us further in the lab:

```plain
[2022-05-16 10:53:54.262957] <information> GLRenderer: GL vendor: NVIDIA Corporation                                                                                                                       
[2022-05-16 10:53:54.262981] <information> GLRenderer: GL renderer: NVS 510/PCIe/SSE2                                                                                                                      
[2022-05-16 10:53:54.262991] <information> GLRenderer: GL version: OpenGL ES 3.2 NVIDIA 470.103.01                                                                                                         
[2022-05-16 10:53:54.262999] <information> GLRenderer: GLSL version: OpenGL ES GLSL ES 3.20
```

**Comment by Saviq** [comment]
> I suspect the test failure to be `umockdev`-version-related. Whatever it is _might_ have been fixed in 0.17.0?

Fails on: 0.14.1 and 0.16.3, so that tracks. Any way to work around (I see Alan worked around…)?

Also, we shouldn't be dropping the exception on the floor, we should at least log it? Could meaningfully be a separate PR though.

**Comment by AlanGriffiths** [comment]
@Saviq I agree with @RAOF's suspicion - umockdev 1.14.1 is not doing what I expect. Can you approve the hack I've added?

**Comment by AlanGriffiths** [comment]
> Also, we shouldn't be dropping the exception on the floor, we should at least log it? Could meaningfully be a separate PR though.

The exception was only "dropped" by the test, which logs it. (I.e. "nothing to see here")

**Review by Saviq — APPROVED** [review]
> Did you mean with the original issue? I think that was already addressed by #2430

Ah yes, that's what I meant. Didn't catch up on everything that happened yet.

> Can you approve the hack I've added?

bors merge r=AlanGriffiths

**Pull request merged**
