### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Release 2.0.0

### CODE REVIEW

**Comment by RAOF** [comment]
Tested gbm-kms, eglstream-kms, and x11 on 20.04

**Comment by AlanGriffiths** [comment]
## Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

Target|Tested| Status| Comments|By
------------ | -------------|---|--|--
18.04LTS||||
16.04LTS||||
20.04LTS|rc1|Completed|| @RAOF 
2.10||||
Nvidia||||

### 1. Qt app menus appear in weird places.

This seems to be a Qt issue as it can be reproduced with `QT_QPA_PLATFORM=wayland <app>` on Gnome DE.

## mir-test-tools

Target|Tested| Status| Comments|By
------------ | -------------|---|--|--
18.04LTS||||
16.04LTS||||
20.04LTS|rc1|Completed|| @AlanGriffiths  
2.10||||

## mir-kiosk
Target|Tested| Status| Comments|By
------------ | -------------|---|--|--
18.04LTS||||
16.04LTS||||
20.04LTS||||
2.10||||

**Comment by AlanGriffiths** [comment]
# NB blocked while we investigate:
* #1607
* #1617 

If they are addressed in time we might also pull in:
* #1614 
* #1615 
* #1616

**Comment by AlanGriffiths** [comment]
# rc3
Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

## mir-team/rc

Platform|20.10|20.04LTS|18.04LTS|
--|--|--|--
gbm-kms||||
gbm-x11||||
eglstream-kms||||
dispmanx|||

Console|20.10|20.04LTS|18.04LTS|
--|--|--|--
minimal||||
linux-VT||||
logind||||

WM|20.10|20.04LTS|18.04LTS|
--|--|--|--
floating||||
tiling||||
kiosk||||

**Note.** On 18.04LTS Qt app menus appear in weird places. This seems to be a Qt issue as it can be reproduced with `QT_QPA_PLATFORM=wayland <app>` on Gnome DE.

## mir-test-tools

Target|Status|Comments|By
------------|---|--|--
18.04LTS||| 
20.04LTS|||   
20.10|||   

## mir-kiosk
Target| Status| Comments|By
------------|---|--|--
18.04LTS|||
20.04LTS|||
20.10|||

**Comment by AlanGriffiths** [comment]
# rc5
Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

## mir-team/rc

Platform|20.10|20.04LTS|18.04LTS|
--|--|--|--
gbm-kms||||
gbm-x11||||
eglstream-kms||||
dispmanx|||

Console|20.10|20.04LTS|18.04LTS|
--|--|--|--
minimal||||
linux-VT||||
logind||||

WM|20.10|20.04LTS|18.04LTS|
--|--|--|--
floating||||
tiling||||
kiosk||||

**Note.** On 18.04LTS Qt app menus appear in weird places. This seems to be a Qt issue as it can be reproduced with `QT_QPA_PLATFORM=wayland <app>` on Gnome DE.

## mir-test-tools

Target|Status|Comments|By
------------|---|--|--
18.04LTS||| 
20.04LTS|||   
20.10|||   

## mir-kiosk
Target| Status| Comments|By
------------|---|--|--
18.04LTS|||
20.04LTS|||
20.10|||

**Comment by RAOF** [comment]
Note: I ran into #1627 while testing. This doesn't seem worth blocking the release over, though.

**Comment by AlanGriffiths** [comment]
# Release 2.0
Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

## mir-team/rc

Platform|20.10|20.04LTS|18.04LTS|
--|--|--|--
gbm-kms||@AlanGriffiths||
gbm-x11||@AlanGriffiths||
eglstream-kms||||
dispmanx|||

Console|20.10|20.04LTS|18.04LTS|
--|--|--|--
minimal||||
console||||
logind||@AlanGriffiths||

WM|20.10|20.04LTS|18.04LTS|
--|--|--|--
floating||@AlanGriffiths||
tiling||||
kiosk||@AlanGriffiths||

**Note.** On 18.04LTS Qt app menus appear in weird places. This seems to be a Qt issue as it can be reproduced with `QT_QPA_PLATFORM=wayland <app>` on Gnome DE.

## mir-test-tools

Target|Status|Comments|By
------------|---|--|--
18.04LTS||| 
20.04LTS|||   
20.10|||   

## mir-kiosk
Target| Status| Comments|By
------------|---|--|--
18.04LTS|||
20.04LTS|||
20.10|||

**Comment by AlanGriffiths** [comment]
bors merge

**Pull request merged**
