### PR TITLE
Release 2.3.0

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
# rc2

## Debs

Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

### Installed from from ppa:mir-team/rc

Platform|21.04|20.04LTS
--|--|--
gbm-kms||
gbm-x11||
eglstream-kms||
dispmanx||

Console|21.04|20.04LTS
--|--|--
minimal||
linux-VT||
logind||

WM|21.04|20.04LTS
--|--|--
floating||
tiling||
kiosk||

## Snaps (once `candidate` is built from ppa:mir-team/rc)

Host|mir-test-tools|mir-kiosk
--|--|--
Core20||
Core18||
21.04||
20.10||
20.04LTS||
18.04LTS||

**Comment by wmww** [comment]
I'm exactly clear on what the three consoles are. I Mir-on-X from a terminal, I launched KMS Mir from a TTY and I launched Mir from the GDM menu. I'm guessing those cover it all, but correct me if I'm wrong.

**Comment by wmww** [comment]
Notes:
- The cursor stutters on Mir-on-X when `glmark2-es2` is running (either the X11 or Wayland version). This doesn't happen on other platforms. I'm unaware if this is pre-existing.
- gnome-terminal wont launch on miral-shell when launched from GDM. No error, just doesn't quit or appear. It works on Mir-on-X and when Mir is launched from a TTY, and other apps including GTK apps work on miral-shell launched from GDM.

**Comment by AlanGriffiths** [comment]
> I'm exactly clear on what the three consoles are. I Mir-on-X from a terminal, I launched KMS Mir from a TTY and I launched Mir from the GDM menu. I'm guessing those cover it all, but correct me if I'm wrong.

* The "minimal" console is used when a "host" owns the display. I.e. with x11 or wayland platforms.
* The "logind" console is used when launched from a VT (either directly or a DM like GDM) to get ownership of the display from logind.
* The "linuxvt" console needs root to forcefully take ownership of the display without a user session. (Like the mir-kiosk daemon, or a DM)

**Comment by AlanGriffiths** [comment]
>     * gnome-terminal wont launch on miral-shell when launched from GDM. No error, just doesn't quit or appear. It works on Mir-on-X and when Mir is launched from a TTY, and other apps including GTK apps work on miral-shell launched from GDM.
> 
> 
> EDIT: I tried running gnome-terminal on Mir launched from GDM again and this time it came up _as an X11 app_. Launching other Wayland GTK apps from it worked fine.

That sounds very odd. The difference between logging into a VT directly and using GDM isn't that much. Essentiallyt the difference between whatever command you entered and
```plain
$ grep Exec= /usr/share/wayland-sessions/mir-shell.desktop 
Exec=bash --login -c mir-shell
```

**Comment by wmww** [comment]
I've dug into it more. Booting up, starting GDM and launching gnome-terminal still comes up as an X11 window. If I start a miral-shell from a TTY at the same time and launch a terminal in it (after other terminal windows have been closed) it comes up as Wayland and future terminals in the original (GDM) miral-shell come up on the new (TTY) miral-shell (as Wayland terminals). There's also a bunch of `gnome-terminal` process that can't be killed (`sudo kill -9 <PID>` does not work).

**Comment by wmww** [comment]
`miral-shell --console-provider=vt` works (both with root and without), but if any applications are started within the session closing it locks up the VT and VT switching. Again, haven't done this before, so I don't know if this is a new issue.

**Comment by wmww** [comment]
I tried testing mir-kiosk. It starts, but with `mir-kiosk --startup-apps weston-terminal` it's just a black screen. Is that supposed to work? Also there doesn't seem to be an `--enable-x11` option on the kiosk. Why?

**Comment by AlanGriffiths** [comment]
On Fri, 5 Feb 2021 14:22:54 -0800, William Wold wrote:
> I tried testing mir-kiosk. It starts, but with `mir-kiosk 
> --startup-apps weston-terminal` it's just a black screen. Is 
> that supposed to work? Also there doesn't seem to be an 
> `--enable-x11` option on the kiosk. Why?

It's a confined snap that doesn't provide an x11 slot. So it can't launch apps outside the snap or serve Xorg.

I guess we should drop the startup-apps option from miral-kiosk.

-- 
Sent using Dekko from my Ubuntu device

**Comment by wmww** [comment]
If startup apps doesn't work, how are you supposed to get an app in mir-kiosk? launch it externally?

**Comment by AlanGriffiths** [comment]
> If startup apps doesn't work, how are you supposed to get an app in mir-kiosk? launch it externally?

Yes, both mir-kiosk and the application snap run as daemons.

**Comment by AlanGriffiths** [comment]
> `miral-shell --console-provider=vt` works (both with root and without), but if any applications are started within the session closing it locks up the VT and VT switching. Again, haven't done this before, so I don't know if this is a new issue.

That is exceedingly odd. I've not tried `console-provider=vt`without root as I don't see how that _can_ work. I guess I should try that and see what the log says. There may be a bug here.

I regularly use the mir-kiosk daemon (which does use with `console-provider=vt` along with root) and had no issues with VT switching, so I'm surprised that leads to problems with `miral-shell`.

**Comment by AlanGriffiths** [comment]
> I've dug into it more. Booting up, starting GDM and launching gnome-terminal still comes up as an X11 window. If I start a miral-shell from a TTY at the same time and launch a terminal in it (after other terminal windows have been closed) it comes up as Wayland and future terminals in the original (GDM) miral-shell come up on the new (TTY) miral-shell (as Wayland terminals). There's also a bunch of `gnome-terminal` process that can't be killed (`sudo kill -9 <PID>` does not work).

As I said before, something is different between your your setup and mine and I suspect the logic in the `mir-shell` script isn't working on your machine. That's what needs digging into.

The `mir-shell` logic is clearly outdated, but it is working for me on 18.04, 20.04, 20.10 and 21.04. I'll submit a tidy-up PR and if that works for you we can cherry-pick it into Mir-2.3.0.

**Comment by AlanGriffiths** [comment]
> > `miral-shell --console-provider=vt` works (both with root and without), but if any applications are started within the session closing it locks up the VT and VT switching. Again, haven't done this before, so I don't know if this is a new issue.
> 
> That is exceedingly odd. I've not tried `console-provider=vt`without root as I don't see how that _can_ work. I guess I should try that and see what the log says. There may be a bug here.

As expected, without root `miral-shell --console-provider vt` fails to start.

```plain
[2021-02-08 14:22:47.784946] <information> mirserver: Starting
[2021-02-08 14:22:47.785309] < - debug - > mirserver: Using Linux VT subsystem for session management
[2021-02-08 14:22:47.785411] <information> mircommon: Loading modules from: /usr/lib/x86_64-linux-gnu/mir/server-platform
[2021-02-08 14:22:47.785472] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-wayland.so.19
[2021-02-08 14:22:47.785486] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/server-x11.so.19
[2021-02-08 14:22:47.785497] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-gbm-kms.so.19
[2021-02-08 14:22:47.785507] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/input-evdev.so.7
[2021-02-08 14:22:47.786216] <information> mirserver: Found graphics driver: mir:wayland (version 2.2.0) Support priority: 0
[2021-02-08 14:22:47.786238] <information> mirserver: Found graphics driver: mir:x11 (version 2.2.0) Support priority: 0
[2021-02-08 14:22:47.813078] <information> mirserver: Found graphics driver: mir:gbm-kms (version 2.2.0) Support priority: 256
[2021-02-08 14:22:47.813277] <information> mirserver: Selected driver: mir:gbm-kms (version 2.2.0)
[2021-02-08 14:22:47.813751] <information> gbm-kms: Using DRM device /dev/dri/card0
[2021-02-08 14:22:47.828543] < -warning- > gbm-kms: Unable to determine the current display mode.
[2021-02-08 14:22:47.828598] < -warning- > gbm-kms: Unable to determine the current display mode.
[2021-02-08 14:22:47.828627] < -warning- > gbm-kms: Unable to determine the current display mode.
[2021-02-08 14:22:47.828653] < -warning- > gbm-kms: Unable to determine the current display mode.
[2021-02-08 14:22:47.828679] < -warning- > gbm-kms: Unable to determine the current display mode.
[2021-02-08 14:22:47.830752] <information> gbm-kms: DRM device details:
[2021-02-08 14:22:47.830777] <information> gbm-kms: /dev/dri/card0: using driver i915 [Intel Graphics] (version: 1.6.0 driver date: 20200515)
[2021-02-08 14:22:47.831715] <information> gbm-kms: 	Output: eDP-1 (connected)
[2021-02-08 14:22:47.831736] <information> gbm-kms: 		Mode: 2560×1440@60.00
[2021-02-08 14:22:47.831756] <information> gbm-kms: 	Output: DisplayPort-1 (disconnected)
[2021-02-08 14:22:47.833090] <information> gbm-kms: 	Output: HDMI-A-1 (disconnected)
[2021-02-08 14:22:47.833112] <information> gbm-kms: 	Output: DisplayPort-2 (disconnected)
[2021-02-08 14:22:47.834440] <information> gbm-kms: 	Output: HDMI-A-2 (disconnected)
[2021-02-08 14:22:47.838092] < -warning- > gbm-kms: drmModeCrtcSetGamma failed: Invalid argument
[2021-02-08 14:22:47.847534] <information> gbm-kms: Detected single-GPU DisplayBuffer. Rendering will be sent directly to output
[2021-02-08 14:22:47.917631] <information> mirserver: Using hardware cursor
[2021-02-08 14:22:47.938024] <information> gbm-kms-buffer-allocator: Enabled linux-dmabuf import support
unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running
[2021-02-08 14:22:47.939042] <information> mircommon: Loading modules from: /usr/lib/x86_64-linux-gnu/mir/server-platform
[2021-02-08 14:22:47.939192] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-wayland.so.19
[2021-02-08 14:22:47.939249] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/server-x11.so.19
[2021-02-08 14:22:47.939295] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-gbm-kms.so.19
[2021-02-08 14:22:47.939370] <information> mircommon: Loading module: /usr/lib/x86_64-linux-gnu/mir/server-platform/input-evdev.so.7
ERROR: /build/mir-wAxBb5/mir-2.2.0/src/server/input/input_probe.cpp(104): Throw in function mir::UniqueModulePtr<mir::input::Platform> mir::input::probe_input_platforms(const mir::options::Option&, const std::shared_ptr<mir::EmergencyCleanupRegistry>&, const std::shared_ptr<mir::input::InputDeviceRegistry>&, const std::shared_ptr<mir::ConsoleServices>&, const std::shared_ptr<mir::input::InputReport>&, mir::SharedLibraryProberReport&)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: No appropriate input platform module found
```

**Comment by wmww** [comment]
Update on the gnome-terminal coming up as an X11 app problem: It appears the difference was not between logind and launching from a TTY, but was between mir-shell and miral-shell (I wasn't previously testing mir-shell from the TTY). Also it's fixed by #1922.

**Comment by wmww** [comment]
The VT issue is present in 2.2.0 and probably shouldn't block the release. Broken off into #1926.

**Comment by wmww** [comment]
Pointer stutter on glmark2 was present in last release as well. Shouldn't block release. Broken off into #1927.

**Comment by wmww** [comment]
# rc7
Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

Idk if we need to completely re-test or not. I'll do a complete re-test since I was the one seeing problems before.

Platform|21.04|20.04LTS
--|--|--
gbm-kms||
gbm-x11||
eglstream-kms||
dispmanx||

Console|21.04|20.04LTS
--|--|--
minimal||
linux-VT||
logind||

WM|21.04|20.04LTS
--|--|--
floating||
tiling||
kiosk||

## Snaps (once `candidate` is built from ppa:mir-team/rc)

### amd64
Host|mir-test-tools|mir-kiosk|egmde
--|--|--|--
Core20|||(n/a)
Core18|||(n/a)
21.04|@AlanGriffiths||
20.10|@AlanGriffiths||
20.04LTS|||
18.04LTS||
Fedora rawhide|||

### armhf
Host|mir-test-tools|mir-kiosk
--|--|--
Core20||
Core18||
21.04||
20.10||
20.04LTS||
18.04LTS||

### arm64
Host|mir-test-tools|mir-kiosk
--|--|--
Core20||
Core18||
21.04||
20.10||
20.04LTS||
18.04LTS||

**Comment by wmww** [comment]
I'm seeing scrolling be extremely slow and inverted on this rc. I didn't notice it before, but I may not have tested scrolling. Strangely Mir built from master is fine. Effects both Mir-on-X and KMS. There are changes to how scrolling is handled in this release, but none very recently. Perhaps Mir is loading an old input platform? Is anyone else having this problem?

**Comment by wmww** [comment]
I'm observing #1704 when running the perf tests on X11 from the mir-test-tools snap. Smoke tests from the snap work fine. Perf tests from the deb work fine.

**Comment by wmww** [comment]
I just did an apt update/upgrade/autoremove and I noticed a bunch of `mir-platform-graphics-*` packages were upgraded. Tried again and scrolling is good. Not sure what went wrong there, since I did `sudo apt install mir-demos mir-graphics-drivers-desktop mir-test-tools` after adding the PPA. In any case, it seems the problem was old input platforms (which makes sense).

**Comment by RAOF** [comment]
eglstream-kms platform appears to hang on shutdown, both with VT and logind console provider. I'll take a deeper look (and test on a 20.04 LTS live environment)

**Comment by RAOF** [comment]
Ok. So, eglstream-kms is broken on 21.04 with the `450.102.04` and `460.32.03` drivers, but works on 20.04 with both `450.102.04` and `460.32.03`.

**Comment by AlanGriffiths** [comment]
bors merge

**Pull request merged**
