### PR TITLE
Roll mirclient into mircommon and modernize mircommon cmake

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Alternative to #2087

**Review by wmww — APPROVED** [review]
LGTM
bors r+

**Comment by wmww** [comment]
Huh?

bors r+

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
OK this should work now.

bors retry

**Pull request merged**
