### PR TITLE
Revert "Merge #2245"

### LINKED ISSUE #2338: [2.7~rc6] fatal error
With ubuntu-frame `beta` (built with [2.7.0~rc60]) and qterminal installed.

From a terminal:

```
export WAYLAND_DISPLAY=wayland-99
ubuntu-frame&
QT_QPA_PLATFORM=wayland qterminal
```

Now, focus on the "Mir-on-X" window and press `Ctrl-Shift-W` and when confirm exit appears press "n".

Finally press a letter.

Expect: the letter appears in the terminal tab
Actual: Mir crashes with:
```
Mir fatal error: Attempt to send keyboard event to wl_surface@8 even though it was not given keyboard focus
```

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes #2338

### CODE REVIEW

**Comment by RAOF** [comment]
#2340 has been merged and fixes the same bug. I think this can be closed.

**Comment by AlanGriffiths** [comment]
> #2340 has been merged and fixes the same bug. I think this can be closed.

Yes, this was a fallback

**Comment by wmww** [comment]
Fixes #2331

**Review by RAOF — APPROVED** [review]
Ok. We should schedule an overhaul of focus/input dispatch for next cycle to fix this properly, but we're clearly not yet in a position to remove these bandaids.

bors r+

**Pull request merged**
