### PR TITLE
[mir:virtual] drop GenericEGLDisplayProvider

### PR DESCRIPTION
**Pull request by AlanGriffiths**
We don't need it anymore

### CODE REVIEW

**Comment by Saviq** [comment]
@AlanGriffiths you got some stray commits in here

**Comment by AlanGriffiths** [comment]
> @AlanGriffiths you got some stray commits in here

Fixed, thanks

**Comment by Saviq** [comment]
Need to reverse / drop a few tests:

```
VirtualGraphicsPlatformTest.can_acquire_interface_for_generic_egl_display_provider
```

**Review by mattkae — APPROVED** [review]
Looks good! Will merge once all of the checks are happy

**Pull request merged**
