### PR TITLE
[codeql] add static analysis

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
OK, it detected something!
```
   /home/runner/work/mir/mir/examples/miral-shell/shell_main.cpp: In function ‘int main(int, const char**)’:
  /home/runner/work/mir/mir/examples/miral-shell/shell_main.cpp:120:47: error: array subscript is above array bounds [-Werror=array-bounds]
       if (auto const test_value = test_buffer[21])
                                   ~~~~~~~~~~~~~~^
  /home/runner/work/mir/mir/examples/miral-shell/shell_main.cpp:117:20: error: ‘test_buffer[15]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
       if (auto const test_value = test_buffer[15])
                      ^~~~~~~~~~
  cc1plus: all warnings being treated as errors
  examples/miral-shell/CMakeFiles/miral-shell.dir/build.make:82: recipe for target 'examples/miral-shell/CMakeFiles/miral-shell.dir/shell_main.cpp.o' failed
```
(But it looks like that prevents detecting anything else)

**Comment by AlanGriffiths** [comment]
Try this once more to see what a year+ has changed

**Comment by AlanGriffiths** [comment]
> Try this once more to see what a year+ has changed

That looks a bit more meaningful than I recall. Although the alerts seem to mostly be that we use integer constants where `size_t` is clearer. Whatever happened to N4254?

**Comment by Saviq** [comment]
6 months more, let's see the state of it now and decide which way to go.

**Comment by Saviq** [comment]
I refreshed again, let's look at the results soon.

**Pull request closed without merging**
