### PR TITLE
graphics/wayland: Handle wl_shm buffers through the WaylandAllocator

### PR DESCRIPTION
**Pull request by RAOF**
This lets platforms do platform-specific optimisations for SHM buffers. All extant platforms currently use the newly-added `mg::wayland::buffer_from_wl_shm` helper, but can now opportunistically transition to platform-specific code.

### CODE REVIEW

**Comment by RAOF** [comment]
bors try

Was that arm64 failure transient?

**Comment by RAOF** [comment]
bors r=wmww

**Comment by RAOF** [comment]
bors r=wmww

**Comment by Saviq** [comment]
bors r=wmww

**Pull request merged**
