### PR TITLE
Clear input regions when they should not be set

### LINKED ISSUE #1091: No pointer or touch events using `--window-manager system-compositor` with Wayland clients
(On master, this isn't yet released)

Switch to a VT and start a Mir "host":
```plain
miral-shell --window-manager system-compositor
```

From another machine ssh in and start a nested Mir:
```plain
WAYLAND_DEBUG=client miral-app --wayland-host wayland-1 2>&1 | grep wl_touch
```
(Adjust wayland-1 to the socket exposed by the host.)

Try touching the screen.

Expect: touch events logged
Actual: no touch events logged

A bit more: using `miral-shell` without the `--window-manager system-compositor` the touch events are seen.

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Clear input regions when they should not be set. (Fixes #1091)

This is a workaround for dubious logic documented in #1094 and discussed in comments to #1093.

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
> The Wayland frontend _should_ be setting and updating the input region as needed. The fact that the input region is being set incorrectly would indicate there is a bug in the frontend.

I disagree, setting the input region is only the responsibility of the frontend because of a mismatch between the way Wayland and mirclient work. See #1094.

I don't object to "fixing" the frontend to handle the mismatch better (if that also fixes the problem), but there's no need to spend time on it right now.

**Comment by AlanGriffiths** [comment]
@wmww I've a different fix that will be more to your liking...

**Comment by wmww** [comment]
I think the sensible implementation may be to have a separate `BasicInputSurface` that implements `input::Surface` and have `BasicSurface` manage a list of them. Each subsurface would have both a `BufferStream` **and** an `InputSurface`. That, however, is an entirely separate problem from the system compositor window manager failing to respect the requested input region.

**Comment by AlanGriffiths** [comment]
> I think the sensible implementation may be to have a separate `BasicInputSurface` that implements `input::Surface` and have `BasicSurface` manage a list of them. Each subsurface would have both a `BufferStream` **and** an `InputSurface`. That, however, is an entirely separate problem from the system compositor window manager failing to respect the requested input region.

Yes, as discussed [elsewhere](#1094), we should revisit once we no longer have to support the mirclient related codepaths.

bors r=wmww

**Pull request merged**
