### PR TITLE
snap,ci: migrate to 22.04 / `base: core22`

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
WFM

**Review by Saviq — COMMENTED** [review]
Since we have #2868, this is now good to go.

Though we may want to replace `egmde-confined-desktop` with `confined-shell`?

**Comment by AlanGriffiths** [comment]
> Though we may want to replace `egmde-confined-desktop` with `confined-shell`?

I agree,  `egmde-confined-desktop` has served its purpose and any future development in this space lies with `confined-shell`.

**Comment by Saviq** [comment]
> I agree, `egmde-confined-desktop` has served its purpose and any future development in this space lies with `confined-shell`.

Done.

**Review by AlanGriffiths — APPROVED** [review]
bors merge

**Pull request merged**
