### PR TITLE
Release 2.12.1

### PR DESCRIPTION
**Pull request by Saviq**
- Bugs fixed:
      . Add missing #include statements (#2802)
      . mir_wayland_generator generated code that include non public
        header (#2804)
      . Building docs fails when trying to not remove doc/html/cppguide (#2800)
      . wayland: Add missing cstdint includes (#2821)
      . Enabling zwp_idle_inhibit_manager_v1 causes Mir to crash with some
        applications (#2836)
      . [Wayland] idle_inhibit_unstable_v1 is badly broken (#2838)

### CODE REVIEW

**Comment by Saviq** [comment]
# ~rc1

[TestPlan](https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir)

Platform |20.04LTS|22.04LTS|22.10|23.04
-- | -- | -- | -- | --
gbm-kms |   |   |   |
gbm-x11 |   |   |   |
eglstream-kms |   |   |  
dispmanx |   |   | 

Console |20.04LTS|22.04LTS|22.10|23.04
-- | -- | -- | -- | --
minimal |   |   |   |
linux-VT |   |   |   |
logind |   |   |   |

WM |20.04LTS|22.04LTS|22.10|23.04
-- | -- | -- | -- | --
floating |   |   |   |
tiling |   |   |   |
kiosk |   |   |   |

**Comment by AlanGriffiths** [comment]
Oh, that's disappointing: I had forgotten #2792 (but #2809 isn't really a bugfix)

**Review by AlanGriffiths — APPROVED** [review]
WFM

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Pull request merged**
