### PR TITLE
Rename miral::CommandLineOption to ConfigurationOption

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Candidate for cherry-picking to 2.9 as we've already broken ABI

### CODE REVIEW

**Review by Saviq — COMMENTED** [review]
These left on purpose?

```plain
tests/miral/command_line_option.cpp:TEST(CommandLineOption, can_take_lambdas)
tests/miral/command_line_option.cpp:TEST(CommandLineOption, can_take_repeated_strings)
```

**Comment by AlanGriffiths** [comment]
> These left on purpose?

No, but happily it proves we are maintaining the API

**Review by Saviq — APPROVED** [review]
If you want to keep them, feel free.

bors d+

**Comment by AlanGriffiths** [comment]
> If you want to keep them, feel free.

We can rename them when we deprecate (or drop) `CommandLineOption`

bors r=Saviq

**Pull request merged**
