### PR TITLE
Simplify Wayland EGL helpers

### PR DESCRIPTION
**Pull request by RAOF**
The various Wayland EGL helpers do not need an `EGLContext` and a Wayland executor; they only need access to a thread with a current `EGLContext` to do cleanup.

At the time they were written, we did not have a good way to provide that, but now we have `EGLContextExecutor` which provides exactly (and only) that.

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
Yes, that's a fitter abstraction.

bors merge

**Comment by AlanGriffiths** [comment]
bors retry

**Comment by AlanGriffiths** [comment]
bors merge

**Review by Saviq — APPROVED** [review]
Yups for the merge.

bors r=AlanGriffiths

**Pull request merged**
