### PR TITLE
Add virtual pointer protocol name to miral

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Sorry, lost these commits when rebasing the target

### CODE REVIEW

**Review by RAOF — APPROVED** [review]
LGTM

**Comment by AlanGriffiths** [comment]
bors r=RAOF

**Comment by Saviq** [comment]
```plain
dpkg-gensymbols: error: some new symbols appeared in the symbols file: see diff output below
dpkg-gensymbols: warning: debian/libmiral5/DEBIAN/symbols doesn't match completely debian/libmiral5.symbols
--- debian/libmiral5.symbols (libmiral5_3.6.0_amd64)
+++ dpkg-gensymbolsJh2F3K	2022-08-16 08:02:31.057015993 +0000
@@ -1,5 +1,6 @@
 libmiral.so.5 libmiral5 #MINVER#
  MIRAL_3.6@MIRAL_3.6 3.6.0
+ _ZN5miral17WaylandExtensions31zwlr_virtual_pointer_manager_v1E@MIRAL_3.6 3.6.0
  (c++)"miral::AddInitCallback::AddInitCallback(std::function<void ()> const&)@MIRAL_3.6" 3.6.0
  (c++)"miral::AddInitCallback::operator()(mir::Server&) const@MIRAL_3.6" 3.6.0
  (c++)"miral::AddInitCallback::~AddInitCallback()@MIRAL_3.6" 3.6.0
dh_makeshlibs: error: failing due to earlier errors
```

**Comment by AlanGriffiths** [comment]
bors r=RAOF

**Pull request merged**
