### PR TITLE
Prefer lambdas to std::bind()

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Drive-by modernization of code

### CODE REVIEW

**Comment by wmww** [comment]
```
/spread/mir/src/server/input/surface_input_dispatcher.cpp: In instantiation of â€˜mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)> [with auto:1 = std::shared_ptr<mir::scene::Surface>]â€™:
/usr/aarch64-linux-gnu/include/c++/5/type_traits:2346:26:   required by substitution of â€˜template<class _Fn, class ... _Args> static std::__success_type<decltype (declval<_Fn>()((declval<_Args>)()...))> std::__result_of_other_impl::_S_test(int) [with _Fn = mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>; _Args = {std::shared_ptr<mir::scene::Surface>}]â€™
/usr/aarch64-linux-gnu/include/c++/5/type_traits:2357:55:   required from â€˜struct std::__result_of_impl<false, false, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, std::shared_ptr<mir::scene::Surface> >â€™
/usr/aarch64-linux-gnu/include/c++/5/type_traits:2361:12:   required from â€˜class std::result_of<mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>(std::shared_ptr<mir::scene::Surface>)>â€™
/usr/aarch64-linux-gnu/include/c++/5/functional:2053:9:   required by substitution of â€˜template<class _Functor, class, class> std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>; <template-parameter-1-2> = void; <template-parameter-1-3> = <missing>]â€™
/usr/aarch64-linux-gnu/include/c++/5/ext/new_allocator.h:120:4:   required from â€˜void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = {anonymous}::InputDispatcherSceneObserver; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; _Tp = {anonymous}::InputDispatcherSceneObserver]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/alloc_traits.h:530:4:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr_base.h:617:4:   required from â€˜std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Args&& ...) [with _Tp = {anonymous}::InputDispatcherSceneObserver; _Alloc = std::allocator<{anonymous}::InputDispatcherSceneObserver>; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr_base.h:1097:35:   required from â€˜std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<{anonymous}::InputDispatcherSceneObserver>; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; _Tp = {anonymous}::InputDispatcherSceneObserver; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr.h:319:64:   required from â€˜std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<{anonymous}::InputDispatcherSceneObserver>; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; _Tp = {anonymous}::InputDispatcherSceneObserver]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr.h:620:39:   required from â€˜std::shared_ptr<_Tp1> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = {anonymous}::InputDispatcherSceneObserver; _Alloc = std::allocator<{anonymous}::InputDispatcherSceneObserver>; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr.h:635:39:   required from â€˜std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = {anonymous}::InputDispatcherSceneObserver; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}]â€™
/spread/mir/src/server/input/surface_input_dispatcher.cpp:157:38:   required from here
/spread/mir/src/server/input/surface_input_dispatcher.cpp:155:33: error: cannot call member function â€˜void mir::input::SurfaceInputDispatcher::surface_removed(std::shared_ptr<mir::scene::Surface>)â€™ without object
         [this](auto const& s) { surface_removed(s); },
                                 ^
In file included from /usr/aarch64-linux-gnu/include/c++/5/aarch64-linux-gnu/bits/c++allocator.h:33:0,
                 from /usr/aarch64-linux-gnu/include/c++/5/bits/allocator.h:46,
                 from /usr/aarch64-linux-gnu/include/c++/5/memory:63,
                 from /spread/mir/include/server/mir/input/input_dispatcher.h:23,
                 from /spread/mir/src/server/input/surface_input_dispatcher.h:22,
                 from /spread/mir/src/server/input/surface_input_dispatcher.cpp:19:
/usr/aarch64-linux-gnu/include/c++/5/ext/new_allocator.h: In instantiation of â€˜void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = {anonymous}::InputDispatcherSceneObserver; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; _Tp = {anonymous}::InputDispatcherSceneObserver]â€™:
/usr/aarch64-linux-gnu/include/c++/5/bits/alloc_traits.h:530:4:   required from â€˜static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = {anonymous}::InputDispatcherSceneObserver; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; _Tp = {anonymous}::InputDispatcherSceneObserver; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<{anonymous}::InputDispatcherSceneObserver>]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr_base.h:522:39:   required from â€˜std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; _Tp = {anonymous}::InputDispatcherSceneObserver; _Alloc = std::allocator<{anonymous}::InputDispatcherSceneObserver>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr_base.h:617:4:   required from â€˜std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Args&& ...) [with _Tp = {anonymous}::InputDispatcherSceneObserver; _Alloc = std::allocator<{anonymous}::InputDispatcherSceneObserver>; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr_base.h:1097:35:   required from â€˜std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<{anonymous}::InputDispatcherSceneObserver>; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; _Tp = {anonymous}::InputDispatcherSceneObserver; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr.h:319:64:   required from â€˜std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<{anonymous}::InputDispatcherSceneObserver>; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}; _Tp = {anonymous}::InputDispatcherSceneObserver]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr.h:620:39:   required from â€˜std::shared_ptr<_Tp1> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = {anonymous}::InputDispatcherSceneObserver; _Alloc = std::allocator<{anonymous}::InputDispatcherSceneObserver>; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}]â€™
/usr/aarch64-linux-gnu/include/c++/5/bits/shared_ptr.h:635:39:   required from â€˜std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = {anonymous}::InputDispatcherSceneObserver; _Args = {mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>}]â€™
/spread/mir/src/server/input/surface_input_dispatcher.cpp:157:38:   required from here
/usr/aarch64-linux-gnu/include/c++/5/ext/new_allocator.h:120:4: error: no matching function for call to â€˜{anonymous}::InputDispatcherSceneObserver::InputDispatcherSceneObserver(mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:1&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>, mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda()>)â€™
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
/spread/mir/src/server/input/surface_input_dispatcher.cpp:47:5: note: candidate: {anonymous}::InputDispatcherSceneObserver::InputDispatcherSceneObserver(const std::function<void(std::shared_ptr<mir::scene::Surface>)>&, const std::function<void(const mir::scene::Surface*)>&, const std::function<void()>&)
     InputDispatcherSceneObserver(
     ^
/spread/mir/src/server/input/surface_input_dispatcher.cpp:47:5: note:   no known conversion for argument 2 from â€˜mir::input::SurfaceInputDispatcher::SurfaceInputDispatcher(const std::shared_ptr<mir::input::Scene>&)::<lambda(const auto:2&)>â€™ to â€˜const std::function<void(const mir::scene::Surface*)>&â€™
```

**Comment by RAOF** [comment]
Ah, 16.04, bane of our existence.

**Comment by RAOF** [comment]
bors r=wmww,RAOF

**Pull request merged**
