### PR TITLE
Release 1.1.1

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Draft bugfix release

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
[Test plan](https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir) complete for 18.04LTS

**Comment by AlanGriffiths** [comment]
[Test plan](https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir) complete for 18.10 (Mesa)

**Comment by RAOF** [comment]
Test plan complete for 19.04 (eglstream-kms)

**Comment by AlanGriffiths** [comment]
[Test plan](https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir) complete for 16.04LTS (Mesa)

**Comment by AlanGriffiths** [comment]
Also tested the mir-test-tools snap built from ppa:mir-team/rc on amd64

**Pull request merged**
