### PR TITLE
Detect GTest/GMock via pkg-config

### PR DESCRIPTION
**Pull request by z3ntu**
It works but it can probably be improved :) but I'm not really familiar with how cmake works

### CODE REVIEW

**Comment by z3ntu** [comment]
The CI failures look pretty unrelated.

**Comment by wmww** [comment]
At least the Fedora Rawhide failure seems to be caused by gtest pkg-config stuff. The others I'm not sure about. Will look at tomorrow.

**Comment by Conan-Kudo** [comment]
I've proposed fixes for the Fedora package to fix some issues with this as [a pull request to the `gtest` package](https://src.fedoraproject.org/rpms/gtest/pull-request/2).

**Comment by Conan-Kudo** [comment]
I've used this change to successfully build Mir with gtest 1.8.1, and have [proposed it as an update for Fedora 29](https://bodhi.fedoraproject.org/updates/FEDORA-2018-905e0b102d).

**Comment by Conan-Kudo** [comment]
Your initial change works, however, the rawhide image probably isn't hitting a mirror that offers the updated gtest package that provides the correct pkgconfig data.

**Comment by AlanGriffiths** [comment]
Confirmed: this works on Fedora 29 (after also applying #632 to fix an unrelated issue).

That ought to apply to the rawhide image too: something is wrong in CI!

I'll spin up a Fedora 28 instance to investigate what is happening there.

**Comment by AlanGriffiths** [comment]
Superseded by #635

**Pull request closed without merging**
