### PR TITLE
Don't request axis values from libinput when axis is unset

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes: #2248

### CODE REVIEW

**Review by wmww — APPROVED** [review]
Tested and working
bors r+

**Comment by AlanGriffiths** [comment]
bors retry

**Comment by AlanGriffiths** [comment]
Alpine/edge timing out on a test:
```plain
233/233 Test #221: mir_umock_unit_tests.UdevWrapperDeathTest.* ...........................................................***Timeout 600.09 sec
```

Not obviously related to this PR

**Comment by AlanGriffiths** [comment]
bors retry

**Comment by AlanGriffiths** [comment]
bors r=wmww

**Pull request merged**
