### PR TITLE
release/2.3

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Bugfix release

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
# rc9

## Debs

Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

### Installed from from ppa:mir-team/rc

Platform|21.04|20.04LTS
--|--|--
gbm-kms||
gbm-x11||@AlanGriffiths
eglstream-kms||
dispmanx||

Console|21.04|20.04LTS
--|--|--
minimal||@AlanGriffiths
linux-VT||
logind||

WM|21.04|20.04LTS
--|--|--
floating||@AlanGriffiths
tiling||
kiosk||

## Snaps (once `candidate` is built from ppa:mir-team/rc)

### amd64
Host|mir-test-tools|mir-kiosk|egmde
--|--|--|--
Core20|||(n/a)
Core18|||(n/a)
21.04|||
20.10|||
20.04LTS|||
18.04LTS|||
Fedora rawhide|||

### armhf
Host|mir-test-tools|mir-kiosk
--|--|--
Core20||
Core18||
21.04||
20.10||
20.04LTS||
18.04LTS||

### arm64
Host|mir-test-tools|mir-kiosk
--|--|--
Core20||
Core18||
21.04||
20.10||
20.04LTS||
18.04LTS||

**Comment by AlanGriffiths** [comment]
*Release on hold pending investigation* 

Something about the changes here doesn't work well with mir-kiosk-neverputt (my go-to for an app that uses pointer confinement). Pointer movements are mostly OK, but with occasional large jerks. (Probably because there are motion events it doesn't expect.)

**Comment by AlanGriffiths** [comment]
> _Release on hold pending investigation_
> 
> Something about the changes here doesn't work well with mir-kiosk-neverputt (my go-to for an app that uses pointer confinement). Pointer movements are mostly OK, but with occasional large jerks. (Probably because there are motion events it doesn't expect.)

Fixed by #1965 (cherry picked)

**Comment by AlanGriffiths** [comment]
# rc12

## Debs

Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir

### Installed from from ppa:mir-team/rc

Platform|21.04|20.04LTS
--|--|--
gbm-kms||
gbm-x11||
eglstream-kms||
dispmanx||

Console|21.04|20.04LTS
--|--|--
minimal||
linux-VT||
logind||

WM|21.04|20.04LTS
--|--|--
floating||
tiling||
kiosk||

## Snaps (once `candidate` is built from ppa:mir-team/rc)

### amd64
Host|mir-test-tools|mir-kiosk|egmde
--|--|--|--
Core20|||(n/a)
Core18|||(n/a)
21.04|||
20.10|||
20.04LTS|||
18.04LTS|||
Fedora rawhide|||

### armhf
Host|mir-test-tools|mir-kiosk
--|--|--
Core20||
Core18||
21.04||
20.10||
20.04LTS||
18.04LTS||

### arm64
Host|mir-test-tools|mir-kiosk
--|--|--
Core20||
Core18||
21.04||
20.10||
20.04LTS||
18.04LTS||

**Comment by wmww** [comment]
Might it be worth it to include https://github.com/MirServer/mir/pull/1955? https://github.com/MirServer/mir/issues/1954 seems worth fixing.

**Comment by wmww** [comment]
All seems to be in order on 21.04. I logged some problems with Firefox but those go back further than this release.

**Comment by AlanGriffiths** [comment]
bors merge

**Pull request merged**
