### PR TITLE
[spread] fix fedora rawhide and add 29

### PR DESCRIPTION
**Pull request by Saviq**
Upgrading proved to be unreliable, on the google provider we can use a
pre-built rawhide image instead.

There is now a Fedora 29 image, too, so use it.

Also reduce the spread timeout so it fits under travis's one.

### CODE REVIEW

**Comment by RAOF** [comment]
bors try

**Comment by Saviq** [comment]
@Conan-Kudo hey, any idea what's going wrong here: https://travis-ci.org/MirServer/mir/jobs/458600292?

```
+ dnf install --assumeyes cmake make gcc-c++ boost-devel mesa-libEGL-devel mesa-libGLES-devel glm-devel protobuf-lite-devel protobuf-compiler capnproto-devel capnproto glog-devel gflags-devel systemd-devel glib2-devel wayland-devel mesa-libgbm-devel libepoxy-devel nettle-devel libinput-devel libxml++-devel libuuid-devel libxkbcommon-devel freetype-devel lttng-ust-devel libatomic qterminal qt5-qtwayland python3-pillow libevdev-devel umockdev-devel gtest-devel gmock-devel dbus python3-dbusmock python3-gobject-base python3-dbus mesa-libwayland-egl-devel libXcursor-devel yaml-cpp-devel
…
Total                                           7.2 MB/s |  71 MB     00:09     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
Failed to obtain the transaction lock (logged in as: root).
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Could not run transaction.
```

**Comment by Saviq** [comment]
bors try

**Comment by Conan-Kudo** [comment]
I don't understand what's happening here... @dmach, what is this?

**Pull request merged**
