### PR TITLE
XWayland: create scene surface only when needed

### LINKED ISSUE #1172: XWayland: windows can not choose their initial size
When you open Gedit in Wayland or actual X11, it sets its initial size to whatever its size was last time. When running in XWayland in Mir, it is always the same (I believe 640x480).

### PR DESCRIPTION
**Pull request by wmww**
XWayland: create scene surface only when needed. (Fixes: #1172)

### CODE REVIEW

**Comment by wmww** [comment]
Hmm... what app(s) did you test with?

**Comment by AlanGriffiths** [comment]
> Hmm... what app(s) did you test with?

xeyes and xterm

**Comment by wmww** [comment]
I can reproduce. I'll figure it out

**Comment by wmww** [comment]
A different approach, but still fixes #1172. If a surface has not had its initial commit when creating an XWayland window from it, wait for that commit before creating the Mir scene surface. If it has already committed, create the Mir scene surface immediately.

**Comment by wmww** [comment]
bors r=AlanGriffiths

**Pull request merged**
