### PR TITLE
Pick up min/max size

### PR DESCRIPTION
**Pull request by wmww**
It appears that this isn't supported in the window manager at all and that's a bigger job than I want to do right now, but at least the correct information is getting fed in. I moved the value handler to a template function so property handlers can be easily implemented for more int types.

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
> It appears that this isn't supported in the window manager at all

I'm not sure how you reach this conclusion. There has been support and I don't recall it being removed. See, for example, `ClientLibrary.min_size_respected_when_placing_surface`

**Comment by wmww** [comment]
It might be supported initially, but it is not respected when interactively resizing windows (the most obvious way to test). I came to this conclusion by sticking a print statement in `BasicSurface::resize()` and watching the window manager happy try to resize windows to a negative size.

**Review by AlanGriffiths — APPROVED** [review]
LGTM

bors r+

**Comment by wmww** [comment]
bors r=AlanGriffiths

**Pull request merged**
