### PR TITLE
GitHub: Try to upload core files on failure

### PR DESCRIPTION
**Pull request by RAOF**
Sometimes, tests fail with a crash. If we could get these tests to dump a core we could inspect later, that would be nice!

### CODE REVIEW

**Comment by RAOF** [comment]
CI is being *pretty* consistent at failing that armhf test, so hopefully this will get tested :)

**Comment by RAOF** [comment]
Oh goddamnit!

**Comment by Saviq** [comment]
Is the core useful at all without being retraced in situ? We may need to artifact the binaries produced?

**Comment by Saviq** [comment]
So this _should_ give us dumps from native binaries… but I can't see the target arch / qemu dumps anywhere when driven from sbuild… If I run things by hand, I get `qemu_*.core` files in `$PWD`… but I couldn't see them anywhere in the chroot :/.

**Comment by RAOF** [comment]
Oh! I wonder if apport is running in the LXD container, and resetting `core_pattern`?

**Comment by Saviq** [comment]
> Oh! I wonder if apport is running in the LXD container, and resetting `core_pattern`?

Testing locally the dumps ended up in `core_pattern`, but _inside_ the container + chroot, which is why I went the mount way.

The qemu — the more interesting ARM ones? — I only ever saw in `$PWD`, which I suppose makes sense since it's QEMU dumping those, and not the kernel?

**Comment by AlanGriffiths** [comment]
This has been inactive too long. At a minimum it needs rebasing on main, and the discussion probably needs to be resolved too

**Pull request closed without merging**
