### PR TITLE
Modernise `GraphicsBufferAllocator`

### PR DESCRIPTION
**Pull request by RAOF**
The server no longer needs a way to allocate “hardware” buffers for its own use,
and we always want *clients* to be able to allocate hardware buffers so it no
longer makes sense for `WaylandAllocator` to be an optional interface.

Fold `WaylandAllocator` into `GraphicsBufferAllocator`, and clean up after it.

### CODE REVIEW

**Comment by RAOF** [comment]
Huh. So I rebased this onto master and now the tests pass locally, so :woman_shrugging:

**Comment by wmww** [comment]
Still nope

bors delegate+

**Comment by AlanGriffiths** [comment]
Progress: Just the rpi build now.

**Comment by RAOF** [comment]
…and there's RPi done.

bors r=wmww

**Pull request merged**
