### PR TITLE
Fix rendering that spans outputs

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes: #1753

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Note that this may well be the wrong way to solve the problem: someone with a better understanding of GL may well have a correct idea.

**Review by wmww — APPROVED** [review]
Looks reasonable to me and empirically fixes the problem (yay!). I'll let @RAOF have a look since he's the one that knows this part of the code.

**Review by RAOF — CHANGES_REQUESTED** [review]
Urgh.

So, this is likely to work in practise (although it involves unnecessary texture uploads), but I *think* that, *technically*, uploading to the texture invalidates it across *all* GL contexts in the absence of other *GL* synchronisation. In practise this will almost certainly work, because we're uploading identical data, but weird GPU memory quirks might stymie that?

I *think* `glFinish()` after the `upload_to_texture()` would work (although I'm *still* not sure if that's mandated to DTRT across EGLContexts), but the thing that's *guaranteed* to work is an EGL fence ([base extension](https://registry.khronos.org/EGL/extensions/KHR/EGL_KHR_fence_sync.txt) and [GPU-side-wait extension](https://registry.khronos.org/EGL/extensions/KHR/EGL_KHR_wait_sync.txt)).

**Comment by AlanGriffiths** [comment]
> I _think_ `glFinish()` after the `upload_to_texture()` would work

Empirically that "works", but should it be in, rather than after, the `upload_to_texture()`? (The other  call site in `MemoryBackedShmBuffer::bind()` could have the same issue.)

**Comment by AlanGriffiths** [comment]
> the thing that's _guaranteed_ to work is an EGL fence ([base extension](https://registry.khronos.org/EGL/extensions/KHR/EGL_KHR_fence_sync.txt) and [GPU-side-wait extension](https://registry.khronos.org/EGL/extensions/KHR/EGL_KHR_wait_sync.txt)).

I think it more likely that `glFinish()` DTRT than me getting this magic right: I've tried reading the docs, but it looks non-trivial to insert `egl*` calls into this context, and I'm not sure how to use them.

**Review by RAOF — APPROVED** [review]
I *think* it will be easy enough to use fences here, but I'm happy to poke at that later and I guess we'll need the `glFinish` as a fallback in case the relevant extensions aren't supported.

It is surprisingly hard to find documentation on cross-thread, cross-context synchronisation, but `glFinish` *has* to be a big enough hammer.

bors r+

**Pull request merged**
