### PR TITLE
Split WlShell out from WaylandConnector

### PR DESCRIPTION
**Pull request by wmww**

### CODE REVIEW

**Review by graysonguarino — APPROVED** [review]

**Comment by Saviq** [comment]
bors retry

**Comment by AlanGriffiths** [comment]
I don't have a specific objection, but what does splitting WlShell out gain us?

**Comment by wmww** [comment]
Sanity? WaylandConnector is big anyway, there's no reason to clutter it with unrelated classes. Other shells all have their own files.

**Comment by AlanGriffiths** [comment]
bors retry

**Comment by wmww** [comment]
bors retry

**Comment by AlanGriffiths** [comment]
I see no reason why this change would cause the tests to run slow on Fedora 34.

bors retry

**Pull request merged**
