### PR TITLE
Fix transformation for Layout::TopRowFirst

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes: #3185

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
The error on rawhide looks unrelated:

```plain
2024-01-16T09:51:36.9234571Z [ 44%] Generating logind-session.h
2024-01-16T09:51:36.9235597Z cd /spread/mir/spread/build/build/src/server/console && gdbus-codegen --header --output logind-session.h --interface-prefix org.freedesktop.login1 --c-namespace Logind /spread/mir/src/server/console/logind-session.xml
2024-01-16T09:51:36.9235710Z Traceback (most recent call last):
2024-01-16T09:51:36.9235909Z   File "/usr/bin/gdbus-codegen", line 53, in <module>
2024-01-16T09:51:36.9236025Z     from codegen import codegen_main
2024-01-16T09:51:36.9236363Z   File "/usr/share/glib-2.0/codegen/codegen_main.py", line 29, in <module>
2024-01-16T09:51:36.9236465Z     from . import dbustypes
2024-01-16T09:51:36.9236746Z   File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
2024-01-16T09:51:36.9236847Z     from . import utils
2024-01-16T09:51:36.9237108Z   File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
2024-01-16T09:51:36.9237211Z     import packaging.version
2024-01-16T09:51:36.9237414Z ModuleNotFoundError: No module named 'packaging'
```

**Comment by AlanGriffiths** [comment]
By way of explanation, the matrix multiplication is creating a function that combines inverting with the supplied transform. And we should be applying `invert(transform(image))`, not `transform(invert(image))`

**Comment by RAOF** [comment]
**Commutivity!** :angry: 

> By way of explanation, the matrix multiplication is creating a function that combines inverting with the supplied transform. And we should be applying `invert(transform(image))`, not `transform(invert(image))`

Correct. And we apply the transformations by left-multiplication, so our final layout transform needs to be leftmost. Argh.

**Review by RAOF — APPROVED** [review]
Yes. Argh!

**Pull request merged**
