### PR TITLE
Fix resize of layer shell surfaces

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Fixes: #1986

### CODE REVIEW

**Review by wmww — APPROVED** [review]
LGTM, thanks!

bors r+

**Comment by RAOF** [comment]
This breaks the following wlcs tests:
```
[  FAILED  ] LayerSurfaceTest.gets_configured_with_supplied_size_even_when_anchored_to_edges
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_initially_positioned_correctly_for_anchor/7
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_initially_positioned_correctly_for_anchor/31
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_positioned_correctly_when_layout_changed/23
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_positioned_correctly_when_layout_changed/29
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_positioned_correctly_when_layout_changed/15
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_initially_positioned_correctly_for_anchor/25
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_initially_positioned_correctly_for_anchor/23
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_initially_positioned_correctly_for_anchor/27
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_initially_positioned_correctly_for_anchor/29
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_positioned_correctly_when_layout_changed/7
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_positioned_correctly_when_layout_changed/31
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_positioned_correctly_when_layout_changed/25
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_initially_positioned_correctly_for_anchor/15
[  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_positioned_correctly_when_layout_changed/27
```

Are the tests incorrect, or is this fix incorrect?

**Comment by AlanGriffiths** [comment]
> Are the tests incorrect, or is this fix incorrect?

The tests are clearly wrong: the compositor is entitled to (and needs to) send resize events to the surfaces. See linked bug.

Will investigate.

**Comment by AlanGriffiths** [comment]
Hmm. Looks like the code may be wrong:

>     <request name="set_size">
>       <description summary="sets the size of the surface">
>         Sets the size of the surface in surface-local coordinates. The
>         compositor will display the surface centered with respect to its
>         anchors.
> 
>         If you pass 0 for either value, the compositor will assign it and
>         inform you of the assignment in the configure event. You must set your
>         anchor to opposite edges in the dimensions you omit; not doing so is a
>         protocol error. Both values are 0 by default.

So we should only be sending size if the requested size is zero.

**Pull request merged**
