### PR TITLE
Add core mmap-backed SHM handling

### PR DESCRIPTION
**Pull request by RAOF**
There are a number of places where we need to deal with
file-descriptor-`mmap`-backed shared memory. Particularly,
with client-submitted file-descriptors. This most obviously
occurs with the `wl_shm` buffer allocator, but also protocols
like `zwp_virtual_keyboard` where a client-provided fd is
required for the keymap.

There are tricky edge cases that need to be handled with
untrusted shared memory which apply across all possible
uses of shm. Add some infrastructure to handle these.

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
LGTM

bors merge

**Comment by AlanGriffiths** [comment]
> Build failed:
> 
>     * [BuildAndTest (lxd:ubuntu-22.04:spread/build/sbuild:ubuntu_armhf)](https://github.com/MirServer/mir/actions/runs/3648946486/jobs/6162989130)

AIUI `ShmBacking.*` shouldn't be run there?

**Comment by Saviq** [comment]
The levels of indirection here… I [tried](https://github.com/MirServer/mir/commit/b3f7741496273d22548d35cb193edd117bdaa99e) adding it in [the two](https://github.com/MirServer/mir/commit/0301a925f36270de0228f56576d7c1d354a476c8) places where I thought this should go. Neither worked…

**Comment by RAOF** [comment]
Hmm `wlcs.Anchor/LayerSurfaceLayoutTest.* (Child aborted)`

**Review by AlanGriffiths — APPROVED** [review]
Still looks good, but I assume we want to land #2747 first?

bors delegate

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Comment by Saviq** [comment]
This won't work. Will wait for #2747 to land.

bors cancel

**Comment by AlanGriffiths** [comment]
bors retry

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Comment by Saviq** [comment]
bors cancel

I messed up the rebase.

**Comment by Saviq** [comment]
Last time. Pinky promise.

bors r=AlanGriffiths

**Pull request merged**
