### PR TITLE
Another attempt to define ioctl() consistently with the platform headers.

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
@z3ntu can you confirm whether this fixes your clang build?

**Comment by AlanGriffiths** [comment]
Marked no-merge until we know if it works

**Comment by z3ntu** [comment]
Builds with both GCC and Clang on Alpine.

**Comment by AlanGriffiths** [comment]
Thanks!

**Comment by AlanGriffiths** [comment]
For the record, the problem was reported against a merged PR: https://github.com/MirServer/mir/pull/686#issuecomment-457878757

**Pull request merged**
