### PR TITLE
Revert merge #1148

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Revert merge #1148 (Fixes: #1332)

I know we want most of this back again. But this gets us back to a working state.

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
@RAOF what I *think* is happening is that buffers are being released after being consumed by the first compositor. That begins a race between the second compositor using the buffer and the client destroying it. (But I've not spent time proving that theory - we can talk next week.)

**Comment by wmww** [comment]
Since this is a lot of code and most of it is probably good, I'm in favor of fixing it without reverting and then having to re-review the whole thing

**Comment by AlanGriffiths** [comment]
> Since this is a lot of code and most of it is probably good, I'm in favor of fixing it without reverting and then having to re-review the whole thing

It isn't hard to review a revert of a revert commit. Fixes can come on top of that.

**Comment by AlanGriffiths** [comment]
@wmww I'm curious does this also fix #1317? (If my theory is right it should, but I've reproduced.)

**Comment by wmww** [comment]
Don't have access to a screen right now. Will try to remember to test when I do

**Comment by wmww** [comment]
This does fix #1317

**Comment by AlanGriffiths** [comment]
Closing: We have a fix under review.

**Pull request closed without merging**
