### PR TITLE
wayland::LifetimeTracker

### PR DESCRIPTION
**Pull request by wmww**
Break out management of the destoryed flag into a new `LifetimeTracker` class so non-resource objects can inherit from it as well. Future PR will make `WindowWlSurfaceRole` use it.

### CODE REVIEW

**Comment by RAOF** [comment]
Additionally, as far as I can tell there's no need for `destroyed_flag` to be a `shared_ptr<bool>`? If `Weak<T>` stored a `weak_ptr<void>` it could simply check `.expired()`. That kinda suggests that we don't need a `Destroyable` helper at all?

**Comment by wmww** [comment]
> `DestroyTracker`, maybe?

Sure, that's fine

> this doesn't seem like an IS-A relationship, rather a HAS-A?

Under the hood, all C++ inheritance is basically just HAS-A. A class member would need to be consistently named and there would only ever be one in a class. A base class seemed like the most straightforward way to accomplish this. Having a random member that needs to have a specific name and is never directly used would only be confusing.

> there's no need for `destroyed_flag` to be a `shared_ptr<bool>`?

One of the reasons `shared_ptr<bool>` won out was because it's simply what we've already got. We can easily move things over to the new system bit by bit (there's still code that manually uses destroyed flags). Once everything is using `wayland::Weak`, it will be easy to switch to any preferable implementation.

Even then, I think inheriting from `DestroyTracker` is a lot more obvious then creating and owning a shared pointer of a specific name.

**Comment by RAOF** [comment]
> > `DestroyTracker`, maybe?
> 
> Sure, that's fine
> 
> > this doesn't seem like an IS-A relationship, rather a HAS-A?
> 
> Under the hood, all C++ inheritance is basically just HAS-A. A class member would need to be consistently named and there would only ever be one in a class. A base class seemed like the most straightforward way to accomplish this. Having a random member that needs to have a specific name and is never directly used would only be confusing.

I mean, *really* what we want here is Concepts.

:woman_shrugging: I don't mind *too* much, but when everything's switched over to `wayland::Weak` the interface will literally be “give me a weak pointer to something that's destroyed when the object is”, which is basically just storing an empty `shared_ptr`.

**Comment by wmww** [comment]
> I'd also be fine with `DestoryTracker` being an abstract interface, since it's totally trivial to implement.

It's *not* totally trivial though. There's no reason to duplicate the (admittedly small) piece of code on every class that wants to supports weak references. You seem to think having multiple copies of this:
```c++
public:
    /// Allows this object to be wayland::Weak
    auto destroyed_flag() const -> std::weak_ptr<void>
    {
        return destroyed;
    }

private:
    /// Used to track if this object has been destroyed
    std::shared_ptr<void> const destroyed{std::make_shared()};
```

or similar is preferable to

```c++
    : public DestroyTracker
```
And I don't understand why.

**Comment by RAOF** [comment]
You don't even need the `make_shared` bit;
```C++
public:
    auto destroyed_flag() const -> std::weak_ptr<void>
    {
        return destroyed;
    }

private:
    std::shared_ptr<void> const destroyed{nullptr};
```
suffices.

As to why: inheritance for the sake of code sharing can come with some unexpected warts. Admittedly, ones which I don't *think* we're likely to hit here, but that's the general principle behind my objections.

**Comment by AlanGriffiths** [comment]
> > 
> 
> Under the hood, all C++ inheritance is basically just HAS-A. A class member would need to be consistently named and there would only ever be one in a class. A base class seemed like the most straightforward way to accomplish this. Having a random member that needs to have a specific name and is never directly used would only be confusing.

No. HasA is a weaker relationship than IsA. But neither describes the design intended here. This is ImplementedUsing (if such a thing exists!)

HasA seems most appropriate, but would be implemented more like this:

```c++
class LifeTimeTracker
{
public:
    operator std::weak_ptr<bool>() const
    {
        return destroyed;
    }
...
};

class Foo
{
public:
    LifeTimeTracker const destroyed_flag;
};
```

**Comment by wmww** [comment]
That is indeed the way to do an actual HAS-A relationship, and not unacceptable, but I still don't get *why*. It seems strange to me to make the naming of a thing an essential part of its function. Why *not* just use inheritance? It keeps everything simply and tidy.

Btw, `LifeTimeTracker` is definitely a better name.

**Comment by AlanGriffiths** [comment]
> Why _not_ just use inheritance? It keeps everything simply and tidy.

Public inheritance would be a statement that "everywhere that uses a `Destroyable` can use a `Foo`" which is clearly not something we intend to say.

**Comment by wmww** [comment]
> Public inheritance would be a statement that "everywhere that uses a `Destroyable` can use a `Foo`" which is clearly not something we intend to say.

Is it... not exactly what we're trying to say? In what context is this statement false?

**Comment by RAOF** [comment]
So, I think I prefer #1581, once we've updated callers to use `Weak<T>` everywhere (since we're updating callers anyway).

**Comment by wmww** [comment]
What? Why?
```
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wayland_connector.cpp.o:(.data.rel.ro+0x128): undefined reference to `virtual thunk to mir::wayland::Compositor::~Compositor()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wayland_connector.cpp.o:(.data.rel.ro+0x130): undefined reference to `virtual thunk to mir::wayland::Compositor::~Compositor()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wayland_connector.cpp.o:(.data.rel.ro._ZTCN3mir8frontend7WlShell8InstanceE0_NS_7wayland5ShellE[_ZTCN3mir8frontend7WlShell8InstanceE0_NS_7wayland5ShellE]+0x48): undefined reference to `virtual thunk to mir::wayland::Shell::~Shell()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wayland_connector.cpp.o:(.data.rel.ro._ZTCN3mir8frontend7WlShell8InstanceE0_NS_7wayland5ShellE[_ZTCN3mir8frontend7WlShell8InstanceE0_NS_7wayland5ShellE]+0x50): undefined reference to `virtual thunk to mir::wayland::Shell::~Shell()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wayland_connector.cpp.o:(.data.rel.ro._ZTCN3mir8frontend14WlShellSurfaceE0_NS_7wayland12ShellSurfaceE[_ZTCN3mir8frontend14WlShellSurfaceE0_NS_7wayland12ShellSurfaceE]+0x90): undefined reference to `virtual thunk to mir::wayland::ShellSurface::~ShellSurface()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wayland_connector.cpp.o:(.data.rel.ro._ZTCN3mir8frontend14WlShellSurfaceE0_NS_7wayland12ShellSurfaceE[_ZTCN3mir8frontend14WlShellSurfaceE0_NS_7wayland12ShellSurfaceE]+0x98): undefined reference to `virtual thunk to mir::wayland::ShellSurface::~ShellSurface()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/data_device.cpp.o:(.data.rel.ro+0x128): undefined reference to `virtual thunk to mir::wayland::DataDeviceManager::~DataDeviceManager()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/data_device.cpp.o:(.data.rel.ro+0x130): undefined reference to `virtual thunk to mir::wayland::DataDeviceManager::~DataDeviceManager()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/data_device.cpp.o:(.data.rel.ro+0x250): undefined reference to `virtual thunk to mir::wayland::DataSource::~DataSource()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/data_device.cpp.o:(.data.rel.ro+0x258): undefined reference to `virtual thunk to mir::wayland::DataSource::~DataSource()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/data_device.cpp.o:(.data.rel.ro+0x3d8): undefined reference to `virtual thunk to mir::wayland::DataOffer::~DataOffer()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/data_device.cpp.o:(.data.rel.ro+0x3e0): undefined reference to `virtual thunk to mir::wayland::DataOffer::~DataOffer()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/data_device.cpp.o:(.data.rel.ro+0x570): undefined reference to `virtual thunk to mir::wayland::DataDevice::~DataDevice()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/data_device.cpp.o:(.data.rel.ro+0x578): undefined reference to `virtual thunk to mir::wayland::DataDevice::~DataDevice()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_subcompositor.cpp.o:(.data.rel.ro+0x270): undefined reference to `virtual thunk to mir::wayland::Subcompositor::~Subcompositor()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_subcompositor.cpp.o:(.data.rel.ro+0x278): undefined reference to `virtual thunk to mir::wayland::Subcompositor::~Subcompositor()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_subcompositor.cpp.o:(.data.rel.ro+0x368): undefined reference to `virtual thunk to mir::wayland::Subsurface::~Subsurface()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_subcompositor.cpp.o:(.data.rel.ro+0x370): undefined reference to `virtual thunk to mir::wayland::Subsurface::~Subsurface()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_surface.cpp.o:(.data.rel.ro+0x1c8): undefined reference to `virtual thunk to mir::wayland::Surface::~Surface()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_surface.cpp.o:(.data.rel.ro+0x1d0): undefined reference to `virtual thunk to mir::wayland::Surface::~Surface()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_surface.cpp.o:(.data.rel.ro._ZTCN3mir8frontend14WlSurfaceState8CallbackE0_NS_7wayland8CallbackE[_ZTCN3mir8frontend14WlSurfaceState8CallbackE0_NS_7wayland8CallbackE]+0x40): undefined reference to `virtual thunk to mir::wayland::Callback::~Callback()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_surface.cpp.o:(.data.rel.ro._ZTCN3mir8frontend14WlSurfaceState8CallbackE0_NS_7wayland8CallbackE[_ZTCN3mir8frontend14WlSurfaceState8CallbackE0_NS_7wayland8CallbackE]+0x48): undefined reference to `virtual thunk to mir::wayland::Callback::~Callback()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_seat.cpp.o:(.data.rel.ro+0x1a0): undefined reference to `virtual thunk to mir::wayland::Seat::~Seat()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_seat.cpp.o:(.data.rel.ro+0x1a8): undefined reference to `virtual thunk to mir::wayland::Seat::~Seat()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_keyboard.cpp.o:(.data.rel.ro+0xd0): undefined reference to `virtual thunk to mir::wayland::Keyboard::~Keyboard()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_keyboard.cpp.o:(.data.rel.ro+0xd8): undefined reference to `virtual thunk to mir::wayland::Keyboard::~Keyboard()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_pointer.cpp.o:(.data.rel.ro+0xe0): undefined reference to `virtual thunk to mir::wayland::Pointer::~Pointer()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_pointer.cpp.o:(.data.rel.ro+0xe8): undefined reference to `virtual thunk to mir::wayland::Pointer::~Pointer()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_touch.cpp.o:(.data.rel.ro+0xd0): undefined reference to `virtual thunk to mir::wayland::Touch::~Touch()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_touch.cpp.o:(.data.rel.ro+0xd8): undefined reference to `virtual thunk to mir::wayland::Touch::~Touch()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x550): undefined reference to `virtual thunk to mir::wayland::XdgShellV6::~XdgShellV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x558): undefined reference to `virtual thunk to mir::wayland::XdgShellV6::~XdgShellV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x648): undefined reference to `virtual thunk to mir::wayland::XdgSurfaceV6::~XdgSurfaceV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x650): undefined reference to `virtual thunk to mir::wayland::XdgSurfaceV6::~XdgSurfaceV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x720): undefined reference to `virtual thunk to mir::wayland::XdgPopupV6::~XdgPopupV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x728): undefined reference to `virtual thunk to mir::wayland::XdgPopupV6::~XdgPopupV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x868): undefined reference to `virtual thunk to mir::wayland::XdgToplevelV6::~XdgToplevelV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x870): undefined reference to `virtual thunk to mir::wayland::XdgToplevelV6::~XdgToplevelV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x978): undefined reference to `virtual thunk to mir::wayland::XdgPositionerV6::~XdgPositionerV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_v6.cpp.o:(.data.rel.ro+0x980): undefined reference to `virtual thunk to mir::wayland::XdgPositionerV6::~XdgPositionerV6()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x5a0): undefined reference to `virtual thunk to mir::wayland::XdgWmBase::~XdgWmBase()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x5a8): undefined reference to `virtual thunk to mir::wayland::XdgWmBase::~XdgWmBase()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x680): undefined reference to `virtual thunk to mir::wayland::XdgSurface::~XdgSurface()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x688): undefined reference to `virtual thunk to mir::wayland::XdgSurface::~XdgSurface()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x758): undefined reference to `virtual thunk to mir::wayland::XdgPopup::~XdgPopup()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x760): undefined reference to `virtual thunk to mir::wayland::XdgPopup::~XdgPopup()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x868): undefined reference to `virtual thunk to mir::wayland::XdgToplevel::~XdgToplevel()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x870): undefined reference to `virtual thunk to mir::wayland::XdgToplevel::~XdgToplevel()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x978): undefined reference to `virtual thunk to mir::wayland::XdgPositioner::~XdgPositioner()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_shell_stable.cpp.o:(.data.rel.ro+0x980): undefined reference to `virtual thunk to mir::wayland::XdgPositioner::~XdgPositioner()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_output_v1.cpp.o:(.data.rel.ro+0x1b0): undefined reference to `virtual thunk to mir::wayland::XdgOutputManagerV1::~XdgOutputManagerV1()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_output_v1.cpp.o:(.data.rel.ro+0x1b8): undefined reference to `virtual thunk to mir::wayland::XdgOutputManagerV1::~XdgOutputManagerV1()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_output_v1.cpp.o:(.data.rel.ro+0x270): undefined reference to `virtual thunk to mir::wayland::XdgOutputV1::~XdgOutputV1()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/xdg_output_v1.cpp.o:(.data.rel.ro+0x278): undefined reference to `virtual thunk to mir::wayland::XdgOutputV1::~XdgOutputV1()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/layer_shell_v1.cpp.o:(.data.rel.ro+0x260): undefined reference to `virtual thunk to mir::wayland::LayerShellV1::~LayerShellV1()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/layer_shell_v1.cpp.o:(.data.rel.ro+0x268): undefined reference to `virtual thunk to mir::wayland::LayerShellV1::~LayerShellV1()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/layer_shell_v1.cpp.o:(.data.rel.ro+0x380): undefined reference to `virtual thunk to mir::wayland::LayerSurfaceV1::~LayerSurfaceV1()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/layer_shell_v1.cpp.o:(.data.rel.ro+0x388): undefined reference to `virtual thunk to mir::wayland::LayerSurfaceV1::~LayerSurfaceV1()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_region.cpp.o:(.data.rel.ro+0xf0): undefined reference to `virtual thunk to mir::wayland::Region::~Region()'
/usr/bin/ld: frontend_wayland/CMakeFiles/mirfrontend-wayland.dir/wl_region.cpp.o:(.data.rel.ro+0xf8): undefined reference to `virtual thunk to mir::wayland::Region::~Region()'
```

**Comment by wmww** [comment]
bors r=AlanGriffiths

**Comment by wmww** [comment]
@AlanGriffiths perhaps you have some insight into why this is failing on Clang

**Comment by RAOF** [comment]
@wmww - you've added a virtual base class to the hierarchy, and this looks to have caused clang to decide to use some non-virtual thunks to call through in some cases. You'll need to add those to the .symbols exports for the link to work.

**Comment by wmww** [comment]
Thanks for adding those for me

bors r+

**Pull request merged**
