### PR TITLE
Untangle display and render platform

### PR DESCRIPTION
**Pull request by RAOF**
This splits `mg::Platform` into `DisplayPlatform` and `RenderingPlatform`,
splits the `create_host_platform` entrypoint into `create_display_platform`
and `create_rendering_platform`, and loads all available display and
rendering platforms.

At this point it only uses the first Display and Rendering module,
but further work will support using multiple Display and Rendering modules.

Closes: #1890

### CODE REVIEW

**Comment by RAOF** [comment]
Marked as a draft as the gbm-kms platform doesn't *quite* work right yet - clients get LLVMpipe rather than accelerated 3D.

**Comment by AlanGriffiths** [comment]
Looks like the usual "didn't build rpi-dispmanx locally first" errors. :grinning: 
```
2021-04-15T12:13:09.3158415Z /spread/mir/src/platforms/rpi-dispmanx/platform_symbols.cpp:67:43: error: ‘CreateRenderingPlatform’ is not a member of ‘mg’; did you mean ‘CreateRenderPlatform’?
2021-04-15T12:13:09.3160032Z    67 |     mir::assert_entry_point_signature<mg::CreateRenderingPlatform>(&create_rendering_platform);
2021-04-15T12:13:09.3161162Z       |                                           ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by RAOF** [comment]
Oh! It's because the rendering platform fails to probe!

**Comment by RAOF** [comment]
Oops. Looks like I need to resolve the conflicts first, though.

**Comment by AlanGriffiths** [comment]
> Oops. Looks like I need to resolve the conflicts first, though.

That's what you get when one of the platforms gets rewritten while you are refactoring them. :grimacing:

**Pull request merged**
