### PR TITLE
cmake: Fix running WLCS tests under ptest

### PR DESCRIPTION
**Pull request by RAOF**
This fixes running the WLCS tests under ptest, rather than silently(!) failing to run them and reporting success.

It also implements the ptest support for checking that the XFAIL tests actually fail.

### CODE REVIEW

**Comment by RAOF** [comment]
Unfortunately I suspect that this will fail CI, as we (somewhat accidentally) exclusively use ptest in CI, and so I think we've missed some WLCS regressions :cry:

**Comment by RAOF** [comment]
Test failure is #1940

**Comment by RAOF** [comment]
Tested against WLCS 1.2; adding a passing test to the exclusion list correctly fails, and dropping one of the excluded tests also correctly results in failure.

**Comment by AlanGriffiths** [comment]
So, with this:
```plain
97% tests passed, 13 tests failed out of 409

Total Test time (real) =  52.28 sec

The following tests FAILED:
          3 - wlcs.CopyCutPaste.* (Failed)
         50 - wlcs.TouchInputSubsurfaces/SubsurfaceTest.one_subsurface_to_another_fallthrough/0_fails (Failed)
         53 - wlcs.TouchInputSubsurfaces/SubsurfaceTest.pointer_input_correctly_offset_for_subsurface/0_fails (Failed)
         55 - wlcs.TouchInputSubsurfaces/SubsurfaceTest.subsurface_extends_parent_input_region/0_fails (Failed)
         63 - wlcs.WlShellSubsurfaces/SubsurfaceTest.one_subsurface_to_another_fallthrough/0_fails (Failed)
         66 - wlcs.WlShellSubsurfaces/SubsurfaceTest.pointer_input_correctly_offset_for_subsurface/0_fails (Failed)
         68 - wlcs.WlShellSubsurfaces/SubsurfaceTest.subsurface_extends_parent_input_region/0_fails (Failed)
         73 - wlcs.XdgShellStableSubsurfaces/SubsurfaceTest.one_subsurface_to_another_fallthrough/0_fails (Failed)
         76 - wlcs.XdgShellStableSubsurfaces/SubsurfaceTest.pointer_input_correctly_offset_for_subsurface/0_fails (Failed)
         78 - wlcs.XdgShellStableSubsurfaces/SubsurfaceTest.subsurface_extends_parent_input_region/0_fails (Failed)
         83 - wlcs.XdgShellV6Subsurfaces/SubsurfaceTest.one_subsurface_to_another_fallthrough/0_fails (Failed)
         86 - wlcs.XdgShellV6Subsurfaces/SubsurfaceTest.pointer_input_correctly_offset_for_subsurface/0_fails (Failed)
         88 - wlcs.XdgShellV6Subsurfaces/SubsurfaceTest.subsurface_extends_parent_input_region/0_fails (Failed)
```
We need wlcs 1.2 in mir-team/dev before can land?

**Comment by RAOF** [comment]
Actually, we need wlcs 1.2 in mir-team/dev *and* we need to have CI pull from mir-team/dev ;)

**Pull request closed without merging**
