### PR TITLE
Release 2.12.0

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
# ~rc3

[TestPlan](https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir)

Platform |20.04LTS|22.04LTS|22.10|23.04
-- | -- | -- | -- | --
gbm-kms |@AlanGriffiths|||
gbm-x11 |@AlanGriffiths|||
eglstream-kms |   |   |  
dispmanx |   |   | 

Console |20.04LTS|22.04LTS|22.10|23.04
-- | -- | -- | -- | --
minimal |@AlanGriffiths|||
linux-VT |@AlanGriffiths|||
logind |@AlanGriffiths|||

WM |20.04LTS|22.04LTS|22.10|23.04
-- | -- | -- | -- | --
floating |@AlanGriffiths|||
tiling |@AlanGriffiths|||
kiosk |@AlanGriffiths|||

**Comment by AlanGriffiths** [comment]
Huh! Was running some nested tests on miriway and it crashed. Investigating...

**Comment by AlanGriffiths** [comment]
# ~rc5

[TestPlan](https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir)

Platform |20.04LTS|22.04LTS|22.10|23.04
-- | -- | -- | -- | --
gbm-kms |||@AlanGriffiths|
gbm-x11 |||@AlanGriffiths|
eglstream-kms |   |   |  
dispmanx |   |   | 

Console |20.04LTS|22.04LTS|22.10|23.04
-- | -- | -- | -- | --
minimal |||@AlanGriffiths|
linux-VT |||@AlanGriffiths|
logind ||||

WM |20.04LTS|22.04LTS|22.10|23.04
-- | -- | -- | -- | --
floating |||@AlanGriffiths|
tiling ||||
kiosk ||||

**Comment by RAOF** [comment]
Runs correctly, outputs correctly, and correctly chooses eglstream platform on my nvidia system.

**Comment by AlanGriffiths** [comment]
bors merge

**Comment by AlanGriffiths** [comment]
bors retry

**Pull request merged**
