### PR TITLE
WIP: Adjust some tests for musl, ifdef out thread tests as they don't work

### PR DESCRIPTION
**Pull request by z3ntu**
Depends on #694 (for the `HAVE_PTHREAD_GETNAME_NP` define)

### CODE REVIEW

**Comment by z3ntu** [comment]
Some more will have to be adjusted probably.

**Comment by wmww** [comment]
All looks reasonable so far to me

**Comment by AlanGriffiths** [comment]
@z3ntu neither this nor #694 can land each depends on changed made in the other. Ideally, make independent PRs, if not PR one against the other so they can land in sequence.

**Comment by z3ntu** [comment]
#694 rebased on master compiles on Alpine. I don't see how #694 depends on this PR.

**Comment by z3ntu** [comment]
With the `current_thread_name()` method now throwing an exception, the tests don't even run through (and are marked as "failed") but just Abort the test run... Disabling all tests that call a method that calls `current_thread_name()` is impractical I think.

Suggestions?

**Comment by AlanGriffiths** [comment]
@z3ntu this should be obsoleted by #702 - could you confirm that works for you?

**Pull request closed without merging**
